### ISSUE TITLE
Build time performance regression

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#102]
I just pulled the latest TeaVM (I had been building against a version from a few weeks ago) and have that builds are taking significantly longer on one of my apps.  Before the update, build times were about 1 to 2 minutes.  After, build time is 5 minutes.

I'll upload the project to github and add a link.  Is there any other things I can do to help track this down?

**Comment by konsoletyper** [comment]
Did you try to enable/disable incremental build? Test project is very good idea. It gives me a chance to measure time and figure out what happens inside TeaVM.

**Comment by shannah** [comment]
I haven't played with incremental build.  We're doing builds through our build server so all builds are clean... we can't use incremental with this model.

I'm using an older pom.xml file (from when I first set up the port project) but according to the docs, the default value for `<incremental>` is `false` so I assume that it is set to "off".

**Comment by shannah** [comment]
Here is the project
https://github.com/shannah/propertycross-demo

If you want to see specifically the versions I'm comparing check out this:
https://github.com/shannah/cn1-teavm-builds/releases

(I keep a parallel project that we use for the version of TeaVM that is used on our build server).

[0.3.0-cn1-032](https://github.com/shannah/cn1-teavm-builds/releases/tag/0.3.0-cn1-032) takes a minute or so to build.

[0.3.0-cn1-033](https://github.com/shannah/cn1-teavm-builds/releases/tag/0.3.0-cn1-033) takes about 5 minutes.

**Comment by shannah** [comment]
Note:  This regression doesn't occur with all projects.  I have other projects that seem to be unaffected.

**Comment by konsoletyper** [comment]
I fixed this performance regression. With this fix all my demo apps work, also all tests pass. CN1 port works as well, but PropertyCross fails during search. May it be because of the wrong setup? Can you test this new branch which fixed performance regression?

**Comment by shannah** [comment]
Ahh yes.  The PropertyCross search requires a proxy to add "Allow-Origin" headers so that's likely not an issue.  Thanks so much for the fix.  I'll test it right away.

**Comment by shannah** [comment]
Wow!  This not only fixed the regression.  It improved on the previous state!  Now it only take 27 seconds to build PropertyCross.  Everything looks like it's still working too.
