### ISSUE TITLE
removeEventListener() doesn't work

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#103]
It seems that due to the way JSFunctors processed, calls to removeEventListener() don't work.

E.g.

~~~
element.addEventListener("click", myEventListener, false);
element.removeEventListener("click", myEventListener, false);
~~~

Will result in the listener being added but not removed.

When I look at the javascript code for this, I see the reason.

~~~~
element12345.addEventListener($rt_ustr($rt_s(548)), (function($instance, $property) { return function() {
            return $instance[$property].apply($instance, arguments);
        };})(ccih_HTML5Implementation1067_access$5002083($this.this$01149), $rt_ustr($rt_s(16))), 0);
element12345.removeEventListener($rt_ustr($rt_s(548)), (function($instance, $property) { return function() {
            return $instance[$property].apply($instance, arguments);
        };})(ccih_HTML5Implementation1067_access$5002083($this.this$01161), $rt_ustr($rt_s(16))), 0);
~~~~

It is because the actual event listener object is not what is registered as the listener.  Instead if generates a one-off function that calls the functor's method.  But we then don't have a reference to that function to be able to remove it later.

**Comment by shannah** [comment]
As a temporary workaround I am doing the following:

~~~~
@JSBody(params={"functor"}, script="return functor")
    private native static JSFunction _getFunctorFunc(JSObject o);
    
    @JSBody(params={"target", "eventType", "handler"}, script="target.addEventListener(eventType, handler, false)")
    private native static void _addEventListener(JSObject target, String eventType, JSFunction handler);
    
    @JSBody(params={"target", "eventType", "handler"}, script="target.removeEventListener(eventType, handler, false)")
    private native static void _removeEventListener(JSObject target, String eventType, JSFunction handler);
    
    private JSFunction addEventListener(JSObject target, String eventType, EventListener l) {
        JSFunction f = _getFunctorFunc(l);
        _addEventListener(target, eventType, f);
        return f;
    }
~~~~


Then I add my event listeners using:

~~~~
JSFunction handle = addEventListener(myElement, "click", myListener);
_removeEventListener(myElement, "click", handle);
~~~~

But it will be nice not to have to do this :)

**Comment by konsoletyper** [comment]
This issue is quite hard to struggle. For each object you should track its wrapper function as well. With Java objects implementing functor interfaces, it's fairly easy: we can just add field to the corresponding class. But what if we pass JSObject? We should add field in run-time, and this leads to deoptimization.

**Comment by konsoletyper** [comment]
I created `improve-functors` branch where I am trying to fix this issue. Could you please test with this branch?

**Comment by shannah** [comment]
I tested it on some apps and appears to be working correctly.  Importantly it doesn't appear to have broken anything either.
