### ISSUE TITLE
Move TeaVM debugger into a separate project

### ISSUE THREAD

**Issue by konsoletyper** [konsoletyper/teavm#11]
TeaVM debugger could work with GWT and bck2brwsr, if they produced proper .teavmdbg files. However, this is quite complex task to reimplement TeaVM's debug information generator. Also, it is not a good deal to install TeaVM plugin for debugging GWT or bck2brwsr. So debugger must be moved into a separate project.

**Comment by liraz** [comment]
That will be great, also let's please create another branch for IntelliJ 14.1.
I made it work in IntelliJ 14.1, and i would like to send you the pull request on this branch.

I see that variable inspection & strings are still not supported - not in Eclipse nor in the latest updates for the IntelliJ debugger.
You can see the variables, and their names correctly.. but the value of String objects does not appear and you cannot evaluate expression or add variables to watch.

I don't care one bit about Eclipse, but i am willing to invest some time to implement watch and expression evaluation in IntelliJ.

I want to start a development also for a debugger that works with GWT.
After a little bit of research, it seems that it'll take a lot of work to emulate the whole dependency evaluation done by the GWT framework, but we can certainly just check to which package the user declared to be used in his "gwt.xml" file.
And go through all classes there and add them to the debug information - will be faster to implement.. but will kill support for all other libraries except the application code.

Then generation of debug information can be added as "Facet" instead of the new tab you added to the current plugin implementation.
It'll be great to have a facet like we have for GWT that gives you the option to set the compiler options.

**Comment by konsoletyper** [comment]
> That will be great, also let's please create another branch for IntelliJ 14.1.
I made it work in IntelliJ 14.1, and i would like to send you the pull request on this branch.

I'm not sure whether creating a new branch for this purpose is a good idea

> You can see the variables, and their names correctly.. but the value of String objects does not appear and you cannot evaluate expression or add variables to watch.

Yes, that requires some amount of work to do.

> I don't care one bit about Eclipse, but i am willing to invest some time to implement watch and expression evaluation in IntelliJ.

Not sure whether it's an easy task. First, you have to write parser for pseudo-Java syntax, which is quite complicated. Second, TeaVM removes all unnecessary code, all unnecessary methods and fields. What if a users types something like `x.foo()`, and there is really no `foo` method compiled?

The only solution I can see is to reuse existing expression evaluation and somehow "capture" all field accesses and rewrite them with call to TeaVM debugger.

> I want to start a development also for a debugger that works with GWT.

Does not GWT have an existing debugger? I mean, IDEA supports source maps debugging. 

> Then generation of debug information can be added as "Facet" instead of the new tab you added to the current plugin implementation.

Thank you! I know little about developing plugins for IDEA. I'll try to use facets to configure TeaVM.

**Comment by liraz** [comment]
> I'm not sure whether creating a new branch for this purpose is a good idea
why? the 14.1 code doesn't compile for plugin SDK of IntelliJ 15 & up.

> Not sure whether it's an easy task. First, you have to write parser for pseudo-Java syntax, which is quite complicated.
You don't need to write a parser, java expression parsers are already available, please look at "jexl3" library - http://commons.apache.org/proper/commons-jexl/

> Second, TeaVM removes all unnecessary code, all unnecessary methods and fields. What if a users types something like x.foo(), and there is really no foo method compiled?
That's a problem indeed. Can't we have a way to reduce compiler optimization so no code is being omitted?.. for debugging purposes. 
I would suggest a compiler optimization like the levels available for you in GWT.

> Does not GWT have an existing debugger? I mean, IDEA supports source maps debugging.
Have you actually used it? the gwt super dev mode with source maps is not able to map variable names, can't watch expression nor evaluate - that's not enough for building and debugging complex systems.
Also the javascript debugger that maps you with chromes source maps works in a weird way, breakpoints are not reached, things are moving to other places, debug points sometimes break on JS code.
This where your debugger can actually solve this problem.

> Thank you! I know little about developing plugins for IDEA. I'll try to use facets to configure TeaVM.
Seems like you are going full steam with it, please update me on what i can contribute with.

**Comment by konsoletyper** [comment]
> why? the 14.1 code doesn't compile for plugin SDK of IntelliJ 15 & up.

Why should I maintain two different branches for only supporting different versions of an IDE? TeaVM supports different tools, if I created different branches for different sets of tools, I ended up with tons of branches. I think, a better approach is to write code that compatible between different versions of IDEA. If it becomes impossible, create separate module for each version of IDEA to contain version-specific code.

> Also 14.1 uses asm4 library, and asm4 doesn't like java 8, but the whole compiler is written in java 8.

Does IDEA use asm4 to instrument bytecode of TeaVM?

> You don't need to write a parser, java expression parsers are already available, please look at "jexl3" library - http://commons.apache.org/proper/commons-jexl/

What does it produce? A naked AST? What about resolution/type inference? What about interpreting these expressions in debugger context? I think, it's better to reuse IDEA PSI, if possible.

> That's a problem indeed. Can't we have a way to reduce compiler optimization so no code is being omitted?.. for debugging purposes. 

No, it's impossible. There are too many dependencies on dependency analyzer, and I can't omit it. What I can do (and going to do) is to disable several local optimizations, but not this one. There are two major reasons:

1. How should TeaVM select classes to compile? Unlike GWT, it does not require you to write something like `module.xml` file, which specified which classes to compile. Without it, TeaVM has to compile the entire (enormous) set of classes available via compiler's class path.
2. TeaVM is capable of generating coroutines to emulate threads and blocking I/O. It makes methods much slower, and TeaVM uses information provided by dependency analyzer to reduce amount of methods that need to be converted to coroutines. Without it every single method should become coroutine.

> Have you actually used it? the gwt super dev mode with source maps is not able to map variable names,

That's the problem indeed, but how can GWT solve this problem? All it can do is to produce source maps, which are limited. You have to hack GWT first to produce another format (for example, TeaVM format) of debug tables. However, it's possible to partially solve the problem by generating JS variables with names as close as possible to original Java names.
