### ISSUE TITLE
Ployglot Web UI Programming for JVM

### ISSUE THREAD

**Issue by crudbug** [konsoletyper/teavm#119]
I was tinkering with this idea in my head, and found out about TeaVM. Great project !

It matches very will with the polyglot programming platform - Vertx.io, which defines a set of core APIs, like a microkernel, and any JVM language bindings can be created to code language specific modules. All modules talk via event-bus, it also provides a web-connector for real-time events on the browser. 

It will great to match TeaVM with Vertx.

Rather than spending resources on |source to JS transpilers|, the bytecode to JS is the right approach here.

Thanks,
Alan

**Comment by konsoletyper** [comment]
Ok, you are free to ask questions and get any required support from me.
