### ISSUE TITLE
Catching NullPointerException in Java

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#123]
Currently NullPointerExceptions can't be caught using Java try/catch.  Is this something that can feasibly be supported?  Generally a nullpointer manifests itself with an Error like:

~~~~
TypeError: Cannot read property 'parent4256' of null at .......
~~~~

Some ideas for supporting this include:

1. Checking to see if the error is a TypeError, and setting the $je property on it to a NullPointerException if so.  This isn't ideal because some javascript errors that aren't nullpointers would then be turned into nullpointers.
2. Additionally check for keywords in the message of the error (like "of null") before adding the nullpointer.

These aren't perfect solutions but I think they would work without major down-sides.  What do you think?

**Comment by konsoletyper** [comment]
Why do you need to catch NPE? Generally, it is a bad practice. Can you check against `null` explicitly rather than catching NPE?

**Comment by shannah** [comment]
Agree it is bad practice.  I'm just running into it with code written by other people.  So far I have just fixed their code as I run into it.
