### ISSUE TITLE
Create ReactJS Component in TeaVM Java

### ISSUE THREAD

**Issue by zzj1213** [konsoletyper/teavm#152]
Is there a way to create the React JS Component in Java ?  The Component's properties and states are Java objects to trigger the render of the component ?

I saw there is JS.instantiate, but do not know how to use it.

**Comment by konsoletyper** [comment]
I don't know. I haven't ever used ReactJS. All interactions with JavaScript code are performed by [JSO](https://github.com/konsoletyper/teavm/wiki/Interacting-with-JavaScript), so you should look in this direction. Just wrap ReactJS API in Java classes and use it from Java.
