### ISSUE TITLE
Unable to download Eclipse Plugin for TeaVM

### ISSUE THREAD

**Issue by anupjava123** [konsoletyper/teavm#154]
HI,

Unable to download Eclipse Plugin for TeaVM from URL: http://teavm.org/eclipse/update-site/0.3.x/

Request you to pls. help with the same.

Thanks,

Anup.

**Comment by konsoletyper** [comment]
You should not download plugin from this link. Instead, you should specify this URL as a repository in Eclipse. Please, read about [installing Eclipse pligin](https://github.com/konsoletyper/teavm/wiki/Eclipse-tutorial#installing-teavm-plugin).

**Comment by anupjava123** [comment]
Thanks a lot.

**Comment by vic-cw** [comment]
@konsoletyper It seems that this wiki page no longer exists.

Any reason not to re-add it?

**Comment by konsoletyper** [comment]
The reason no to re-add it is Eclipse plugin is not supported anymore

**Comment by vic-cw** [comment]
Thanks for the swift response!

I am sad to read this. Is there a place somewhere I can read about this decision not to support it anymore?

**Comment by konsoletyper** [comment]
No, there's nothing to read. I just switched to IDEA myself and I have no time to maintain plugins for two IDEs.

**Comment by vic-cw** [comment]
Ok I understand, thanks

**Comment by vic-cw** [comment]
Ok I understand, thanks
