### ISSUE TITLE
Accessing a Java method from Javascript

### ISSUE THREAD

**Issue by bertung** [konsoletyper/teavm#155]
How do we access Java object methods from Javascript? Is it posible to make a Java method available to the window object as a Javascript method so that other Javascript code in that page can call it?

**Comment by konsoletyper** [comment]
TeaVM 0.3 does not support something similar to `@`-syntax in JSNI. Upcoming TeaVM 0.4 will support Java method invocation via the following notation:

```javascript
javaMethods.get("className.methodDesc").invoke(params);
```

See corresponding [test](https://github.com/konsoletyper/teavm/blob/master/jso/apis/src/test/java/org/teavm/jso/test/JavaInvocationTest.java) for example.

With current version of TeaVM you can pass Java callbacks to JavaScript code, see [documentation](https://github.com/konsoletyper/teavm/wiki/Interacting-with-JavaScript#passing-java-objects-to-javascript) and [test case](https://github.com/konsoletyper/teavm/blob/master/jso/apis/src/test/java/org/teavm/jso/test/FunctorTest.java).

**Comment by bertung** [comment]
This is good to hear.
