### ISSUE TITLE
Calling a JSFunctor from a JSBody script 

### ISSUE THREAD

**Issue by leobm** [konsoletyper/teavm#157]
Browser Console Error: "TypeError: a[b] is undefined"

comprehension gap by me or a bug ?

Here a simple example:

```
@JSFunctor
public interface JSFunction {

	public void apply();

}
```

```
public class Client {
        
    @JSBody(params = { "callback" }, script = "callback()")
    public static native JSObject test(JSFunction callback);

	public static void main(String[] args) {
		test(new JSFunction() {

			@Override
			public void apply() {
				//console.log("Hello JSFunction");
			}

		});
     }
}
```

**Comment by konsoletyper** [comment]
You should add `extends JSObject` to `JSFunction` declaration. I think TeaVM should have reported this as an error. So this is a bug, but it's a bug of TeaVM error reporter, not of compiler.

**Comment by leobm** [comment]
ok, thanks  this works.

on the wiki page https://github.com/konsoletyper/teavm/wiki/Interacting-with-JavaScript
is an example @JSFunctor in "Passing Java objects as JavaScript functions" without extending 
the JSObject.

**Comment by konsoletyper** [comment]
Thank you for pointing on this mistake. Fixed it.
