### ISSUE TITLE
Script with Object parameter type

### ISSUE THREAD

**Issue by nhuttrung** [konsoletyper/teavm#164]
Just a simple code as below:

```Java
public class TestApp {
  @JSBody(params={"msg"}, script="console.log(msg);")
  public static native void test01(Object msg);

  @JSBody(params={"msg"}, script="console.log(msg);")
  public static native void test02(String msg);

  public static void main(String[] args) {
    test01("Hello");
    test02("Hello");
  }
}
```

I expect there are two 'Hello' messages showed in the console log. However, it is not.
- My Chrome console shows something like:
jl_String1 {characters97: arraycls, hashCode98: 69609650, $id: 8}
Hello

- My Firefox console shows something like:
Object { characters97: Object, hashCode98: 69609650, $id: 8 }
Hello

I am not sure this is a bug or not. 
What's wrong with the method `test01`?

**Comment by konsoletyper** [comment]
It's not valid to pass Objects to `@JSBody` methods, see [here](https://github.com/konsoletyper/teavm/wiki/Interacting-with-JavaScript#running-javascript-code-from-java). I think that there is bug in TeaVM, so it does not report you about violation of this restriction.

**Comment by konsoletyper** [comment]
That's not an error that code produced by TeaVM does not work. The problem is that TeaVM should have reported about wrong usage of JSBody annotation. I added this error reporting.
