### ISSUE TITLE
EventObject & Listener

### ISSUE THREAD

**Issue by jtulach** [konsoletyper/teavm#165]
I tried to use TeaVM with one of the latest DukeScript tutorials and I failed. The charts tutorial is referencing java.util.EventObject and also java.util.EventListener and these aren't recognized by TeaVM. I am not sure what is the best way out? Steps to reproduce:

```
$ git clone http://github.com/DukeScript/dukescript-charts.git
$ cd dukescript-charts/
$ git checkout 9ed79d9b5a192a293baa61ab0707542a552016c0
$ mvn clean install -DskipTests
$ cd sample/client-web/
$ mvn -Pteavm package -DskipLicenses
```

the above yields a TeaVM compilation error:

```
[INFO] Building JavaScript file
[INFO] JavaScript file built with errors
[ERROR] Class java.util.EventObject was not found
    at net.java.html.charts.ChartEvent.<init>(ChartEvent.java:40)
    at net.java.html.charts.Chart.onClick(Chart.java:322)
    at net.java.html.charts.Chart.applyTo(Chart.java:126)
    at com.dukescript.charts.sample.ChartModel.lineLike(ChartModel.java:150)
    at com.dukescript.charts.sample.ChartModel.onPageLoad(ChartModel.java:75)
    at com.dukescript.charts.sample.BrowserMain.main(BrowserMain.java:34)
```

**Comment by konsoletyper** [comment]
Obviously, TeaVM emulation of JDK does not provide these two classes. You should rewrite your example without them

**Comment by jtulach** [comment]
Yes, that is something that can be done if one recompiles the charts library (https://dukescript.com/javadoc/charts/), but I doubt that end users of DukeScript will do that...

Btw. I tried to put fake implementation of java.util.EventObject and java.util.EventListener into the library sources, but it wasn't discovered and picked by the TeaVM compilation up. Is that explainable somehow or did I just messed up something?

**Comment by konsoletyper** [comment]
> Yes, that is something that can be done if one recompiles the charts library (https://dukescript.com/javadoc/charts/), but I doubt that end users of DukeScript will do that...

You should have tested this library with TeaVM before publishing it

> Btw. I tried to put fake implementation of java.util.EventObject and java.util.EventListener into the library sources, but it wasn't discovered and picked by the TeaVM compilation up. Is that explainable somehow or did I just messed up something?

Where do you add it? Into `classlib/src/main/java`? Did you prefix class names with 'T'? Please, examine `classlib` module for examples of other classes.

**Comment by jtulach** [comment]
I tried to put the missing classes into the sources of the project itself:
```diff
dukescript-charts$ git diff -r HEAD
diff --git a/sample/client-web/src/main/java/java/util/EventListener.java b/sample/client-web/src/main/java/java/util/EventListener.java
new file mode 100644
index 0000000..365f9fb
--- /dev/null
+++ b/sample/client-web/src/main/java/java/util/EventListener.java
@@ -0,0 +1,4 @@
+package java.util;
+
+public interface EventListener {
+}
diff --git a/sample/client-web/src/main/java/java/util/EventObject.java b/sample/client-web/src/main/java/java/util/EventObject.java
new file mode 100644
index 0000000..3f0cab9
--- /dev/null
+++ b/sample/client-web/src/main/java/java/util/EventObject.java
@@ -0,0 +1,6 @@
+package java.util;
+
+public class EventObject {
+    public EventObject(Object source) {
+    }
+}
```
If this worked, it would be easy for end users to workaround deficiencies in TeaVM...

**Comment by salmonb** [comment]
Perhaps a solution would be that TeaVM offers the equivalent of <super-source> in GWT?
Then TeaVM could use the EventObject.java you are providing.
What do you think?

**Comment by konsoletyper** [comment]
Rename your java.uitl.EventObject class to org.teavm.classlib.java.util.TEventObject

**Comment by jtulach** [comment]
Good advice. Thanks.
