### ISSUE TITLE
Need a comprehensive documentation

### ISSUE THREAD

**Issue by bertung** [konsoletyper/teavm#168]
We need a detailed documentation especially on overlays to make teavm a dependable choice for our platform.

**Comment by shannah** [comment]
I find the documentation already quite good.  If there are missing pieces, perhaps this is a good opportunity for the community to pick up some of the slack and contribute.  Specifically what kind of documentation are you finding lacking?

**Comment by bertung** [comment]
Very well, case closed.

**Comment by shannah** [comment]
My response wasn't meant to shut this case down.  I was rather suggesting that this might be an area the community can get involved with (I'm just a member of the community).  If there is specific documentation lacking, then I (or another member of the community) might be able to help here.

**Comment by bertung** [comment]
My simple take would be that some well documented examples for overlay types and JSObject will be very useful for the new comers.

**Comment by shannah** [comment]
I see.  You've probably read this page:

https://github.com/konsoletyper/teavm/wiki/Interacting-with-JavaScript

which covers the fundamentals.  But doesn't have full examples.

Not so many examples yet.  When I was learning, I found the best examples to be part of the source for TeaVM itself.

Here is an example of a TeaVM wrapper for the localforage library that I am using inside some of my projects.
https://gist.github.com/shannah/cba3ff19ba4f5c34052c

It includes quite a few of the Javascript interaction items, such as overlay types, JSProperty, JSBody, etc..

Perhaps adding a section to the wiki page for example like this would be helpful.

**Comment by bertung** [comment]
Yes, couple of step by step examples including the javascript side in some cases if necessary would be excellent for the new comers. Not everybody would want to read the relevant parts of the teavm source code. Overlay types are very powerful and needed to be understood well. Thank you for sharing your code example.

**Comment by bertung** [comment]
Also, a simple command line compilation tutorial is also needed.

**Comment by konsoletyper** [comment]
There's no command line tool for TeaVM. The only way to run TeaVM is to use it from Maven. Also, TeaVM plugin for Eclipse is capable to work stand-alone, without Maven at all (and of course, it can set-up itself according to pom.xml)

I think wiki documentation on overlay types is good enough to start. Of course, there might be some difficulties to start with it, and some developers need tutorials. Well, I suppose tutorials must be created separate from project's official wiki by project's community. Also, you may read examples in TeaVM source code. It's not that difficult as you would expect. You don't have to read implementation part, only look at existing API wrappers, they are quite simple: https://github.com/konsoletyper/teavm/tree/master/jso/apis/src/main/java/org/teavm/jso

And don't forget to ask direct questions on things you don't understand.

**Comment by bertung** [comment]
I will look into the "jso" directory further. Thanks.
