### ISSUE TITLE
Best way to convert JSON String to java.util.Map 

### ISSUE THREAD

**Issue by mirkosertic** [konsoletyper/teavm#170]
Hi there,

I am using TeaVM 0.4.1. What is the recommended way to convert a JSON String to a java.util.Map instance using JSO? 

The org.teavm.jso.json.JSON.parse() Method returns a JSObject. But it is possible to convert a JSObject to a java.util.Map instance?

My use case is to convert a JSON String to a java.util.Map instance and also do the reverse, translate a java.util.Map to a JSON String. Are there examples available how to do this with JSO?

**Comment by konsoletyper** [comment]
You can create your own wrapper for your JSON object like this:

```java
public interface MyJsonWrapper {
    @JSIndexer
    JSObject get(String key);
}
```

The only problem here is to extract the set of keys from the object. Unfortunately, JavaScript does not provide API similar to Java's Iterable and therefore you have to use special syntax (i.e. `for` .. `in` statement) for this purpose. So, write a simple JSBody like the following:

```java
@JSBody(params = "obj", script = ""
        + "var keys = [];"
        + "for (var key in obj) {"
            + "keys.push(key);"
        + "}"
        + "return keys;")
public static native String[] extractKeys(MyJsonWrapper obj);
```
