### ISSUE TITLE
Some thing similar to java.lang.reflect.Proxy?

### ISSUE THREAD

**Issue by bertung** [konsoletyper/teavm#172]
Class generation from a Java interface is not supported by Teavm as I presume (Generators in GWT). Would it be too hard to implement something similar to interface proxy mechanism offered by JVM?

**Comment by konsoletyper** [comment]
I'm not sure if I understood you, but I'll try to guess. You mean you lack for code generation/reflection/metaprogramming support in TeaVM? Well, there is such support, but it's not documented. You are free to extend TeaVM compiler via plugins, and plugins can generate TeaVM IR. This is the way of how I do JAX-RS proxies, JSON serializer and so forth. I agree, it's not very convenient way, but there is nothing I can propose right now. I am developing metaprogramming support as a part of Flavour framework, and I am going to include it into the next major release of TeaVM. The metaprogramming module offers more convenient way of generating code: you pass the lambda to a special method (Emitter.emit, Emitter.returnValue, etc) and these lambdas don't execute, but their bytecode it copied to the generated method bytecode. Here are some examples: https://github.com/konsoletyper/teavm-flavour/blob/refactor/mp/src/test/java/org/teavm/flavour/mp/test/MetaprogrammingTest.java

**Comment by bertung** [comment]
Yes exactly. thanks.
