### ISSUE TITLE
[Question] class library additions?

### ISSUE THREAD

**Issue by bertung** [konsoletyper/teavm#175]
Is there a discussion board such as gitter for teavm? anyways, I want to add some missing java classes such as "java.util.concurrent.ConcurrentHashMap", Is it allowed? Can I just put it into my jar file under
/java/util/concurrent directory?

**Comment by konsoletyper** [comment]
I guess, you can discuss here: https://groups.google.com/forum/#!forum/teavm
Or is there some difference between google groups and gitter?

Generally, you should give up when you miss some class in TeaVM. You can try to contribute, but generally it's more difficult than you can expect.

In your case a workaround is available. Look at [classlib](https://github.com/konsoletyper/teavm/tree/master/classlib) module. You can use the same package naming convention to create emulation for ConcurrentHashMap.

**Comment by bertung** [comment]
Yes, google groups will do, thanks.
