### ISSUE TITLE
Can we access javaMethods object from index.html?

### ISSUE THREAD

**Issue by bertung** [konsoletyper/teavm#176]
Can we access javaMethods object from index.html? If not how do we access java methods from index.html?

lets say I have a Hello class and there is a public "Hey" method. Can I access the method "Hey"? 
<pre>
&nbsp;&lt;!DOCTYPE html&gt;<br />&nbsp;&lt;html&gt;<br />&nbsp; &lt;head&gt;<br />&nbsp;&nbsp;&nbsp; &lt;title&gt;Main page&lt;/title&gt;<br />&nbsp;&nbsp;&nbsp; &lt;meta http-equiv="Content-Type" content="text/html;charset=utf-8"&gt;<br />&nbsp;&nbsp;&nbsp; &lt;script type="text/javascript" charset="utf-8" src="teavm/runtime.js"&gt;&lt;/script&gt;<br />&nbsp;&nbsp;&nbsp; &lt;script type="text/javascript" charset="utf-8" src="teavm/classes.js"&gt;&lt;/script&gt;<br />&nbsp;&nbsp;&nbsp; &lt;script&nbsp; type="text/javascript"&gt;<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; alert(javaMethods.get('org.myproject.Hello.hey(II)Ljava/lang/String;').invoke(0, 2));<br />&nbsp;&nbsp; &lt;/script&gt;<br />&nbsp;&nbsp; &lt;/head&gt;<br />&nbsp;&nbsp; &lt;body onload="main()"&gt;<br />&nbsp;&nbsp;&nbsp; &lt;!-- TODO: add HTML content --&gt;<br />&nbsp;&nbsp; &lt;/body&gt;<br />&nbsp;&lt;/html&gt;
</pre>

**Comment by konsoletyper** [comment]
No. `javaMethods` is not really an object. JSO implementation just capable of parsing script you specify in `@JSBody` and recognize syntactical construct involving `javaMethods` identifier. Then it just replaces corresponding expression with the direct invocation of a method. You can try to write a simple example and find what JS code is generated by TeaVM.

Why do you need such thing? In your case just put corresponding call in the beginning of `main` method, i.e.:

```java
Window.alert(Hello.hey(0, 2));
```

**Comment by bertung** [comment]
Our external script lives in another script library and we must interact with the teavm generated script. 

lets say we have "setNative" method defined to Window object in our outer script.
Will this work? Can I access the processService method this way from our outer script?
 
    @JSBody(params={}, script = "setNative(javaMethods.get('org.myproject.processService(Ljava/lang/String;Ljava/lang/String;IZ'));")
    static native void setProcessService();

    public void processService(String listenerId,String data, int responseCode,boolean binary) {
    }

**Comment by bertung** [comment]
How about this one? will window.processService call the processService method successfully?


public static void main(String[] args) {
       setProcessService();
}

@JSBody(params={}, script = "window.processService=function(listenerId,data,responseCode,binary){javaMethods.get('org.myproject.processService(Ljava/lang/String;Ljava/lang/String;IZ')).invoke(listenerId,data,responseCode,binary);}")
static native void setProcessService();

public void processService(String listenerId,String data, int responseCode,boolean binary) {
}

**Comment by konsoletyper** [comment]
Again, this won't work. The only thing you can do with `javaMethods.get` is to call it immediately. Consider another approach:

```java
public interface ProcessServiceExport extends JSObject {
    void process(String listenerId, String data, int responseCode, boolean binary);
}
public class ProcessService implements ProcessService {
    // some code here
}

public static void main(String[] args) {
    export("ProcessService", new ProcessService());
}

@JSBody(params = { "name", "service" }, script = "window[name] = service;")
private static void export(String name, JSObject service);
```

and call it this way:

```js
ProcessService.process("foo", "bar", 23, true);
```

This is a kind of hack, since TeaVM is not intended to be invoked from JavaScript directly.

**Comment by konsoletyper** [comment]
Your second solution seems working. Why suggesting? Just try it!

**Comment by bertung** [comment]
I design first then implement :). Thanks.
