### ISSUE TITLE
Sourcemaps not working in Chrome / incomplete

### ISSUE THREAD

**Issue by Meai** [konsoletyper/teavm#184]
Only works in Firefox for me, are there any other steps to do to make it work in Chrome?
And even in Firefox the sourcemaps seem fairly basic, I dont even get the variable names on the right. Pretty much only the step position works and that doesn't work for event handlers either. (the debugger stops but not inside the handleEvent method)

Can that be improved?

![capture](https://cloud.githubusercontent.com/assets/649922/12946974/68f029be-cff8-11e5-96e1-2316fa9bee79.PNG)

**Comment by konsoletyper** [comment]
I don't know why you can't make source maps working in Chrome. Please, open your Chrome DevTools configuration, and check whether source maps are enabled for JavaScript.

I can't do anything with variable names, it's a consequence of general misdesign of source maps. You can use Eclipse debugger, which shows proper variable names.

I don't understand what problems do you have with event handlers. Do you put breakpoint inside event handler? Does debugger stop on the breakpoint when you actually raise an event (i.e. click a button)?

**Comment by Meai** [comment]
Yes in Chrome the sourcemaps are enabled, I'm opening the same exact html file. Anyway, if you say it works i guess the problem must be with me.

What is wrong with source maps? You can try and propose a change for firefox at least:
https://github.com/mozilla/source-map

For the event thing: the debugger stops but it doesnt highlight the line and it doesnt really jump in there because even the basic a,b, this variables are missing.

**Comment by konsoletyper** [comment]
There's everything wrong with source maps. In particular, there is no support of naming local variables (i.e. instruction that in a certain region of JS code we should show variable X as Y). There is naming support, but is very limited. It requires to specify renaming for every occurrence. Also, renamings go in one stream with line numbers, so to simply rename a variable occurence, I have to report line number information again and again. Also, support of these renamings used to be poor. I can recheck current situation, but anyway I'll end up with bloated source maps file

Yes, I can propose a change, and maintainers can just ignore my complain (which is quite usual) or claim that I don't really need this and I do wrong things.

As for event handlers: please, give me your code. I'll try to reproduce the issue on my side.
