### ISSUE TITLE
calling main('foo') will give each char as entry in main(String[] args)

### ISSUE THREAD

**Issue by michaelmosmann** [konsoletyper/teavm#190]
html:
`<body onload="main('foo','bar')">`

java:
`    public static void main(String[] args) {`
`        StringBuilder sb=new StringBuilder();`
`        for (String arg : args) {`
`            sb.append(arg);`
`            sb.append("|");`
`        }`
`                `
`        Console.message("works "+sb.toString());`
`    }`

console:
`works f|o|o`

**Comment by konsoletyper** [comment]
You should write `<body onload="main(['foo','bar'])">`

**Comment by michaelmosmann** [comment]
Thanks:)
