### ISSUE TITLE
System.out.println with float cause exception.

### ISSUE THREAD

**Issue by Wolftein** [konsoletyper/teavm#191]
When trying to use System.out.println with float or double an exception is thrown.

Example: System.out.println(3.0f);

**Comment by konsoletyper** [comment]
Are you sure it's exception? Probably, TeaVM compiler fairly reports error, since TeaVM's class library does not support `PrintStream.print(float)`, as you can see [here](http://teavm.org/jcl-support/0.3.x/classes/java.io.PrintStream.html).

**Comment by Flame6332** [comment]
fix it by changing it to: println("" + 3.0f);

**Comment by teras** [comment]
Is there any reason why print(float), print(boolean) etc is not supported? And how can we help with this?
To my naive eyes,  adding appropriate methods in classlib/src/main/java/org/teavm/classlib/java/io/TPrintStream.java it seems rather trivial?

**Comment by konsoletyper** [comment]
Yes, it's pretty trivial. The only reason I didn't implement them is the lack of time and the need to implement more important things.
