### ISSUE TITLE
Static fields with default string values cause uncaught TypeError, since string pool is not yet initialized

### ISSUE THREAD

**Issue by Wolftein** [konsoletyper/teavm#196]
It will fail to execute with "app.js:445Uncaught TypeError: Cannot read property '0' of undefined"

How to reproduce

``` java
    public final static String CONST1 = "FIRST";
    public  final static String CONST2 = "SECOND";

    boolean isTrue = (new Random().nextBoolean());

    StringBuffer buf = new StringBuffer(10);
    buf.append((isTrue ? CONST1 : CONST2)).append(" ");
    System.out.println(buf.toString());
```

Expanding it works

``` java
    public final static String CONST1 = "FIRST";
    public  final static String CONST2 = "SECOND";

    boolean isTrue = (new Random().nextBoolean());

    StringBuffer buf = new StringBuffer(10);
        if (isTrue)
        {
            buf.append(CONST1).append(" ");
        }
        else
        {
            buf.append(CONST2).append(" ");
        }
    System.out.println(buf.toString());

**Comment by konsoletyper** [comment]
Could not reproduce this issue. Please, post complete code sample which helps to reproduce the issue. I wrote the following test:

```java
    @Test
    public void issue196() {
        boolean isTrue = condition();

        StringBuilder buf = new StringBuilder();
        buf.append(isTrue ? Constants.CONST1 : Constants.CONST2);

        assertEquals("FIRST", buf.toString());
    }

    private boolean condition() {
        return true;
    }

    static class Constants {
        public final static String CONST1 = "FIRST";
        public final static String CONST2 = "SECOND";
    }
```

and it produces JS like this:

```javascript
function otcjl_VMTest_issue196($this) {
    var a, b, c;
    a = otcjl_VMTest_condition($this);
    b = jl_StringBuilder_$init();
    if (a == 0) {
        c = $rt_s(0);
    } else {
        c = $rt_s(1);
    }
    jl_StringBuilder_append(b, c);
    oj_Assert_assertEquals($rt_s(1), jl_StringBuilder_toString(b));
    return;
}
```

I used TeaVM from `master` branch.

**Comment by Wolftein** [comment]
It works if the constants are declared in a different class, otherwise it fails.

**Comment by konsoletyper** [comment]
Please, don't try to speculate. Post a code that causes the problem, so that I could reproduce it.

**Comment by konsoletyper** [comment]
Also, when you post error messages, don't forget to attach generated JS code and a complete stack trace.

**Comment by Wolftein** [comment]
```java
public final class Example {
    public final static String CONST1 = "FIRST";
    public final static String CONST2 = "SECOND";

    public static void main(String[] argv) {
        boolean isTrue = (new Random().nextBoolean());

        StringBuilder buf = new StringBuilder();
        buf.append(isTrue ? CONST1 : CONST2);

        System.out.println(buf.toString());
    }
}

**Comment by konsoletyper** [comment]
I found the reason. Usually, javac does not put `getstatic` instructions in such cases, instead it can inline constants with `ldc`. However, for some reason (probably, a bug) javac does not inline constants in conditional expressions. `CONST1` and `CONST2` do not get their value via `<clinit>` method, instead they have default values specified. TeaVM initializes them via `$rt_s`, which requires string pool to be prepared. String pools are initialized after all declarations, so string pool has `undefined` value when static fields compute their default values. A probable solution would be to initialize string static fields after initialization of string pool.
