### ISSUE TITLE
Using "org.eclipse.collections" won't generate any code.

### ISSUE THREAD

**Issue by Wolftein** [konsoletyper/teavm#202]
I have updated my project to use "org.eclipse.collections" (https://www.eclipse.org/collections/) and when i try to compile with TeaVM it won't generate any code and won't throw any exception nor display any log at all.

All i'm getting in app.js is

``` javascript
main = $rt_mainStarter(main);

//# sourceMappingURL=app.js.map
```

app.js.map

```
{"version":3,"file":"app.js","sourceRoot":"src","sources":[],"names":[],"mappings":""}
```

``` java
  public static void main(String[] argv) {
        FastList<Integer> container = new FastList<>();
        container.add(3);
        System.out.println(container.get(0));
    }
```

**Comment by konsoletyper** [comment]
Can't reproduce the bug. Can you send me a minimum project that causes the issue?
