### ISSUE TITLE
Cannot build archetype project with 0.4.3

### ISSUE THREAD

**Issue by aragozin** [konsoletyper/teavm#207]
I use following command to generate project 

    mvn8 archetype:generate -DarchetypeGroupId=org.teavm -DarchetypeArtifactId=teavm-maven-webapp -DarchetypeVersion=0.4.3 -DgroupId=test -DartifactId=test -Dversion=0.1-SNAPSHOT

After fixing `<teavm.version>` property to 0.4.3, I'm trying to build it with `mvn clean package` command, but compilation fails with message below ([full log in attached](https://github.com/konsoletyper/teavm/files/409718/log.txt)).

	[INFO] Building JavaScript file
	[INFO] JavaScript file built with errors
	[ERROR] Substitutor for bootstrap method java.lang.invoke.LambdaMetafactory.metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; was not found
		at java.time.temporal.TemporalQueries.<clinit>
		at java.util.Formatter$FormatSpecifier.print(Formatter.java:4156)
		at java.util.Formatter$FormatSpecifier.print(Formatter.java:4060)
		at java.util.Formatter$FormatSpecifier.printDateTime(Formatter.java:2832)
		at java.util.Formatter$FormatSpecifier.print(Formatter.java:2740)
		at java.util.Formatter.format(Formatter.java:2508)

Project is not working with eclipse plugin 0.4.3 either.
Problem is not reproducing with 0.4.2 version.

**Comment by konsoletyper** [comment]
Seems that `teavm-classlib` missing in project dependencies

**Comment by aragozin** [comment]
Project is generated from archetype without modifications. `teavm-classlib` is present

	<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	  <modelVersion>4.0.0</modelVersion>

	  <groupId>test</groupId>
	  <artifactId>test</artifactId>
	  <version>0.1-SNAPSHOT</version>
	  <packaging>war</packaging>

	  <properties>
		<java.version>1.8</java.version>
		<teavm.version>0.4.2</teavm.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	  </properties>

	  <dependencies>
		
		<dependency>
		  <groupId>org.teavm</groupId>
		  <artifactId>teavm-classlib</artifactId>
		  <version>${teavm.version}</version>
		  <scope>provided</scope>
		</dependency>
    ...

**Comment by konsoletyper** [comment]
That's definitely misconfiguration, TeaVM for some reason can't find `teavm-classlib` artifact. You can try following:

1. Change `teavm.version` property to 0.4.3 (I noticed you have 0.4.2 there)
2. Remove `provided` scope from `teavm-classlib` dependency
3. Put `teavm-classlib` dependency inside correspondong TeaVM `plugin` section

**Comment by konsoletyper** [comment]
Also, I examined your log and found the following message:

```
[WARNING] error reading C:\WarZone\tools\maven-repos\default\org\teavm\teavm-classlib\0.4.3\teavm-classlib-0.4.3.jar; invalid LOC header (bad signature)
```

It seems that `teavm-classlib` is properly attached to your maven configuration, but for some reason it's corrupt. Please, solve this problem, it's unrelated to TeaVM.
