### ISSUE TITLE
Allow writing native functions in separate JS files

### ISSUE THREAD

**Issue by sriharshachilakapati** [konsoletyper/teavm#208]
For native functions which are too large it gets uncomfortable to write that amount of code in strings of JSBody annotation. I think support for writing these functions in a separate JS files will be nice, and also keeps my code readable and organised with IDE support as well.

**Comment by konsoletyper** [comment]
Why don't you just put this separate JS files to your web resources and put calls to functions in the JS files to `@JSBody`?

In case of TeaVM supporting this feature directly, how it's expected to specify which JS code in the JS file matches a certain method in Java?

**Comment by sriharshachilakapati** [comment]
I'm currently using GWT, but am planning to move my codebase to use TeaVM. And am not actually sure if I can call `javaMethods.get(...)` from external JS files. Would love if there is some support like how we do JNI code in standard Java.

~~~js
function jsni_com_example_MyClass_funct(arguments)
{
    ....
}
~~~

I'm also happy to try out alternative approaches. Thanks for your time. What do you think about this?

**Comment by konsoletyper** [comment]
You really don't need to write large `JSBody` with TeaVM. If you have a large JS method, you can really write it as a Java method with several calls to small JS code pieces. My experience with TeaVM shows that it's almost always is true.

Also, you don't need to use `javaMethods.get()` often. In GWT/JSNI it was the only way to call Java from JS. In GWT/JsInterop, as well as in TeaVM JSO you have [another ways](https://github.com/konsoletyper/teavm/wiki/Interacting-with-JavaScript#passing-java-objects-to-javascript) of calling Java from JS.
