### ISSUE TITLE
[QUESTION] Easy way to convert JSArray to int[]

### ISSUE THREAD

**Issue by bertung** [konsoletyper/teavm#212]
Is there an easy way to convert JSArray which consists of an integer array to java int[] other than manually looping over the JSArray and craete an integer array.

**Comment by konsoletyper** [comment]
The answer is short: no, you can't. Do you experience problems with performance? Is there hot code that relies on JSArray -> int[] conversion?

**Comment by bertung** [comment]
We are unable to run our code with TeaVM yet because of the bug I reported earlier. I was just curious. I will have a pretty good performance comparison with GWT though when we start running with TeaVM. GWT compiled apps running very fast using GWT 2.7. Will try 2.8 next week.
