### ISSUE TITLE
ByteArrayInputStream.read() Bug

### ISSUE THREAD

**Issue by sio29** [konsoletyper/teavm#213]
ByteArrayInputStream.read()  returned as an int in the range 0 to 255.
But TeaVM returned  as an int in the range -128 to 127.

**Comment by bertung** [comment]
Byte is signed in Java. The returned value is correct. The following code will give you the value you seek (0-255).

```
  public static int unsignedToBytes(byte b) {
    return b & 0xFF;
  }
```
