### ISSUE TITLE
Redundant code in produced javascript output

### ISSUE THREAD

**Issue by bertung** [konsoletyper/teavm#214]
* Unused static final fields can be removed. They are all kept.

Interesting, almost all methods and fields are kept that references unused classes. There are huge classes that are never used but a field references it and that field is never used. I think that class may be purged entirely and that field may be replaced with a dummy javascript field. For example,

```
public class A {
   Column col;
   ...(tons of other code)
}
```

col is not used in runtime at all. The setters/getters or any other method that initializes it are not called. Teavm still puts that gigantic Column class in the produced javascript anyways.

**Comment by konsoletyper** [comment]
I can prove you that your assumption is wrong by the following code snippet:

```java
package org.teavm.samples.hello;

public final class Client {
    private Client() {
    }

    public static void main(String[] args) {
        System.out.println(new A().bar());
    }

    private static class A {
        B b;

        int bar() {
            return 23;
        }
    }

    private static class B {
        void foo() {
            System.out.println("BBB");
        }
    }
}
```

ahich does not produce any code for `B`, nor does it include `b` field at all.

**Comment by bertung** [comment]
Very well
