### ISSUE TITLE
Compiling with own code

### ISSUE THREAD

**Issue by WhiteTrashLord** [konsoletyper/teavm#222]
I want to start the compiling process with my own code. So I don't want to use any plugins.
Could you please provide an example how to achieve this for the latest version ( 0.4.3 )?

I want to compile all the files in a specified folder and the output should be written to another folder.
I tried the code snippet in the class TeaVM but it seems to be outdated.
So far I failed to get any Javascript code :(

**Comment by konsoletyper** [comment]
No, I won't provide any clues. There's Maven plugin for you, just read docs and use it. You can find 3rd party Gradle plugin and learn it. It author did not ask me the questions, he just read through the code and found out how to embed TeaVM himself.
