### ISSUE TITLE
Bug in try catch statements

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#230]
I have run into a bug in the generation of a try-catch statement.

The original java looks like:

~~~~
    while(codenameOneRunning) {
            try {
                // wait indefinetly Lock surrounds the should method to prevent serial calls from
                // getting "lost"
                 synchronized(lock){
                     if(shouldEDTSleep()) {
                         impl.edtIdle(true);
                         lock.wait();
                         impl.edtIdle(false);
                     }
                 }

                edtLoopImpl();
            } catch(Throwable err) {
                if(!codenameOneRunning) {
                    return;
                }
                err.printStackTrace();
                if(crashReporter != null) {
                    CodenameOneThread.handleException(err);
                }
                if(!impl.handleEDTException(err)) {
                    if(errorHandler != null) {
                        errorHandler.fireActionEvent(new ActionEvent(err,ActionEvent.Type.Exception));
                    } else {
                        Dialog.show("Error", "An internal application error occurred: " + err.toString(), "OK", null);
                    }
                }
            }
        }
~~~~

The resulting Javascript is (or at least some of it is):

~~~~
    case 13:
        $bb: {
            $bc: {
                try {
                    ccu_Display_edtLoopImpl(this_0);
                    if ($rt_suspending()) {
                        break $main;
                    }
                } catch ($e) {
                    $je = $e.$javaException;
                    if ($je && $je instanceof jl_Throwable) {
                        // err = $je;     <--- Adding this resolves this issue... but it is missing when generated
                        break $bc;
                    } else {
                        throw $e;
                    }
                }
                var$5 = this_0.$codenameOneRunning;
                if (var$5 == 0) {
                    break $bb;
                }
                try {
                    vkb = ccu_Display_lock;
                    $ptr = 5;
                    continue $main;
                } catch ($e) {
                    $je = $e.$javaException;
                    if ($je && $je instanceof jl_Throwable) {
                    } else {
                        throw $e;
                    }
                }
            }
            if (this_0.$codenameOneRunning == 0) {
                return;
            }
            jl_Throwable_printStackTrace(err);  // <------- err is undefined here
            if (this_0.$crashReporter !== null) {
                $ptr = 11;
                continue $main;
            }
~~~~

The problem is that `err` is undefined when it reaches this line:

~~~~
jl_Throwable_printStackTrace(err);
~~~~

The problem is resolved if I manually assign `err = $je` in the original try/catch as shown in the snippet above.

I have created a project that demonstrates this issue at https://github.com/shannah/teavm-exception-bug-test

The fully-built project .war file (which includes a servlet proxy for http requests -- may be necessary to reproduce issue is [here](https://github.com/shannah/teavm-exception-bug-test/blob/master/7936560e-3da8-4c2b-ad2c-ea9c438b4381-1479340802321-JSCookiesTest-1.0.war?raw=true)

You should be able to run this war directly in any container.  Press the "Throw Exception" button to reproduce the error at runtime.

**Comment by ilanov** [comment]
What's the status of this issue?
I face the exact same problem.
You can easily reproduce it using the below trivial code:
    public void func1() throws Exception {
        throw new Exception("Bla Bla...");
    }
    
    public void func2() {
        try {
            func1();
        }catch(Exception je) {
            Log.p(je.toString());
        }
    }

Now simply call func2()

**Comment by konsoletyper** [comment]
Did you try to build latest TeaVM from source code?

**Comment by ilanov** [comment]
No. I'm using Codename one platform, so I'm bound to their releases and build server.
Are you aware to this bug?

**Comment by shannah** [comment]
We are not using the latest sources.  This is on my todo list for Monday,
and the first thing I will be trying is to build from latest sources.

Steve

**Comment by ilanov** [comment]
Great. Just a hint...

As a workaround I modified the code to:

    public void func1() throws Exception {
        throw new Exception("Bla Bla...");
    }
    
    public void func2() {
        try {
            func1();
        }catch(Exception $je) {
            Log.p($je.getMessage());
        }
    }

Since $je holds the right information, I "cheat" and use this name...

**Comment by shannah** [comment]
I have confirmed that this issue still exists with the latest TeaVM sources.

**Comment by konsoletyper** [comment]
@shannah the issue is not reproducible with trivial try/catch statement, but your example still causes a bad code generated. I'll investigate it later.

**Comment by konsoletyper** [comment]
Looks like this problem disappeared in your example as well. I found out that I misconfigured build, when I applied latest TeaVM, I got the working app.

**Comment by ilanov** [comment]
@shannah can you please recheck it with CN1 platform? there is also an issue that when an error occurs in the network threads (when trying to connect to a server while it is down, for example), they get killed. It might be related to the same issue...

**Comment by shannah** [comment]
@ilanov Add the build hint

javascript.teavm.version=1.0.0-cn1-008

This will cause it to build with the latest TeaVM version (I just uploaded it).

That will confirm whether your issue is fixed for your app.

**Make sure you remove this build hint when you're done**.  It is undocumented and for development purposes, and could screw up future builds for you when I update TeaVM again.

**Comment by ilanov** [comment]
It doesn't help. Now the input to the exception in "undefined".
The issue is not fix.

konsoletyper, are you sure that you've tried the below code and not the workaround that I've mentioned?

public void func1() throws Exception {
    throw new Exception("Bla Bla...");
}

public void func2() {
    try {
        func1();
    }catch(Exception je) {
        Log.p(je.toString());
    }
}

func2()

**Comment by ilanov** [comment]
That's the network failure thread that I've described. I don't know whether it is teavm or CN1 issue...
Exception in the network thread should not kill it. As you can see, the exception gets null...
![image](https://cloud.githubusercontent.com/assets/15261457/22311518/760f5296-e35c-11e6-8eec-1a5ba5349fc9.png)

**Comment by shannah** [comment]
I have put together a new test case with the snippet you provided.  The Pertinent bit of JS code is:

~~~~
function cmt_TestJSException_func2($this) {
    var $je, $$je, $ptr, $tmp;
    $ptr = 0;
    if ($rt_resuming()) {
        var $thread = $rt_nativeThread();
        $ptr = $thread.pop();$je = $thread.pop();$this = $thread.pop();
    }
    $main: while (true) { switch ($ptr) {
    case 0:
        $ba: {
            try {
                cmt_TestJSException_func1($this);
            } catch ($$e) {
                $$je = $$e.$javaException;
                if ($$je && $$je instanceof jl_Exception) {
                    break $ba;
                } else {
                    throw $$e;
                }
            }
            return;
        }
        $je = jl_Object_toString($je);   // <----- $je is undefined.  We need $$je there instead
        $ptr = 1;
    case 1:
        cci_Log_p($je);
        if ($rt_suspending()) {
            break $main;
        }
        return;
    default: $rt_invalidPointer();
    }}
    $rt_nativeThread().push($this, $je, $ptr);
}
~~~~

Chrome debugger break on this line:

![image](https://cloud.githubusercontent.com/assets/2677562/22311738/cd16b0e6-e309-11e6-9d84-ac14c5cf50ae.png)

**Comment by shannah** [comment]
Alexey, here is a test project to reproduce this issue.

https://github.com/shannah/teavm-issue-230

**Comment by ilanov** [comment]
shannah can you please integrate the fix within CN1 platform?

**Comment by shannah** [comment]
@ilanov It will be deployed on Friday. 
You can access it before then with the build hint
javascript.teavm.version=1.0.0-cn1-009

But be sure to remove this hint after Friday so it doesn't override future updates that we make.
