### ISSUE TITLE
spring boot starter for backend side JavaScript generation

### ISSUE THREAD

**Issue by mirkosertic** [konsoletyper/teavm#232]
I use compile time JavaScript generation combined with the Maven plugin to package a web application. This process also includes bower packaging and other steps. During my development cycle, i often just need to replace the JavaScript part. So i wrote a simple spring boot starter which generates the JavaScript on the fly while in development mode, and production packaging stays the same.

I'd like to contribute this starter, if interesting for other coders:-)

**Comment by konsoletyper** [comment]
Why don't you just use IDE integration for this purpose?

**Comment by mirkosertic** [comment]
Where can i find the IDEA Plugins for 0.4.x?

**Comment by konsoletyper** [comment]
There's no IDEA plugins for 0.4.x, only for `master` version.

**Comment by mirkosertic** [comment]
Closed as no longer relevant.
