### ISSUE TITLE
"Cannot use undeclared label"

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#234]
Building with the latest TeaVM sources I get an error in a test case that works for older versions of TeaVM.

Compiled Javascript:

~~~~
function ccih_HTML5Implementation_blobToDataURL($blob) {
    ccih_HTML5Implementation_$callClinit();
    var $out, $complete, $lock, var$5, var$6, $$je, $ptr, $tmp;
    $ptr = 0;
    if ($rt_resuming()) {
        var $thread = $rt_nativeThread();
        $ptr = $thread.pop();var$6 = $thread.pop();var$5 = $thread.pop();$lock = $thread.pop();$complete = $thread.pop();$out = $thread.pop();$blob = $thread.pop();
    }
    $main: while (true) { switch ($ptr) {
    case 0:
        $out = $rt_createArray(jl_String, 1);
        $complete = $rt_createBooleanArray(1);
        $lock = jl_Object__init_();
        var$5 = window;
        var$6 = ccih_HTML5Implementation$37__init_($out, $complete, $lock);
        var$5.BlobToBase64($blob, otji_JS_function(var$6, "callback"));
        $ptr = 1;
    case 1:
        jl_Object_monitorEnter($lock);
        if ($rt_suspending()) {
            break $main;
        }
        $ba: {
            $bbb: {
                while (true) {
                    try {
                        if ($complete.data[0] != 0) {
                            break;
                        }
                        try {
                            $ptr = 2;
                            continue $main;
                        } catch ($$e) {
                            $$je = $$e.$javaException;
                            if ($$je) {
                                break $bbb;
                            } else {
                                throw $$e;
                            }
                        }
                        continue;
                    } catch ($$e) {
                        $$je = $$e.$javaException;
                        if ($$je) {
                            break $bbb;
                        } else {
                            throw $$e;
                        }
                    }
                }
                try {
                    jl_Object_monitorExit($lock);
                    break $ba;
                } catch ($$e) {
                    $$je = $$e.$javaException;
                    if ($$je) {
                    } else {
                        throw $$e;
                    }
                }
            }
            jl_Object_monitorExit($lock);
            $rt_throw($blob);
        }
        return $out.data[0];
    case 2:
        $bbb: {
            $bcc: {
                $bdd: {
                    try {
                        jl_Object_wait2($lock);
                        if ($rt_suspending()) {
                            break $main;
                        }
                    } catch ($$e) {
                        $$je = $$e.$javaException;
                        if ($$je && $$je instanceof jl_InterruptedException) {
                            break $bdd;
                        } else if ($$je) {
                            break $bbb;
                        } else {
                            throw $$e;
                        }
                    }
                    try {
                        break $bcc;
                    } catch ($$e) {
                        $$je = $$e.$javaException;
                        if ($$je) {
                            break $bbb;
                        } else {
                            throw $$e;
                        }
                    }
                }
                try {
                    break $bcc;
                } catch ($$e) {
                    $$je = $$e.$javaException;
                    if ($$je) {
                        break $bbb;
                    } else {
                        throw $$e;
                    }
                }
            }
            try {
                $bee: {
                    try {
                        if ($complete.data[0] == 0) {
                            break $bee;
                        }
                        jl_Object_monitorExit($lock);
                    } catch ($$e) {
                        $$je = $$e.$javaException;
                        if ($$je) {
                            break $bbb;
                        } else {
                            throw $$e;
                        }
                    }
                    return $out.data[0];
                }
            } catch ($$e) {
                $$je = $$e.$javaException;
                if ($$je) {
                    break $bbb;
                } else {
                    throw $$e;
                }
            }
            try {
                continue $main;
            } catch ($$e) {
                $$je = $$e.$javaException;
                if ($$je && $$je instanceof jl_InterruptedException) {
                    break $bdd;     // <----------------- In this scope $bdd is not defined
                } else if ($$je) {
                } else {
                    throw $$e;
                }
            }
        }
        jl_Object_monitorExit($lock);
        $rt_throw($blob);
    default: $rt_invalidPointer();
    }}
    $rt_nativeThread().push($blob, $out, $complete, $lock, var$5, var$6, $ptr);
}
~~~~

Original Java Source:

~~~~
static String blobToDataURL(Blob blob){
        final String[] out = new String[1];
        final boolean[] complete = new boolean[1];
        final Object lock = new Object();
        ((WindowExt)Window.current()).BlobToBase64(blob, new DataURLCallback(){

            @Override
            public void callback(final JSString str) {
                new Thread(){
                    public void run(){
                        
                        out[0] = (str != null && !JS.isUndefined(str)) ? str.stringValue() : null;
                        complete[0] = true;
                        synchronized(lock){
                            lock.notifyAll();
                        }
                    }
                }.start();
                
            }
            
        });
        synchronized(lock) {
            while (!complete[0]) {
                try {
                    lock.wait();
                } catch (InterruptedException ex) {
                    //Log.e(ex);
                    
                }
            }
        }
        return out[0];
    }
~~~~

Project: https://github.com/shannah/teavm-regression

Safari Debugger output

![image](https://cloud.githubusercontent.com/assets/2677562/22219504/d99e771e-e15f-11e6-90db-a2f3297ccc55.png)

In Chrome, the same app doesn't give this particular error, but it fails at a different point.

![image](https://cloud.githubusercontent.com/assets/2677562/22221631/b8d4fd42-e168-11e6-9570-0b41258d16ed.png)

I suspect that it could be caused by the error that Safari reported, but Chrome just doesn't report that one.  Narrowing down where it goes wrong in Chrome:

The javascript code:

~~~~
function ccu_Form__init_2($this) {
    var var$1, $ptr, $tmp;
    $ptr = 0;
    if ($rt_resuming()) {
        var $thread = $rt_nativeThread();
        $ptr = $thread.pop();var$1 = $thread.pop();$this = $thread.pop();
    }
    $main: while (true) { switch ($ptr) {
    case 0:
        ccul_FlowLayout__init_(new ccul_FlowLayout);
        $ptr = 1;
    case 1:
        ccu_Form__init_4($this, var$1);   // <------  $var1 should contain the result of the line ccul_FlowLayout__init_(new ccul_FlowLayout); but is undefined
        if ($rt_suspending()) {
            break $main;
        }
        return;
    default: $rt_invalidPointer();
    }}
    $rt_nativeThread().push($this, var$1, $ptr);
}
~~~~

My guess is that `var$1` was supposed to be set by the `if ($rt_resuming())` block, but failed to for some reason.  Perhaps that failed due to the bad break reported in Safari?

The corresponding Java code to the above JS function is 

~~~~
public Form() {
        this(new FlowLayout());
    }
~~~~

**Comment by shannah** [comment]
I've been poring over TeaVM's code to try to find the source of this.  One other piece of useful info:

It seems to be invoking `ccul_FlowLayout__init_()` as if it were an async method.  But the actual method is rendered in a way that makes it look like a regular method:

~~~~
function ccul_FlowLayout__init_($this) {
    ccul_Layout__init_1($this);
    $this.$orientation = 1;
    $this.$valign1 = 0;
    $this.$dim2 = ccug_Dimension__init_(0, 0);
    return;
}
function ccul_FlowLayout__init_1($this, $orientation) {
    ccul_Layout__init_1($this);
    $this.$orientation = 1;
    $this.$valign1 = 0;
    $this.$dim2 = ccug_Dimension__init_(0, 0);
    $this.$orientation = $orientation;
    return;
}
~~~~

I placed some debugging code on line 292 of Javascript target to see if it deemed that method as an async method:

~~~~
        System.out.println("Async methods: "+asyncMethods);
        System.out.println("Async Family Methods: "+asyncFamilyMethods);
~~~~

That method was not included in the output -- i.e. TeaVM doesn't seem to think that it is async at that point.

**Comment by konsoletyper** [comment]
The problem was in node splitting algorithm that converts irreducible CFG to reducible CFG. Sometimes it failed to copy and map exception handlers properly. With my fix problem with breaking wrong block disappeared (I examined generated code of the method you mentioned and it looks ok). However, the whole example still does not run. Can you perform some investigation yourself?

**Comment by shannah** [comment]
Thanks.  Just testing it out now.

**Comment by shannah** [comment]
I may not be fully understanding how it's supposed to work, but here's what looks like a problem to me:

In the following method,  I've marked 2 points:

`ccul_FlowLayout__init_(new ccul_FlowLayout); `

The result of `new ccul_FlowLayout` somehow needs to be assigned to `var$1` before the line

`ccu_Form__init_4($this, var$1); `

~~~~
function ccu_Form__init_2($this) {
    var var$1, $ptr, $tmp;
    $ptr = 0;
    if ($rt_resuming()) {
        var $thread = $rt_nativeThread();
        $ptr = $thread.pop();var$1 = $thread.pop();$this = $thread.pop();
    }
    $main: while (true) { switch ($ptr) {
    case 0:
        ccul_FlowLayout__init_(new ccul_FlowLayout);  // <1>
        $ptr = 1;
    case 1:
        ccu_Form__init_4($this, var$1);  // <2>
        if ($rt_suspending()) {
            break $main;
        }
        return;
    default: $rt_invalidPointer();
    }}
    $rt_nativeThread().push($this, var$1, $ptr);
}
~~~~

Based on the structure here, it looks like TeaVM is expecting this to be set inside the `ccul_FlowLayout__init_()` method and passed up using `$rt_nativeThread().push()` so that it will be picked up inside the `$rt_resuming()` block.

But either the `ccul_FlowLayout__init_()` method nor the `ccul_FlowLayout` constructor do this.  I've pasted those methods below.

~~~~
function ccul_FlowLayout__init_($this) {
    ccul_Layout__init_1($this);
    $this.$orientation = 1;
    $this.$valign1 = 0;
    $this.$dim2 = ccug_Dimension__init_(0, 0);
    return;
}
~~~~

~~~~
function ccul_FlowLayout() {
    var a = this; ccul_Layout.call(a);
    a.$fillRows = false;
    a.$orientation = 0;
    a.$valign1 = 0;
    a.$vAlignByRow = false;
    a.$dim2 = null;
}
~~~~

It seems to me that either `ccl_FlowLayout_init()` needs to be rendered as an async method so that the `$this` will be passed up via the  `$rt_nativeThread`, or the invocation of it needs to explicitly return a return value e.g:

~~~
var$1 = new ccul_FlowLayout;
ccul_FlowLayout__init_(var$1);
~~~~

**Comment by konsoletyper** [comment]
Looks like I finally got rid of the issue.

**Comment by shannah** [comment]
Thanks.  Confirmed that it fixes the issue.

I was in the process of trying to track down the issue myself.  Judging by the diff, it would have taken me a while to find it.  My process is currently:

1. Add System.out.println() statements in various key places to (e.g inside the AsyncProgramSplitter) to print debugging information.
2. mvn install -DskipTests
3. Build my project and look at the output.

Repeat.

I'd like to become more effective at solving problems like this so that I can contribute more.  I know that some of the techniques you use, particularly for program splitting, are your own creation, so the only literature I can refer to is the source code itself.  But would you recommend any papers or literature that I should read to help better understand the program-splitting algorithm?

**Comment by konsoletyper** [comment]
Well, first of all you have to read [Dragon Book](https://en.wikipedia.org/wiki/Compilers:_Principles,_Techniques,_and_Tools). Second, you should find some papers on SSA represenatation (which is used internally in TeaVM). Third, you should learn "Under the hood" section in TeaVM's wiki. Also, you may ask me.

As for this particular bug. I suspected, that termporary variable that stores result of `new ccul_FlowLayout` was eliminated by AST optimizer. I went to `Decompiler.decompileAsyncCacheMiss`. You can see some `Optimizer` references on the bottom of the method. I put breakpoint just before this and examined `node` parts. All variables were in places. I was right, it is optimizer which does wrong things.

Then, I went to optimizer. I know exactly how it eliminates temporary variables and how it *does not* eliminate temporary variables if they cross part bounds. Frankly speaking, it's overcomplicated now, and I should make it simplier. So, we encounter a variable that is defined exactly once, used exactly once and therefore can be eliminated by optimizer if possible. `Optimizer.findEscapingLiveVars` is the method that prevents some temporary variables from elimination.

It's logic is as follows: calculate live-in set before the split instruction, and mark all variables from live-in set as "don't eliminate" (related topic: [liveness analysis](https://en.wikipedia.org/wiki/Live_variable_analysis)). The problem was in liveness analysis. It first call global liveness analysis which calculates live-in sets per basic block. Then it calculates live-out set of a block and starts to apply gen/kill information for each instruction, from the last to first, until it reaches split instruction. I changed recently my IR to represent instructions in a double-linked list instead of `ArrayList`, and had to change how split points represented (they were just integer indexes). Here is related change: [ae5e1e4](https://github.com/konsoletyper/teavm/commit/ae5e1e49622969b0ea736b9997227afa95243a94#diff-1b4b91fed9395d1df9f47cc6f8b8d1efR130). You can see, the previously algorithm included split point (used >= comparion) whereas current algorithm breaks as it reaches split point. Split point in your particular method was `invokespecial` to `Form.<init>` with parameters. It passes the variable to parameter, so generates it and therefore it should be included in `live-in` set. However, TeaVM did not visit this instruction, did not include variable in `live-in` set and let optimizer to eliminate it.

I believe, this can be done simplier: just calculate def/use counts of variable in the original program and in the part after splitting. If they differ, we can't eliminate variable.

**Comment by shannah** [comment]
Thanks for the pointers and explanation.  They are very helpful.  I'll buy the Dragon Book today and begin my studies :)
