### ISSUE TITLE
Creating an empty 2-dimensional array fails

### ISSUE THREAD

**Issue by rufenerc** [konsoletyper/teavm#239]
If I create an array like

```
int t[][] = new int[0][0];
```

the resulting t is 'undefined' in JS

To reproduce it, just create an int[][] like in my example and try to access the array like:

```
int t[][] = new int[0][0];
System.out.println("t length = " + t.length);
```

I use Version 0.4.3

**Comment by konsoletyper** [comment]
The reason was in 0 dimensions, I created fix. You can rebuild TeaVM yourself (clone and type `mvn clean install -DskipTests`) and then switch Maven dependency version version to `1.0.0-SNAPSHOT`.

**Comment by rufenerc** [comment]
Thx!
