### ISSUE TITLE
Strange WASM compile time errors with simple example

### ISSUE THREAD

**Issue by mirkosertic** [konsoletyper/teavm#256]
The following example code leads to strange "type stack at end of if false branch is 1, expected 0" errors at compile time in browser and even if wasm-compiler is used at command line:

```
package de.mirkosertic;

import org.teavm.interop.Import;
import org.teavm.jso.JSBody;
import org.teavm.runtime.GC;

public class Main {

    static class Test {
        int value;
    }

    public static void mark(Test test) {
        if (test == null || isMarked(test)) {
            return;
        }
    }

    public static boolean isMarked(Test test) {
        return test.value == 0;
    }

    public static void main(String[] args) {
        mark(new Test());
    }
}

```

**Comment by konsoletyper** [comment]
My commit fixes the issue. However, I could not get my examples working in Google Chrome, it reports:
```
Wasm compilation exceeds internal limits in this context for the provided arguments
```
which is unclear for me. The only description I could find is https://codereview.chromium.org/2699843003
Looks like a bug in Google Chrome? Everything works fine in latest FF nightly

**Comment by mirkosertic** [comment]
Added pull request  #257 to fix this issue
