### ISSUE TITLE
Add TouchEvent support

### ISSUE THREAD

**Issue by reportmill** [konsoletyper/teavm#285]
I would love to see support for TouchEvent! My TeaVM demos all appear static on tablets and phones. Alexey has suggested that I could add these myself, but I know very little about JavaScript and modifying the TeaVM project.

Can anyone look into this and/or describe the steps to add it? Particularly if there is a way to add external to TeaVM (for now - since I have a sizable TeaVM adapter for my Java code, I could get started that way).

**Comment by konsoletyper** [comment]
You have `Event` interface, right? You have several interfaces that extend this interface. Why don't you create something like:

```java
public interface TouchEvent extends Event {
    // ...
}
```

somewhere in your project?
