### ISSUE TITLE
ArrayList ensure capacity problem?

### ISSUE THREAD

**Issue by norzak** [konsoletyper/teavm#289]
https://github.com/konsoletyper/teavm/blob/master/classlib/src/main/java/org/teavm/classlib/java/util/TArrayList.java#L54

What if the minimum capacity needed is 3 times the the array length itself?

**Comment by norzak** [comment]
This one breaks us very badly. Are we gonna see 0.5.1 soon?

**Comment by konsoletyper** [comment]
Yes, I'll release 0.5.1 in 2-3 weeks
