### ISSUE TITLE
JSO WebSockets Performance

### ISSUE THREAD

**Issue by WolfieWerewolf** [konsoletyper/teavm#292]
Hi Alexey,
I'm back again already.  I have a performance related question this time if you don't mind.  I have a very simple abstract base class that exposes some methods from the Socket.IO Client Library.  I've written two implementations, JVM and TeaVM.  I set some flags, depending on where the app is running, to use the correct implementation.  The Java Implementation uses the Java version of the Socket.IO client library and the JSO implementation consumes the standard JavaScript library, nothing fancy, I just have it in a <script> tag in the index.html
I've run three tests timing the round-trip to call the server and receive the callback with data.  I loop over this test 10 times and so I will report approximate average times.
Straight JS in the browser, no TeaVM, yields about 97ms RT
Straight Java running on HotSpot on my Mac yields about 190ms
I realize these are two completely different libraries so I am not concerned about this discrepancy.
However my JSO implementation, which consumes the same library that the straight JS UT called is taking about 450 ms to complete the callback and return the data.
I'm just wondering if there's anything in particular that I should be doing so that I can get greatest benefit from JSO?  I'm using @JSBODY with static native void and returning the callback via an interface annotated with the @JSFunctor... like this:

![image](https://user-images.githubusercontent.com/10762757/27766249-bd96f668-5ea0-11e7-9086-003ee556cddd.png)

Thanks in advance for any advice you can offer.
Kind Regards
/W

**Comment by WolfieWerewolf** [comment]
actually I just noticed they aren't void... I'll check that.

**Comment by WolfieWerewolf** [comment]
and changing them to void didn't make any difference either :-)

**Comment by konsoletyper** [comment]
I don't know anything about methodology you use to measure time. Do you warm-up virtual machines? Running 10 times is too few, I think. You should run 10000 times. Please, share your benchmark if possible so that I could run it myself and check what causes performance loss. Also, you can investigate yourself, Google Chrome has built-in JS profiler (press F12, go to Performance tab).

**Comment by WolfieWerewolf** [comment]
Alexey, very good advice, thanks.  I'll do as you suggested and put together something to share.

**Comment by WolfieWerewolf** [comment]
Alexey.. sorry for the slow update on this.  Thank you for suggesting that I look at your tests.  They have answered all of my questions and a lot more.  I would encourage anyone to look there first as there is a wealth of information within.  Thank you again and great work mate... 
Kind Regards
/W
