### ISSUE TITLE
MetaProgramming passing args

### ISSUE THREAD

**Issue by WolfieWerewolf** [konsoletyper/teavm#293]
Hi Alexey... I'm learning your MetaProgramming / Reflection API and I have, what I hope, is a simple question.  The following code, including JUNit test works:

![image](https://user-images.githubusercontent.com/10762757/27959522-2ef19ae6-62fe-11e7-939b-2912388b162d.png)

![image](https://user-images.githubusercontent.com/10762757/27959547-44deecbe-62fe-11e7-9dfa-e5994446fbe3.png)

I would like to extract the value of: Value<String> methodName and use it in place of the string literal "getAge".
If I try to call methodName.get() it fails due to incorrect context; I understand why that happens, but I don't quite get how I can pass in args and use them?
Thanks for any advice you can offer.... I've been through your MetaprogrammingTest.java and ProxyTest.java but couldn't find a sample use case.
Kind Regards
/W

**Comment by konsoletyper** [comment]
Hello. First, you don't have to copy screen shots from IDEA, better use markdown, like this

```markdown
    ```java
    // some java code here
    ```
```

Second, the thing you want is a little sophisticated. You can use a trick. Here is code example that shows two approaches to achieve what you want:

```java
@CompileTime
public final class Client {
    public static void main(String[] args) {
        System.out.println("-- Simple -- ");
        System.out.println(className(nGetType(A.class, "foo")));
        System.out.println(className(nGetType(A.class, "bar")));
        System.out.println(className(nGetType(A.class, "zzz")));

        System.out.println("-- Map -- ");
        for (Map.Entry<String, Class<?>> entry : nGetTypeMap(A.class).entrySet()) {
            System.out.println(entry.getKey() + " = " + className(entry.getValue()));
        }
    }

    private static String className(Class<?> cls) {
        return cls != null ? cls.getSimpleName() : null;
    }

    @Meta
    private static native Class<?> nGetType(Class<?> cls, String methodName);

    private static void nGetType(ReflectClass<?> cls, Value<String> methodName) {
        Value<Class<?>> result = lazy(() -> null);
        for (ReflectMethod method : cls.getMethods()) {
            Value<Class<?>> previousResult = result;
            ReflectClass<?> returnValue = method.getReturnType();
            String currentMethodName = method.getName();
            result = lazy(() -> currentMethodName.equals(methodName.get())
                    ? returnValue.asJavaClass()
                    : previousResult.get());
        }

        Value<Class<?>> finalResult = result;
        exit(() -> finalResult.get());
    }

    @Meta
    private static native Map<String, Class<?>> nGetTypeMap(Class<?> cls);

    private static void nGetTypeMap(ReflectClass<?> cls) {
        Value<Map<String, Class<?>>> result = emit(() -> new HashMap<>());
        for (ReflectMethod method : cls.getMethods()) {
            ReflectClass<?> returnValue = method.getReturnType();
            String methodName = method.getName();
            emit(() -> result.get().put(methodName, returnValue.asJavaClass()));
        }
        exit(() -> result.get());
    }

    interface A {
        int foo();

        String bar();
    }
}
```

May I ask you for which purpose you are trying to use metaprogramming API?

**Comment by WolfieWerewolf** [comment]
Alexey,
First, you are correct, it is much more convenient to use Markdown; I will in future.  Second, you are exceptional!  I found the first example to be the easiest to understand so I've tested that and it works.  I will have many other use cases, however, so I appreciate you providing more than one approach.  
Regarding your question I would be more than happy to answer that in detail however I would prefer to do it in private.  Please feel free to email me on wolfiewerewolf@gmail.com and I will respond with more detail.
Again, I can't thank you enough for sharing TeaVM and also for your prompt and very professional support.... 
Kind Regards
/W

**Comment by WolfieWerewolf** [comment]
Hi Alexey,
After spending the weekend reading the code for the MetaProgramming plugin I'm re-opening this to ask for some advice.  Admittedly your code is complex; this is most likely one of the more complex areas in TeaVM.  I feel that the limitation of only being able to pass arguments the way you have designed this is too much to make this useful for me, however, I am confident that TeaVM is the right solution for my use case.  I know you don't like to "give clues" but if we are honest the documentation from a contributor point of view is pretty much non-existent.  I'll ask a specific question.  With the current Metaprogramming implementation is it possible to modify it so that at least one argument, other than the ReflectClass, can be passed without being transformed into Value<> x?  I have made some attempts however there are a lot of dependencies in here and I keep breaking stuff that I frankly don't understand.  Please appreciate that I am not a novice developer and that your project is one of the most complex I've ever worked with.
Kind Regards
/W

**Comment by konsoletyper** [comment]
> I feel that the limitation of only being able to pass arguments the way you have designed this is too much to make this useful for me

Please, describe what you are going to do and I'll help you, don't try to hack TeaVM, until you discuss it with me. I used Metaprogramming API in quite complex scenarios and thought a lot of its design. Anyway, doing things like "I'm quietly creating a large patch" IMO is a bad approach. The good approach is: discuss first.

> I know you don't like to "give clues"

I like to give clues, hoewever, there are two issues. First, I merely don't have much time. Second, I don't know what's unclear for users.

> but if we are honest the documentation from a contributor point of view is pretty much non-existent

If you want to make documentation better, the best thing you can do is ask me about things which are unclear to you and update documentation with things you learned from me. A slightly worse (but still good approach) is to create an issue here that requests to update documentation. Not like "please, update documentation, it's unclear", but "the X thing is not explained clear enought, please clarify".

> I'll ask a specific question. With the current Metaprogramming implementation is it possible to modify it so that at least one argument, other than the ReflectClass, can be passed without being transformed into Value<> x?

The answer is short: no, generally speaking, it's impossible (but it's possible in few corner-cases). So, the next thing would be: please, describe what you are doing. Instead of inventing solutions that aren't supported in TeaVM (and trying to patch TeaVM to support them) you should name your goal. So that I can hint you with another solution.

> Please appreciate that I am not a novice developer and that your project is one of the most complex I've ever worked with

If you want to understant code, you can ask me. Without understanding the whole picture you'll be confused in details. Do you know what SSA form is? Did you read how [TeaVM's pipeline](https://github.com/konsoletyper/teavm/wiki/Pipeline) organized?

**Comment by WolfieWerewolf** [comment]
Hi Alexey,
Thanks for the prompt response.  
I have read every piece of documentation, including all of the documents that you have referenced, many times.  I've even ported Doppio from TS to JS by hand to better understand the JVM and read the source for various JVM implementations, and studied the JDK and Back2Brwsr and Dragome and GWT...
I'm sure you can appreciate that this is a very specialized area and that byte code manipulation and Java to JS trans-compilation is not in the realm of your average developer.  I have a substantial amount of Typed Language and JavaScript experience so I feel well prepared to deal with the nuances of using Java in a browser.. for example there are cases where callbacks via anonymous functions / methods are necessary to deal with Async issues that would not be necessary when running on the JVM.  I get all that... I am very impressed with JSO which handles every case I have ever attempted flawlessly!  Overlays are king!

I also appreciate that your time is limited, I should not have said that "you don't like to give clues"... it's just that, and I sometimes suffer from this myself, your comments on here are sometimes interpreted by others as being a bit terse... this is not a criticism from my perspective, I am just happy to get your help, but I have seen others complain in various forums and I thought you should know.

From a high level what I am attempting to port a rather large Java library to TeaVM which uses a lot of reflection.  I am not able to go into detail here due to contractual restrictions with my client which is why I said I would tell you more in private.  

The previous use case you helped me with is similar to the current one I am struggling with but not exactly the same and I am trying to avoid asking you for help with every single case when the answer would be to, somehow, be able to pass an argument into the native method and consume it outside of the lambda context(s).

I attempted to write a new Annotation that held the value however Metaprogramming is limited to a single ReflectClass argument per method and so that is not practical either.

Reflection, at the best of times, can be daunting... I'm comfortable with it but Metapogramming, as it stands, is difficult to use as a drop in replacement.

Also I would be more than happy to contribute to documentation however I feel I have not sufficiently understood all of this yet to be able to contribute;  perhaps these threads will be helpful to someone else.

The previous example:
```java
    ReflectMethod method = cls.getMethod("get");
    ```
is a perfect starting point.  I really need to be able to replace "get" with some arbitrary value without iterating and depending on the ability to consume the resulting Value<> in the exit(()-> Also have you seen the JS generated by the previous example nGetType?  It was the single largest nested if/then I have ever seen.....
Again none of this is criticism... I've never seen anything as cool or awesome as TeaVM before.. you are a legend.  I'm just trying to catch up :-)
