### ISSUE TITLE
Boolean.getBoolean() maybe System.getProperty broken in trunk

### ISSUE THREAD

**Issue by tulach** [konsoletyper/teavm#306]
Hello,
I'm working with current trunk but Boolean.getBoolean() fails with JS error Uncaught TypeError:  Cannot read property '$hashCode' of undefined.

Working fine in release 0.5.1.

Jiri Tulach

**Comment by konsoletyper** [comment]
Can you provide an example that reproduces the issue?

**Comment by tulach** [comment]
Ok, I'll try to prepare an example.

The actual code which fails looks like:
        if(Boolean.getBoolean("controls4j.dummytech")) DummyTechnology = true;

And property "controls4j.dummytech" doesn't exist. 

The generated JavaScript error is:
teavm.js:12941 Uncaught TypeError: Cannot read property '$hashCode' of undefined
    at jl_String_hashCode (teavm.js:12941)
    at ju_Hashtable_get (teavm.js:13275)
    at ju_Properties_getProperty (teavm.js:13422)
    at jl_System_getProperty (teavm.js:19045)
    at jl_Boolean_getBoolean (teavm.js:8753)

The undefined value is passed to jl_String_hashCode which fails because it expects the object.

**Comment by konsoletyper** [comment]
Please, try to build your project against latest master

**Comment by tulach** [comment]
It works! Great. Thank you.
