### ISSUE TITLE
Getting "is claimed to be synchronous, but it is has invocations of asynchronous methods" for code with no 'synchronized'

### ISSUE THREAD

**Issue by shooshx** [konsoletyper/teavm#320]
I'm getting this error:

    il.co.codeguru.corewars8086.gui.widgets.JButton$1.handleEvent(Lorg/teavm/jso/dom/events/Event;)V is claimed to be synchronous, but it is has invocations of asynchronous methods:

for an invocation that looks like this:

        element.addEventListener("click", new EventListener<Event>() {
            @Override
            public void handleEvent(Event evt) {
                m_listener.actionPerformed(new ActionEvent(JButton.this));

            }
        });

none of the functions involved are synchronized and I even removed all traces of synchronized methods from anywhere in my code.  
What's going on? what causes this error?

**Comment by konsoletyper** [comment]
Do you receive full trace to the asynchronous method? What actionPrformed looks like? What about ActionEvent constructor?

As a workaround you can run even handler in a separate thread.

**Comment by konsoletyper** [comment]
This message has nothing common with Java `synchronized` keyword. You are calling some asynchronous code from event handler, which is prohibited. It's a TeaVM-specific thing.

**Comment by shooshx** [comment]
> You are calling some asynchronous code from native event handler, which is prohibited. 

Do you mind explaining this in a bit more detail? How is asynchronous code created in TeaVM?

The stack trace led me to isolate this problem to one handler that calls 'dispose()' on some class. Once I removed this (unnecessary) call, the error went away. I still don't know why this happened though.

**Comment by konsoletyper** [comment]
Here's the documentation: http://teavm.org/docs/runtime/coroutines.html
