### ISSUE TITLE
NPE in ReflectClassImpl.getFields()

### ISSUE THREAD

**Issue by sheepdreamofandroids** [konsoletyper/teavm#334]
Wow! I'm really impressed by this project! I love the simplicity of the programming model and the speed and efficiency of the compiler.
While experimenting with the metaprogramming api (as a GWT refugee I'm trying to recreate serialization...) I ran into the aforementioned problem.
It happens on line 340 ( the middle one in below fragment) where classReader is null. I see you take great care of that in other methods but not here:

```
            fieldsCache = context.getClassSource()
                    .getAncestors(classReader.getName())
                    .flatMap(cls -> cls.getFields().stream().filter(fld -> fld.getLevel() == AccessLevel.PUBLIC))

```
I found that it is easily possible to debug the compiler by debugging maven. Would debugging be possible through the plugin?

Cheers, Guus

**Comment by konsoletyper** [comment]
> Would debugging be possible through the plugin?

You mean debugging IDEA plugin? Ctrl+Shift+A -> Debug build process. Then, when you press 'build' button, IDEA starts build process in debug mode and shows remote port. You can create remote debug launch configuration with corresponding port to start debugging. Additionally, you can press Ctrl+Shift+A -> Registry... and set `compiler.process.debug.port` value to, say, 5005.

Personally, I debug CLI process. See `teavm-cli` module, `TeaVMRunner` class.

**Comment by konsoletyper** [comment]
You don't need to recreate serialization and RPC. There are [JSON](http://teavm.org/docs/flavour/json.html) and [REST](http://teavm.org/docs/flavour/rest-client.html) support in TeaVM.

**Comment by sheepdreamofandroids** [comment]
I didn't know about 'Debug build process'. Nifty! But I can see how debugging teavm-cli is even handier. I'll try that.

I know about JSON but I'm not a fan. It's too limited and undefined to my taste (no shared structure, no difference between lists/sets, no polymorphism). On top of that it is just inefficient. Most of that can be worked around but why bother?

Anyway, what I really want is to synchronize structures between client and server, preferably using websockets so REST is really not a concern.

**Comment by konsoletyper** [comment]
> no shared structure

What do you mean?

> no difference between lists/sets

There's no need in it. To *transfer* data, you need only transfer items. If these items are stores in either `Set<T>` or `List<T>` in Java, they'll be just put there.

> no polymorphism

There *is* polymorhism, see [corresponding test](https://github.com/konsoletyper/teavm-flavour/blob/master/json/src/test/java/org/teavm/flavour/json/test/SerializerTest.java#L240) and [Jackson documentation](https://fasterxml.github.io/jackson-annotations/javadoc/2.4/com/fasterxml/jackson/annotation/JsonTypeInfo.html)

**Comment by sheepdreamofandroids** [comment]
With "no shared structure" I mean that JSON cannot refer to a previously written object. Also, I know that _Jackson_ supports polymorphism, but _JSON_ doesn't.

Anyway, it's not that JSON wouldn't work it's just that I have a bunch of code using serialization that also runs outside of TeaVM that I want to keep as separate as possible. Regarding the last point I have some ideas that I will put in a separate issue.
