### ISSUE TITLE
When will the official version be released

### ISSUE THREAD

**Issue by mylovetop** [konsoletyper/teavm#346]
When will the official version be released,  thank you!

**Comment by konsoletyper** [comment]
What do you men by "official version"? Why do you need it? What's wrong with binaries published to bintray?

**Comment by mylovetop** [comment]
i meaning when release 1.0,  Can't wait to write a web page use Java， I'm very glad to

**Comment by mylovetop** [comment]
yes  stable release,  when release

**Comment by konsoletyper** [comment]
What prevents you from using current version of TeaVM to write a web application on Java? There's no answer to the question 'when'.

**Comment by mylovetop** [comment]
oh, thanks!  i now use vue.js  ,  i have no use teavm,  i try to ,  how to start teavm?  less data

**Comment by konsoletyper** [comment]
http://teavm.org/docs/intro/getting-started.html
