### ISSUE TITLE
Class identification, runtime?

### ISSUE THREAD

**Issue by claeslundahl** [konsoletyper/teavm#347]
Hi Konsoletyper!

Thanx for all the good work you have put into this project.

I have a question concerning identifying objects class during execution. 

I am trying to do something like this:

```
import java.util.ArrayList;
import java.util.List;

public class WhatTypeIsIt {
    
    public static void main(String[] args) {
        List stuff = new ArrayList();
        stuff.add(new A());
        stuff.add(new B());

        for (Object o : stuff) {
            if (o instanceof A) {
                ((A) o).foo();
                continue;
            }
            if (o instanceof B) {
                ((B) o).baa();
                continue;
            }
            throw new RuntimeException("It should have been A or B!");
        }
    }

    public static class A {
        public void foo() {
            System.out.println("A.foo();");
        }
    }

    public static class B {
        public void baa() {
            System.out.println("B.baa();");
        }
    }
    
}
```

And it does not work. Have tried to identify the class with variations of `o.getClass().getName()` and so on too. But trying to get the class information like that causes an error inside TClass.

Du you know a way to get this to work?

Kind regards 

/C

**Comment by konsoletyper** [comment]
What kind of error do you get? I could not reproduce the error. Instead, I get following output:

```
A.foo();
B.baa();
```

Can you provide a self-contained example, including build confuguration?

**Comment by claeslundahl** [comment]
Hi 

I think my problem has to do with my specific environment.

Now I can not even build a newly created project (from your maven archetype). Getting a different problem
[build-fail.txt](https://github.com/konsoletyper/teavm/files/2132012/build-fail.txt)

I will close this 'issue' this week if can not repeat it due to my environment problems. 

Sorry for vasting your time.

/C

**Comment by konsoletyper** [comment]
From your log I see that you use TeaVM version 0.5.1. I strongly suggest you to use latest version, i.e. 0.6.0-dev-529
