### ISSUE TITLE
Can support openGL?

### ISSUE THREAD

**Issue by rayy-li** [konsoletyper/teavm#349]
I am a designer and always using Processing(processing.org)(built in Java and OpenGL) to create project of creative coding. If the project can be used TeaVM to translate from jre to WebAssembly, That's Amazing!

So, can The TeaVM support OpenGL or translation OpenGL to WebGL? or have some methods to support? Thanks!

**Comment by konsoletyper** [comment]
WebGL is supported, what's wrong with it? What do you mean by "OpenGL"? What particular API?
