### ISSUE TITLE
String.format can not be transpiled

### ISSUE THREAD

**Issue by nowachri-de** [konsoletyper/teavm#352]
Hello teavm team,

it seems that teavm has a problem transpiling the String.format method. Could you please check:

package hall.collin.christopher.stl4j.build;

public class TestApp2 {

    public void test(){
        String name = "MyName";
        String pattern = "abc";
        String.format("Function name %s is invalid, it should be an identifier (regular expression: %s)", name, pattern);
    }

}

When transpiling this code I get the following error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.379 s
[INFO] Finished at: 2018-08-20T14:08:13+02:00
[INFO] Final Memory: 26M/414M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.teavm:teavm-maven-plugin-nowachri:0.5.0-SNAPSHOT:compile (web-client) on project teavm-samples-hello: Unexpected error occured: Error rendering class hall.collin.christopher.stl4j.build.TestApp2. See a cause for details: Can't provide name for method as it was not found: java.lang.String.format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String; -> [Help 1]

Thank you and kind regards
Christian

**Comment by konsoletyper** [comment]
You can use 0.6.0-dev version from bintray, it supports `String.format` partially, see [documentation](https://github.com/konsoletyper/teavm#preview-builds). Also, I strongly suggest to avoid `String.format`.

**Comment by nowachri-de** [comment]
Thank you for the quick response. Will follow your suggestion.

kind regards
Christian
