### ISSUE TITLE
Compilation Error: EmitException: Can't convert J to V

### ISSUE THREAD

**Issue by Anuken** [konsoletyper/teavm#354]
I am attempting to get my libGDX game working with TeaVM. 

- I've forked your `libgdx-teavm` repository, added most missing features and upgraded to the latest version of libGDX.
- I've forked the `teavm-gradle-plugin` and updated it to the same version of TeaVM as `libgdx-teavm` (0.5.1)

While the plugin and backend seem to work properly with a small test project (e.g. drawing moving squares), I get vague cast errors when trying to compile my game. [Here is the error I get when I attempt to do so.](https://hastebin.com/doxucuwise.nginx)

What is causing this issue? It seems like the stack trace is missing the in-source location of where the compilation goes wrong. Would there happen to be an option to display more detailed error info?

*Relevant source code:*
[teavm-libgdx fork](https://github.com/Anuken/teavm-libgdx)
[teavm-gradle-plugin fork](https://github.com/Anuken/teavm-gradle-plugin)
[game main class](https://github.com/Anuken/Mindustry/blob/teavm/html/src/io/anuke/mindustry/teavm/TeaVMLauncher.java)

**Comment by konsoletyper** [comment]
First of all, the link to the error you provided is not valid.

Second, did you try to use latest dev version?

Third, please, provide self-contained example of your game.

**Comment by Anuken** [comment]
Looks like using the dev version fixed my compilation errors.

(Side note: there isn't really a self-contained example of my game, since the issue occured only when I tried to compile the whole 400+ class codebase.)
