### ISSUE TITLE
Compilation fails with ConcurrentModificationException under Ubuntu 18.04.1

### ISSUE THREAD

**Issue by boyanio** [konsoletyper/teavm#356]
Hello. I am [playing around](https://github.com/boyanio/wasm-wheel/tree/master/src/langs/java) with compiling Java to WebAssembly. I am using Maven to compile the simple project and it works fine on Windows 10. However, when I try to compile the same project on Ubuntu 18.04.1, I get _ConcurrentModificationException_ (see screenshots). Do you have any idea what the problem could be?

![teavm-0](https://user-images.githubusercontent.com/980463/44840245-f1d5b880-ac40-11e8-96f4-7becc13ac112.JPG)
![teavm-1](https://user-images.githubusercontent.com/980463/44840252-f4d0a900-ac40-11e8-984c-0bcb7ecd367a.JPG)

**Comment by konsoletyper** [comment]
Hello. Looks like this bug is reproduced on Java 9+. Perhaps you have Java 8 on your Windows 10 machine.

**Comment by konsoletyper** [comment]
Please, provide a self-contained example so that I could reproduce this bug myself

**Comment by konsoletyper** [comment]
Also, use the latest version of TeaVM available on bintray (0.6.0-dev-559 for now).

**Comment by boyanio** [comment]
Thanks for the quick answer. I will do some tests as you suggest and will get back

**Comment by boyanio** [comment]
You were right, I have Java 1.8.0_181 on my Windows machine (where it works fine) and Java 10.0.2 (OpenJDK). You can find the example in the link above. It is installed with `mvn clean install`.

**Comment by boyanio** [comment]
And I can confirm that it builds fine with TeaVM 0.6.0-dev-559
