### ISSUE TITLE
Increase WASM maximum memory size?

### ISSUE THREAD

**Issue by Restless88** [konsoletyper/teavm#357]
Hi, sorry if this a stupid question, is it possible to increase the WASM memory size?

I've spent the last few hours attempting to reverse engineer how the WASM memory size is allocated and if there is any parameters to increase it. And whilst I feel like I've learnt a lot about how it's all working, I've yet to actually find a way to increase the available space. 

From what I can tell, the only memory object available is the one produced by Teavm as I can't seem to import one from JS. Is there a way to increase the maximum size of pages?

Please let me know if you need any more info and thanks in advance!

**Comment by konsoletyper** [comment]
There's option that controls WebAssembly and C heap size inside code, but this option is not assigned somewhere within Maven plugin, it's only set from CLI tool (see [TeaVMRunner.java](https://github.com/konsoletyper/teavm/blob/55e090551866caf6b33966e7fcc9659cd89e683f/tools/cli/src/main/java/org/teavm/cli/TeaVMRunner.java#L341)). You can ask me to include this option into Maven plugin or contribute it yourself (it must be easy). The relevant file is [TeaVMCompileMojo.java](https://github.com/konsoletyper/teavm/blob/55e090551866caf6b33966e7fcc9659cd89e683f/tools/maven/plugin/src/main/java/org/teavm/maven/TeaVMCompileMojo.java#L81). Also please note that currently Wasm and C backend are limited to constant heap size, then can't allocate additional memory.

As for Wasm memories: by the time I implemented Wasm target, the specification did not allow to have more than one memory object (but committee planned to enable this feature). I haven't been wathing for spec updates for a while. Have they enabled multiple memory objects?
