### ISSUE TITLE
runtime.js isn't minified

### ISSUE THREAD

**Issue by ScraM-Team** [konsoletyper/teavm#360]
When using the 'MERGED' option with minified 'true', the generated 'classes.js' has all of the transpiled classes minified nicely.  However, the merged-in runtime.js file isn't minified, resulting in a warning from Lighthouse.  

Is it possible to enable minification on runtime.js, especially when merged, or would that cause problems for the transpiled code that depends on it?

**Comment by konsoletyper** [comment]
While `classes.js` is generated by TeaVM, `runtime.js` is written by hands. The way, used by TeaVM generator, does not fit to minify `runtime.js`, so either I have to write minifier for that purpose, or reuse existing one. This requires some amount of work and isn't a low-hanging fruit. On the other hand, I thought of complete elimination of `runtime.js` as a hand-written code and rewriting whole runtime in Java.

**Comment by konsoletyper** [comment]
I believe that does not affect license.

**Comment by ScraM-Team** [comment]
@konsoletyper , thanks for thinking about this.  If runtime.js could be minified in the future that would be great.

About the licensing issue, while technically the merged file has the header, I think the intent is clear that the license applies to the runtime.js part, not the minified classes.js part.  @konsoletyper , could the license be clarified to say this?

**Comment by ScraM-Team** [comment]
Thank you!  I will try this out soon...

**Comment by norzak** [comment]
What is the final resolution in this licensing mixup?

**Comment by konsoletyper** [comment]
@norzak what version are you using? Minification of runtime.js was implemented long time ago.

**Comment by norzak** [comment]
I had 0.6, recently switched to the 0.7. I believe I was outdated on that front. Thanks for heads up.
