### ISSUE TITLE
TeaVMRunner hang

### ISSUE THREAD

**Issue by reportmill** [konsoletyper/teavm#369]
I regularly use TeaVM version 0.5.0-dev-328 to compile my SnapKit demos, but when I try the latest version (by cloning the project and gathering the jars), TeaVMRunner hangs. You can download and build the SnapKit library like this:

    prompt> cd /tmp; git clone http://github.com/reportmill/SnapKit.git
    prompt> cd SnapKit; mvn install

Then you can try a TeaVM compile against a little built-in demo:

    prompt> java -cp /<TeaVM-jar-dir>/*:/tmp/SnapKit/target/classes/ org.teavm.cli.TeaVMRunner snap.viewx.TextPane
    INFO: Running TeaVM
    Analyzing classes...

For me (on MacOS) this never returns - but works fine for the old version. Note, this sample doesn't include my SnapTea adapter library, but that shouldn't stop it from compiling. You can also delete the src/snap/swing package and the only reference (via reflection) in the method snap.view.ViewEnv.setDefaultEnv (ViewEnv.java:47). But that doesn't matter either.

**Comment by konsoletyper** [comment]
Did you try to increase maxium heap size available for JVM?

**Comment by konsoletyper** [comment]
Could not reproduce. I need more info. What is the Java version? What is the TeaVM version? What is `TeaVM-jar-dir`?

**Comment by reportmill** [comment]
I just tried with -Xmx1500m, but no change.

I built a directory (/tmp/tvm-new) with all the teavm jars with this:

  prompt> cd /tmp/teavm/tools/cli
  prompt> man install
  prompt> mvn dependency:copy-dependencies -DoutputDirectory=/tmp/tvm-new
  prompt> cp target/teavm-cli-0.6.0-SNAPSHOT.jar /tmp/tvm-new/teavm-cli.jar

I'm not sure if that's sufficient to get all the TeaVMRunner dependencies, but I was thinking it would throw a ClassNotFound error if it wasn't so. I'm also a bit of a maven idiot, so please forgive my ignorant approach to this.

**Comment by reportmill** [comment]
I just did a pull from your latest commit and that seems to have fixed the hang. Although, now I am getting a bunch of "claimed to be synchronous, but it is has invocations of asynchronous methods" errors. I need to read the docs on this to figure out what is causing it - although I don't see all of these errors with version 0.5.0-dev-328.

**Comment by konsoletyper** [comment]
Strange. The last commit did not fix anything related to compilation itself. It just fixed lack of diagnostic messages from CLI. Right, you did not see any error messages before since CLI runner did not report them to the console (but compiler generated them). The article that explains the error message you get is here: http://teavm.org/docs/runtime/coroutines.html
