### ISSUE TITLE
String.intern() issue

### ISSUE THREAD

**Issue by reportmill** [konsoletyper/teavm#370]
I have code that compares strings (using ==) that were scraped from larger strings via substring().intern() against string literals. In version .5 of TeaVM and the JVM this works fine, but I'm having a problem in version .6. I can reproduce the problem with this:

    String s1 = "abc";
    String s2 = "xabc".substring(1).intern();
    System.out.println("Equals()? " + s1.equals(s2) + ", ==? " + (s1==s2));

This returns false for the direct compare for me.

**Comment by reportmill** [comment]
This issue has been fixed for me for most cases, but I suddenly hit it again for one particular string, "Object". So the above code works, but this code still fails for me:

`
    String s1 = "Object";
    String s2 = "xObject".substring(1).intern();
    System.out.println("Equals()? " + s1.equals(s2) + ", ==? " + (s1==s2));
`

Prints this to the console: Equals()? true, ==? false

**Comment by reportmill** [comment]
I should have mentioned that this happened in the latest clone (from last thursday). I don't know if I should open a new issue for this.

**Comment by konsoletyper** [comment]
Please, open a new issue and attach the minimum project that reproduces it.
