### ISSUE TITLE
Bug when serializing object with null Date field

### ISSUE THREAD

**Issue by vic-cw** [konsoletyper/teavm#387]
I don't know whether there is an easy workaround, but I have been fighting with this and it seems like a bug.

If I try to send an AJAX request through `RESTClient`, passing as body an object that has a `Date` field which is null, then an error is thrown.

The stack trace is:

> runtime.js:529 Uncaught TypeError: Cannot read property '$value2' of null
>     at ju_Date_getTime (TDate.java:151)
>     at otfjs_JsonSerializer$proxy0_serialize (JsonSerializerEmitter.java:472)
>     at otfjs_JsonSerializer$proxy0.main [as $serialize1] (TCollections.java:547)
>     at otfj_JSON_serialize1 (JSON.java:52)
>     at otfj_JSON_serialize (JSON.java:41)

### To reproduce

Create a data structure like so:

    public class DateWrapper { public Date date; public DateWrapper(Date date) { this.date = date; } }

Then call `JSON.serialize(new DateWrapper(null))`.

### More details

Conversely, `JSON.serialize((Date) null);` works fine

**Comment by ScraM-Team** [comment]
Two things:
* JSON library is part of Flavour.  The maintainer likes those issues to be filed in the Flavour issue repository: https://github.com/konsoletyper/teavm-flavour/issues
* I recommend converting Date to a long and passing that via JSON.  Primitives, enums, and data classes containing primitives and enums seem best supported.

When you limit the types you are passing, the REST/JSON support works like magic.  Much easier than fussing with the underlying APIs, especially if you already have (or can build) a JAX-RS/JSON service.

**Comment by vic-cw** [comment]
@ScraM-Team Thanks again for the swift reply!

Sorry I indeed filed this issue in the wrong repo, I didn't mean to. Would you like me to close this one and reopen it in the Flavour repo?

Regarding the workarounds you mention, of course they would work, and that is a short term solution.

However, if we want TeaVM to become mainstream, and I really hope it does, this kind of thing should be handled. If you want, I can explain you why it is much better for me to pass a Date object rather than a long, but in any case, I find that adding support for widely used classes such as `Date`, `Optional`, and `LocalDate` will be necessary to convince people to switch to something like TeaVM.

Again I am happy to try and submit a pull request for that as soon as I can.

**Comment by ScraM-Team** [comment]
I think moving this to the Flavour repo is best.  It will help out @konsoletyper .

I agree with everything you said about making Date and other common types work "out of the box".  The easier it is for new folks the faster it will grow.

I have used many of the Flavour and TeaVM features over the the past 6-9 months, so feel free to ask for help if you run into issues with anything else, from components to validation to routing to geolocation to Canvas.

**Comment by konsoletyper** [comment]
I fixed the issue, however this issue should have been created in another repository as pointed out by @ScraM-Team

**Comment by vic-cw** [comment]
@ScraM-Team thanks a lot for proposing your help! That's really nice of you!

@konsoletyper awesome, great!

Sorry again for posting in the wrong repo, it was inadvertent.
