### ISSUE TITLE
Kotlin to javascript

### ISSUE THREAD

**Issue by j209** [konsoletyper/teavm#389]
Hi
What is teavm's superior to Kotlin, given that kotlin converts Java code into javascript?[Kotlin to javascript](https://kotlinlang.org/docs/tutorials/javascript/kotlin-to-javascript/kotlin-to-javascript.html)

**Comment by konsoletyper** [comment]
The problem with Kotlin/JS is that it does not allow to include Java libraries and mix Java and Kotlin code, while TeaVM supports this feature.
