### ISSUE TITLE
Idea Plugin build error when Flavour is used

### ISSUE THREAD

**Issue by mfdewit** [konsoletyper/teavm#390]
When running the Development Server from the Idea plugin, the build fails:
```
INFO: Build complete with errors
INFO: Compilation took 1605 ms
ERROR: Can't create template for [Ljava.lang.Object;: no BindTemplate annotation supplied
```

Building works from maven and IntelliJ (Ctrl-F9).
Is Flavour development supported with Idea Plugin?

**Comment by ScraM-Team** [comment]
I'm afraid I don't use the plugin so I can't give direct help.  Hopefully @konsoletyper can weigh in.

Does the plugin require you to specify dependencies or does it read from your POM?

Which version of TeaVM, Flavour, and the plugin are you using?

**Comment by mfdewit** [comment]
The plugin can be configured to use the classpath of a module. So I'm guessing that it will include all maven dependencies. Looking at the plugin itself, it seems only TeaVM is packaged into the lib folder. So I'm wondering if Flavour is actually supported.

Just out of curiosity, what is your workflow then? The plugin provides a better workflow then running a maven build after each change.

Version wise, I'm using these versions (for the plugin as well):
```
<flavour.version>0.2.0-dev-52</flavour.version>
<teavm.version>0.6.0-dev-690</teavm.version>
```

**Comment by konsoletyper** [comment]
Flavour is not compatible with development server yet.

**Comment by konsoletyper** [comment]
The correct workflow with Flavour is to use it as described [here](http://teavm.org/docs/tooling/idea.html). However, latest versions of IDEA plugin do not enable this way by default. You should find TeaVM facet in module configuration and enable TeaVM build.

**Comment by mfdewit** [comment]
Well, it seems I'm having trouble with the described workflow as well now. 
I've enabled the facet, and by default 'Skip TeaVM compilation' is set to Skip. Then the build is successful (Java compilation that is), but no JS is generated. Setting it to 'Don't Skip', will cause a NPE:

`Error:TeaVM: Error: java.lang.NullPointerException
java.lang.NullPointerException
	at org.teavm.backend.javascript.codegen.SourceWriter.append(SourceWriter.java:69)
	at org.teavm.backend.javascript.codegen.SourceWriter.append(SourceWriter.java:46)`

Having said this, I understand this software is still a work in progress and expecting everything to work is just not realistic. But I really, really like TeaVM and hope that it will become more mature.

Is it hard to make the development server support Flavour? And can I help in this regard?
I would definitively be willing to invest time to contribute to this.

**Comment by mfdewit** [comment]
@alexey-andreev I'm exploring the possibility of adding Flavour support to the plugin. 
Is there any fundamental reason this is not yet working/possible? 
Looking at CodeServlet (which is used by the plugin) and TeaVMTool (used by Maven) they both use TeaVM class to run the actual build. Any suggestions?

**Comment by konsoletyper** [comment]
The reason for this problem is another dependency analyzer (fast in dev server vs. precise in Maven)

**Comment by konsoletyper** [comment]
Is the issue still there in the latest Flavour built from master with the preview version of TeaVM IDEA plugin (instructions how to install it can be found [here](https://github.com/konsoletyper/teavm#preview-builds))?
