### ISSUE TITLE
Arrays cannot be synchronized on

### ISSUE THREAD

**Issue by SquidDev** [konsoletyper/teavm#393]
Under TeaVM 0.6.0-dev-751, the following code will throw a `"$o.$monitor is undefined"` error within `jl_Object_monitorEnterSync`:

```java
int[] x = new int[0];
synchronized(x) { }
```

I believe this was caused by fe68bf700b21ce8cb2667296fbb35d25cf94831e - as arrays are no longer using `jl_Object`'s constructor, they do not initialize `$monitor` to `null`, and so the `if ($o.$monitor.$owner === null)` check fails, meaning the monitor is never actually initialised.

**Comment by ScraM-Team** [comment]
Thanks for making this detailed report!

In case you need a workaround, I would guess you can make a wrapper class for the array and synchronize on instances of the wrapper.

Let us know what you are doing with TeaVM sometime.

**Comment by SquidDev** [comment]
So I had a look into fixing this and ran into a little bit of difficulty. While setting `$monitor = null` technically fixes this, it breaks when minification is enabled - the field in the generated classes is remapped, but not in the runtime.

This makes perfect sense, but also complicates things. Just wondering if anyone can think of an alternative fix. I've just disabled minification as a bodge for the time being

> Let us know what you are doing with TeaVM sometime.

@ScraM-Team I'm afraid [it's nothing especially serious](https://github.com/SquidDev-CC/copy-cat/). Effectively trying to emulate a fantasy console running on the web.

**Comment by ScraM-Team** [comment]
Hopefully Alexey can comment on your fix ideas.

Thanks for telling us about your project.  When you are ready for some testers post in the forum.

**Comment by SquidDev** [comment]
Amazing, thank you very much!

**Comment by konsoletyper** [comment]
BTW, I just published 0.6.0-dev-764 version, which includes fix for this issue. This means you can build your project against this version without any patches.
