### ISSUE TITLE
TeaVM forum broken intermittently

### ISSUE THREAD

**Issue by PokingUrsa** [konsoletyper/teavm#404]
The TeaVM forum on Google Groups isn't working.  It says:

"This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.
RELOAD"

This has been happening for a month or so intermittently for me, maybe longer.

**Comment by Pneumaticat** [comment]
Can reproduce. I have actually never been able to access the forum on my end.

**Comment by reportmill** [comment]
Wow - this is a bummer and very surprising. Is this the link you are using?

https://groups.google.com/forum/#!forum/teavm

I wonder if this is a problem of the group or access from particular places/countries?

**Comment by PokingUrsa** [comment]
Ever since I posted it works fine every time!  @Pneumaticat , can you try the forums again?

**Comment by Pneumaticat** [comment]
Yeah, works for me now. Not sure what changed.

**Comment by PokingUrsa** [comment]
Still working fine 100% of the time.  @konsoletyper , you can close this as far as I'm concerned.
