### ISSUE TITLE
Dead code elemination - how to improve it..?

### ISSUE THREAD

**Issue by wordlessly** [konsoletyper/teavm#405]
Hi,

I would like to get as small as possible code. For example I have a main-method where execution starts but only a small part of my classes is visited. Some classes are very big and often only a small fraction of that class is used (single static final fields or single methods). Is the "dead code elemination" efficient enough to even remove unused fields and methods from classes? Or is it just doing a simple "import analysis" and then excludes classes never use?

**Comment by konsoletyper** [comment]
Dead code elimination works automatically. If compiler includes some code it has a reason for such decision. Do you have a project for which TeaVM produces too many code?

**Comment by wordlessly** [comment]
Most projects have many dependencies (jars). Many of those jars contains hundreds or thousands of classes although my code only uses 1-5 of those classes. I assumed TeaVM does at least an import analysis and removes all the classes not needed for the execution of my code before it compiles everything to Javascript?

**Comment by konsoletyper** [comment]
Did you try it?

**Comment by wordlessly** [comment]
No, I am currently evaluating several 'frameworks' that do Java-to-JS.

**Comment by konsoletyper** [comment]
So if you are interested: TeaVM removes unused classes and unused methods. If you are interested in detail, you can build simple project and see what classes are there (you need to disable minification, see `pom.xml` generated by archetype).

**Comment by wordlessly** [comment]
Can you point me to the code (packages/classes) that remove unused classes and methods? I prefer reading source code.

**Comment by konsoletyper** [comment]
Most of DCE is in `org.teavm.dependency` package, you can start learning from [DependencyAnalyzer](https://github.com/konsoletyper/teavm/blob/a5ba6f247e50ac89d93432d3bfefa58ce69f10db/core/src/main/java/org/teavm/dependency/DependencyAnalyzer.java) class

**Comment by wordlessly** [comment]
In case I decide to use TeaVM I would like to improve unnecessary-code-removal as much as possible.  Maybe even remove the parts of a method that will never be executed given certain conditions known beforehand (e.g.: the method argument can never be null, so I can remove the parts that are executed conditionally when the arguments is null).

Or do you think one cannot improve the already existing removal heuristic any more?

**Comment by konsoletyper** [comment]
I think everything is possible. But look, I've been improving DCE for years, so it's really hard to improve anything else.
