### ISSUE TITLE
byte[] is not Object[]

### ISSUE THREAD

**Issue by volth** [konsoletyper/teavm#411]
This should print `false`, but it prints `true` in TeaVM (C-target)

```java
public class Client {
  public static void main(String[] args) {
    byte[] ab = {1};
    Boolean z = Boolean.valueOf((Object)ab instanceof Object[]);
    System.out.println(z.toString());
  }
}
```

this bug results in segmentation fault in simple Scala code
```scala
 val ab = Array[Byte](0.toByte, 1.toByte, 2.toByte)
```

**Comment by konsoletyper** [comment]
Thanks, I'll check that. Also, it's useful to provide native stack traces (i.e. output of `fr` command in gdb after you reach sigsegv).

**Comment by volth** [comment]
It is already result of stacktrace analysis :)

https://github.com/scala/scala/blob/515916c42f8f2f5c476ffabd6774e5a903feda10/src/library/scala/runtime/ScalaRunTime.scala#L73-L81

`xs` being `Array[Byte]` passes check that it is `Array[AnyRef]` and then wrongly cast to it

**Comment by volth** [comment]
the new test fails on JS target:
https://travis-ci.org/konsoletyper/teavm/builds/568869060#L4425-L4464
