### ISSUE TITLE
Thread problem when built with IDEA Dev server 

### ISSUE THREAD

**Issue by mfdewit** [konsoletyper/teavm#420]
I've mentioned this problem on the google group as well, but I think it is a bug. So here it is again :)

I've encoutered some strange behavior doing a Thread.sleep when building using the IDEA Dev server: the delayed message from the example below is never printed.
When using the normal build, it works as expected and the message is printed on page load:
The code below demonstrates this issue

```
public static void main(String[] args) {
    Runnable r = ()-> {
        System.out.println("Run");
        try {
            Thread.sleep(1000);
            System.out.println("delayed message");
        }
        catch(InterruptedException e) {
            System.out.println("error "+e);
        }
    };
    new Thread(r).start();
}
```

**Comment by konsoletyper** [comment]
Isn't is fixed in latest `master`?

**Comment by mfdewit** [comment]
Great, I've created a new build from master and it is working indeed. Good job.
This feature is a real time saver!
