### ISSUE TITLE
Possible bug in CodeServlet? Devserver not detecting changes

### ISSUE THREAD

**Issue by mfdewit** [konsoletyper/teavm#421]
Since 0.6.0 the DevServer is not detecting changes anymore when a class is built.
I've tracked the problem down to the CodeServlet constructor:

```
public CodeServlet(String mainClass, String[] classPath) {
        this.mainClass = mainClass;
        this.classPath = classSource != null ? classPath.clone() : new String[0];
```
Obviously classSource is always null when the constructor is called, causing the classPath parameter to be ignored. Changes are detected again when changing this to:
`this.classPath = classSource == null ? classPath.clone() : new String[0];`

Having said this, I don't understand the purpose of the condition on this line.

**Comment by konsoletyper** [comment]
Obviously, it's mistyped. It should be `classPath != null`.
