### ISSUE TITLE
Cannot print byte array to console

### ISSUE THREAD

**Issue by ccadete** [konsoletyper/teavm#43]
When trying to print a byte array:
```
System.out.println(new byte[] {1, 2, 3});
```
The error is raised:
```
Cannot read property 'characters30' of null
```
A workaround is to wrap in a String
```
System.out.println(new String(new byte[] {'a', 'b', 'c'}));
```

**Comment by konsoletyper** [comment]
@ccadete what do you want this snippet to print in the real JVM? I ran this code and got something like:

    [B@3f26f816

There is no variant of `PrintStream.println` for byte array, so the variant for `Object` is called. This method should call `toString` and send the resulting string to the decorated `OutputStream`. `toString` for arrays does not do what you are expecting, it just calls the default implementation of `toString`, that simply generates such string by combining `getClass().getName()` and object identity. However, `Class.getName()` is not supported properly in TeaVM. This issue will be fixed soon, but there is no use in your snippet. You should prefer wrapping in a `String` or call `System.out.write` method.

**Comment by ccadete** [comment]
Thanks, it was just an example test code, the Object.toString should be the one called.
