### ISSUE TITLE
Use RESTClient in EventListener not working

### ISSUE THREAD

**Issue by olivierayache** [konsoletyper/teavm#436]
When I use RESTClient in an EventListener I got the following error:

Uncaught TypeError: Cannot read property 'isResuming' of null. 
It seems that $rt_nativeThread() returns null

The same call in main method works perfectly.

**Comment by konsoletyper** [comment]
You can't call coroutines from native JavaScript, read [this](http://teavm.org/docs/runtime/coroutines.html). Unfortunately, TeaVM does not report this issue clearly. You should run RESTClient requests from a separate thread.
