### ISSUE TITLE
#Question Is there a way to include certain classes

### ISSUE THREAD

**Issue by exellian** [konsoletyper/teavm#442]
I am about to write a component based frontend System where Components should be compiled into the classes.js but they are used later. So the main method creates them with reflection.

At the moment i have the problem that the classes get not included into the compile process. Is there a way to achieve this?

I noticed the function setClassesToPreserve and it also works with default ClassLoader and default src directory, but when i add another SourceFileProvider and othe ClassLoader it doesnt work anymore

**Comment by konsoletyper** [comment]
It's highly recommended to avoid reflection in TeaVM. Please, describe your task in detail so I could recommend you how to solve it without reflection. Also, you can take a look at [metaprogramming API](http://teavm.org/docs/runtime/metaprogramming.html).

**Comment by exellian** [comment]
I need to be able to instantiate unknown classes (component classes) with only the name of the class, because thats what exists in the template file. So at the moment i have a compiler program written in java and that runs in the normal jvm. This program retrieves all the component classes via reflection with a given folder path. Then I inject the classname array into the teavm compiled javascript script, so that the teavm program knows of all component classes and renders the component data to templates. This sounds really complicated, but i don't know if there is a better way. It would be nice if i could directly access all compiled classes and instantiate them directly without that injection part and if i could do the Class. forName with the metaprogramming api

**Comment by konsoletyper** [comment]
So I suspect you need something similar to Flavour template engine? You can look at its source code (which is based on metaprogramming API) and learn how it deals with components. Metaprogramming API has method similar to `Class.forName` - `Metaprogramming.findClass`. Please note that Metaprogramming API is a compile-time API, not a run-time API.

As for writing TeaVM-specific code. There are several ways to do that, the easiest one is to use `PlatformMarker` annotation. To learn how to use the annotation, you can find usages of this annotation in TeaVM code base.

**Comment by exellian** [comment]
Ok Thank you very much!
