### ISSUE TITLE
Add DataOutput interface.

### ISSUE THREAD

**Issue by ccadete** [konsoletyper/teavm#47]
Can the TDataOutput interface be added to classlib. Thanks.

**Comment by shannah** [comment]
I have added this and a few other classes to my local copy.  However, I pulled them from a repo that is GPL+Classpath exception.  Where is the best place to "steal" these classes that would yield a compatible license with TeaVM?

**Comment by konsoletyper** [comment]
You can't steal code with GPL. Consider borrowing from Apache licensed projects. Personally, I get code from Apache Harmony.

Do you mean only interface, or DataOutputStream as well?

**Comment by shannah** [comment]
I needed a few classes.  I pulled the DataOutput interface, and the DataOutputStream -- there were a few others also.  I'll redo it with Harmony's versions and do a pull request.
