### ISSUE TITLE
#Question Can i access fields from javascript side of a java object

### ISSUE THREAD

**Issue by exellian** [konsoletyper/teavm#473]
First of all to understand the context: I wrote a templating engine in typescript and I want to fill the templates with data of a component instance of a component class, which is implementing the JSObject interface. When I print the object via console.log I see that the fields are there, but they have very unidentifiable names like b7 or something similar. So my question is if there is a possibility to get the names of the fields and identifying their type. So basically can I convert java objects to javascript objects or access java object fields via field identification and type reflection?

**Comment by konsoletyper** [comment]
You can't access fields. The only way to access TeaVM objects from JavaScript world is to declare JSObject interface with methods and then implement this interface in Java and pass it to native JavaScript methods. Properties aren't supported in this case (no particular reason, just haven't chance to do that). TeaVM was not designed for seamless interaction with JavaScript code.

**Comment by exellian** [comment]
Ok thank you then I have to figure out a different solution
