### ISSUE TITLE
#question Modularisation of java code

### ISSUE THREAD

**Issue by exellian** [konsoletyper/teavm#485]
My question is, if I have two java projects, both transpiled to javascript with teavm, is there an compiler option to include the teavm runtime and libaries in one js file and not in the secound one to avoid duplicate code (I use TeaVMTool from the standalone jar). My goal is to create some type of a runtime which can load modules of transpiled java code into it and have access to the classes of this module.

**Comment by konsoletyper** [comment]
Hello. There's no such compiler option and there won't be any ever.

**Comment by exellian** [comment]
ok
