### ISSUE TITLE
Optimize event handler generated code

### ISSUE THREAD

**Issue by ccadete** [konsoletyper/teavm#49]
When handling events as the following:
```
private HTMLButtonElement startButton;
    
public void onLoad() throws IOException {
	startButton.addEventListener("click", new EventListener() {
		@Override
		public void handleEvent(Event evt) {
			// do event
		}
	});
}
```
The generated code is always replicated for each event handling:
```
a.addEventListener($rt_ustr(b), (function($instance, $property) { return function() {
    return $instance[$property].apply($instance, arguments);
};})(c, $rt_ustr($rt_s(12))));
```
Can it be replaced with a new runtime function, for example:
```
var $rt_bind = function($instance, $property){ return function(){ 
	return $instance[$property].apply($instance, arguments); 
};};
```
reducing the generated code:
```
a.addEventListener($rt_ustr(b), $rt_bind(c, $rt_ustr($rt_s(12))));
```

**Comment by konsoletyper** [comment]
It might be optimized even better. First, it would be better if function was cached as an instance's field. It could allow the following code:

```java
EventListener listener = new MyEventListener();
button.addEventListener(listener);
// ...
button.removeEventListener(listener);
```

Second, I'd prefer to get rid of string-based method name and generic `apply` function with variable-length arguments. Instead, specific function for each functor type should be created, with predefined method name and argument list.

**Comment by konsoletyper** [comment]
I fixed this in https://github.com/konsoletyper/teavm/issues/103
