### ISSUE TITLE
Method invoked where this is null

### ISSUE THREAD

**Issue by hohwille** [konsoletyper/teavm#494]
I am getting this exception from my TeaVM generated JavaScript
```
Uncaught TypeError: Cannot read property '$child0' of null
    at igmutwc_TvmSlot_setChild0 (VM1580 classes.js:10015)
    at igmutwc_TvmSlot_setChild (VM1580 classes.js:10029)
    at igmusc_AbstractUiNavigationManager_navigateRecursive (VM1580 classes.js:2769)
    at igmusc_AbstractUiNavigationManager_navigateTo (VM1580 classes.js:2752)
    at igmutc_TvmNavigationManager_onLocationChange (VM1580 classes.js:2982)
    at igmutc_TvmNavigationManager_doInit (VM1580 classes.js:2925)
    at igmusc_AbstractUiNavigationManager_init (VM1580 classes.js:2745)
    at igmudt_UiDemoTvm_start (VM1580 classes.js:720)
    at igmudt_UiDemoTvm_main (VM1580 classes.js:799)
    at VM1580 classes.js:458
```

Debugging reveals that the variable `this` in that class is `null`. In regular Java it is completely impossible that you are inside a non-static method and `this` is `null`. Seems there is a bug in Java emulation somehow.
![Screenshot 2020-05-03 at 15 10 55](https://user-images.githubusercontent.com/1923119/80915163-ae561a80-8d50-11ea-90cf-fa15356b72b5.png)
As you can see in the debugger both `$this` is `null` and also `this` is `undefined` leading to the comparison `this.child == child` to fail with a null-pointer.

**Comment by konsoletyper** [comment]
`this` is not used by TeaVM, so the correct is `$this` variable. This behaviour is expected, since TeaVM does not reproduce 100% behaviour of Java machine in favour of performance. There's strict mode, you can enable it and get fair NPE, but this costs some significant performance. This particular case means that somewhere you should have NPE somewhere earlier.

**Comment by hohwille** [comment]
OK. Thanks for the explanation. Any hints how to trace down the actual error in such case? When debugging the NPE is thrown exactly when that if is evaluated so as `$this` is `null` I was assuming that `this.child` is causing the NPE. Maybe that is also what you are saying but want explain that something else went wrong before leading to `$this` being `null`. Still I find it really hard to trace down errors. So maybe I will try to temporary enable strict mode (or all the time during development) in such case and then see if I can find and fix the bug.
Could you give me a hint how to enable strict mode?
I was searching for "strict" in the documentation but could not find it here:
http://teavm.org/docs/tooling/maven.html

**Comment by konsoletyper** [comment]
In case of TeaVM don't read documentation, read the code. If there's support in Maven, you can try to make your IDE to find out actual Maven configuration properties. At least this works in IDEA.

**Comment by hohwille** [comment]
I am using Eclipse and m2e also supports code-completion for maven.
However, there is no suitable option matching:
![Screenshot 2020-05-03 at 17 15 35](https://user-images.githubusercontent.com/1923119/80917830-bff3ee00-8d61-11ea-95b4-46b7efa9036d.png)

I also tried IDEA community edition and your TeaVM plugin but it never worked and I am entirely unable to build or launch the app with that. It also seems that IDEA does not support Java11 properly and also has problems with JPMS. I am happy to learn but there is no working tutorial, documentation, video or whatever and after trying myself for many hours I simply gave up with IDEA as Eclipse is working for me.

**Comment by konsoletyper** [comment]
What version of TeaVM maven plugin you are using? 

See https://github.com/konsoletyper/teavm/blob/7313b2bb62be47a0d778670278186738b3fd6dcb/tools/maven/plugin/src/main/java/org/teavm/maven/TeaVMCompileMojo.java#L83

> I also tried IDEA community edition and your TeaVM plugin but it never worked and I am entirely unable to build or launch the app with that.

What exactly did not work? IDEA is my primary IDE and everything should work fine.

> It also seems that IDEA does not support Java11 properly

IDEA does work with Java 11.

> I am happy to learn but there is no working tutorial, documentation, video or whatever and after trying myself for many hours I simply gave up with IDEA as Eclipse is working for me.

What kind of documentation do you need?

**Comment by hohwille** [comment]
> What version of TeaVM maven plugin you are using?

The latest released version I found which is `0.6.1`.

> What kind of documentation do you need?

I tried to run the vanilla flavour archetype with IntelliJ but it fails to launch anything:

![Screenshot 2020-05-03 at 17 39 39](https://user-images.githubusercontent.com/1923119/80918428-24647c80-8d65-11ea-9e3c-5d07f9e032d7.png)

Thanks for asking. You do not need to support me with my problems. Maybe it is because I have MacOS. No clue but IntelliJ never worked for me - I can not even run simple JUnits.
I also reinstalled IntelliJ without any progress so it seems IDEA does not like me.

**Comment by konsoletyper** [comment]
> The latest released version I found which is 0.6.1.

You should use [preview build](https://github.com/konsoletyper/teavm#preview-builds)

> I tried to run the vanilla flavour archetype with IntelliJ but it fails to launch anything:

So the message should be clear: the directory you specified as Java home does not contain a valid JRE. How did you install JDK?

 > You do not need to support me with my problems. Maybe it is because I have MacOS. 

This is definitely not due to MacOS. My colleagues use MacOS and Windows, and everyone got IDEA working with TeaVM plugin.

**Comment by hohwille** [comment]
> So the message should be clear: the directory you specified as Java home does not contain a valid JRE. How did you install JDK?

I am running Eclipse and Maven with the same JDK without issues.
I downloaded the JDK from AdoptOpenJDK.
To get a fully reproducible environment you can even use `devonfw-ide` (https://devonfw.com). With that I tested it was well.

> This is definitely not due to MacOS. My colleagues use MacOS and Windows, and everyone got IDEA working with TeaVM plugin.

OK. Good to know, but MacOS is very strange. An application like the JDK is actually a folder with a `Contents` subfolder containing `Home` and `MacOS` folders. This is often causing issues when stuff is not well tested and prepared for MacOS.

For the record:
```
/Users/hohwille/projects/software/default/java/11.0.5_10/Contents/Home/bin/java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
```

So I changed the JDK location and added `Contents/Home` then the error goes away and I get the next error (I already went through all this many times):
![Screenshot 2020-05-03 at 18 19 26](https://user-images.githubusercontent.com/1923119/80919545-ccc90f80-8d6a-11ea-95c2-a5d664123c35.png)

**Comment by hohwille** [comment]
> You should use preview build

Thanks for the link. Great. I updated to `0.7.0-dev-1090`.

**Comment by hohwille** [comment]
We can still chat here, but I am closing this issue as indeed the object the method was invoked on was already `null`. Your optimizations are fine - it is only a little tricky to debug in the browser.
And for that it is especially hard because `TString` is implemented as a `char[]` instead of wrapping a plain JavaScript String inside. I have no clue if maybe JavaScript String is too limited to handle Java Unicode compatibility but GWT was designed so that `java.lang.String` behaved in the browser like a JavaScript `String` including regex stuff that really gave some incompatibilities. But emulating a String this way is making debugging extra hard and looks like some low-level overhead (I am not trying to convince you to change your design, just want to understand).
![Screenshot 2020-05-03 at 18 26 18](https://user-images.githubusercontent.com/1923119/80919893-b3c15e00-8d6c-11ea-9506-d74f5cd995b5.png)

So in case I would get TeaVM plugin working for dev that would really be a big boost. I will also update to latest dev.

**Comment by konsoletyper** [comment]
> I have no clue if maybe JavaScript String is too limited to handle Java Unicode compatibility

It's not about Unicode features, it's all about Java features. GWT does a lot of tricky things (of course in cost of performance) to properly emulate all aspects of `java.lang.String`. Also, TeaVM targets not only JavaScript, so having unified String implementation is useful there as well (unless I'm going to have separate String implementation for each platform)

> But emulating a String this way is making debugging extra hard 

Not that hard. First, it's possible to debug in IDEA using plugin and you will see strings as they are. I had an Eclipse plugin, but abandoned it. Anyone can pick the plugin and continue maintaining it. Second option is to call `toString()` on TeaVM strings and you'll get JavaScript string.

> and looks like some low-level overhead

it's not overhead at all. It's only overhead when you call JavaScript from Java and vice versa. And emulating over JavaScript string is an overhead spread over entire program, even when you don't deal with strings.

**Comment by konsoletyper** [comment]
> So I changed the JDK location and added Contents/Home then the error goes away and I get the next error (I already went through all this many times):

Can you provide a sample project for me to reproduce this? BTW, what plugin version did you install? Did you follow preview builds for IDEA instructions? Did you install latest 0.7.0-dev build?
