### ISSUE TITLE
Optimize classes and methods that use final modifiers

### ISSUE THREAD

**Issue by ccadete** [konsoletyper/teavm#50]
If a method has the final modifier with no class hierarchy it could be inlined. It can be applied to getters/setters, example:
```
public final class Point {
	private int x;
	private int y;

	public Point() {
		x = 0; y = 0;
	}

	// getters / setters
}
```
The access to the fields could be inlined for faster access.

**Comment by konsoletyper** [comment]
Wrong. Inlining should be done in more general way. TeaVM has enough information to determine, that particular call site is monomorphic and hence can be inlined, so we don't really need rely o final modifier. However, all inlining must be done very carefully, as it can break V8/SpiderMonkey optimizer. BTW, they both perform inlining themselves, so there may be no need in inlining in TeaVM. Also, inlining itself won't give significant performance gain. It only gives another optimizations chance to to their work better. Please, read [Purple dragon book](http://www.amazon.com/Compilers-Principles-Techniques-Tools-Edition/dp/0321486811) and articles about how V8 works.
