### ISSUE TITLE
Unused lambda expression causes NullPointerException when compiling

### ISSUE THREAD

**Issue by negora** [konsoletyper/teavm#500]
Hi:

If you have an unused lambda expression in your code, it causes a `NullPointerException`. At least when compiling the project with the Maven's plug-in. This bug exists in version 0.6.1 and also 0.7.0-dev-1105.

Example:

```java
public final class EntryPoint {

	public static void main (String[] arguments) {
		Consumer<String> foo = (bar) -> {};
	}

}
```

This may look like an usual situation, but I left one of this expressions by mistake in my code, and it took me a lot of time to find the cause, because the exception message is not descriptive enough.

In my opinion, the compiler should silently remove the expression.

Thank you!

**Comment by konsoletyper** [comment]
> In my opinion, the compiler should silently remove the expression.

I fully agree, compiler should not crash in any scenario and in case you have problems in your code it should assist you to fix them.

**Comment by negora** [comment]
Thank you!
