### ISSUE TITLE
Java source files are not copied when "optimizationLevel" is set to "SIMPLE"

### ISSUE THREAD

**Issue by negora** [konsoletyper/teavm#501]
Hi:

When you use the plug-in for Maven and set the `optimizationLevel` option to `SIMPLE`, the plug-in does not copy the Java source files to the target directory; it only copies the source maps. These are the most relevant options of my configuration:

```xml
...
<sourceMapsGenerated>true</sourceMapsGenerated>
<sourceFilesCopied>true</sourceFilesCopied>
<optimizationLevel>SIMPLE</optimizationLevel>
```

If you set `optimizationLevel` to `ADVANCED` or `FULL`, though, the source files are effectively copied there.

This happens in version 0.6.1 and also 0.7.0-dev-1105.

The only workaround that has came to my mind is to compile first in `ADVANCE` level and then in `SIMPLE` level. But it's tiring when you need to do multiple clean-then-build actions.

Thank you.

**Comment by negora** [comment]
I guess that it's not directly related but setting `incremental` to `true` also prevents the copy of source files, even although you do a full clean-and-install cycle.

Surprisingly, the plug-in output states that the source files have been copied:

```
Running TeaVM
Cache is missing
Output file successfully built
Source maps successfully written
Source files successfully written
Cache updated
```

**Comment by konsoletyper** [comment]
I fixed the issue. However, I see that your are trying to use Maven for development cycle, which is inefficient. I'm going to remove incremental mode from Maven build at all. You can try to use dev server available on IDEA plugin (which has really efficient incremental compilation and performs deobfuscation of stack traces and allows debugging right in IDEA) or if IDEA is not an option for you, ask me and I provide further instructions to setup CLI version of dev server.

**Comment by negora** [comment]
> I fixed the issue.

First of all, thank you for fixing it. I've compiled TeaVM again and it works well now.

> However, I see that your are trying to use Maven for development cycle, which is inefficient.

I've realized about that during this week, when I've been doing some experiments. I'm converting a TypeScript project to use Java/TeaVM instead, and each small change has required a new Maven execution, which takes a lot of time. I've used some tricks to reduce the JVM start time, but it's not enough.

> You can try to use dev server available on IDEA plugin (which has really efficient incremental compilation and performs deobfuscation of stack traces and allows debugging right in IDEA) or if IDEA is not an option for you, ask me and I provide further instructions to setup CLI version of dev server.

I'm using NetBeans IDE. I've considered IntelliJ IDEA a few times, but I've not had enough time to test it thoroughly (I also like NetBeans much, sincerely). If you could publish some instructions for the CLI version, for example in the `README.md` file, I would appreciate it. Thank you in advance!

**Comment by konsoletyper** [comment]
Ok, but writing a documentation requires some time and efforts from my side which I don't have. So in brief you need `teavm-cli` artifact. To build it, you need to enable `with-cli` Maven profile. CLI module is located at `tools/cli` directory. Also, you can download this artifact from bintray (for example, current latest one is https://bintray.com/konsoletyper/teavm/download_file?file_path=org%2Fteavm%2Fteavm-cli%2F0.7.0-dev-1105%2Fteavm-cli-0.7.0-dev-1105.jar). 

Run 

```
java -cp teavm-cli-0.7.0-dev-1105.jar org.teavm.cli.TeaVMDevServerRunner
```

from command line and you'll get some help.

You'll need to specify following options:

```
java -cp teavm-cli-0.7.0-dev-1105.jar org.teavm.cli.TeaVMDevServerRunner \
  package.name.MainClassName \
  -p classpath-element1 \
  -p classpath-element2 \
  -s source-element1 \
  -s source-element2 \
  --deobfuscate-stack \
  --indicator
```

And dev server will serve generated Javascript at http://localhost:9090/classes.js. Classpath elements are either directories (`path/to/module/target/classes` or jar files). Each time `.class` files are updated, TeaVM will pick these changes and rebuild Javascript.

**Comment by negora** [comment]
Great! I'm going to try it right now. Thank you for your help :+1: .

**Comment by negora** [comment]
I've added, in my `index.html` file, a `<script>` tag pointing to `http://localhost:9090/classes.js`. Then I've run the compilation server and I've made a small change in a class. And it has worked flawlessly. Less than a second to publish the change! What a difference.

Now I'm going to explore the available options, but I better publish my doubts in Google Groups to avoid "polluting" this report. Again, thanks a lot!

**Comment by ScraM-Team** [comment]
@negora , please post more about your experience with teavm-cli and NetBeans.  I would like to hear how to set this up.  I will also post sometime about a TeaVM plugin for NetBeans I have been working on.  Maybe I can add teavm-cli support once I see how it works.

**Comment by negora** [comment]
@ScraM-Team Well, I guess that my setup is really rustic compared to using IntelliJ IDEA with the TeaVM plug-in.

I started with the Maven archetype that is provided by TeaVM. NetBeans IDE has fantastic support for Maven, so the experience with it is good. In general, I love programming in NetBeans.

Once that @konsoletyper told me about the existence of `teavm-cli`, I stopped using Maven manually for the generation of the JS code during the development phase. NetBeans still uses Maven to compile the Java source code, of course. But it's completely transparent because, by default, the IDE compiles automatically after saving each file.

Invoking the compilation server requires to pass all the JARs, classes and source files that you use in your project. Since it's quite tedious and I'm still experimenting a lot, I decided to make a simple Bash script (Linux) to automate all this process. It's worth it.

For debugging, I use the debugger of by browser, Firefox. It's not easy, because, although you see the Java source files, the shown variables are the ones from the JS side, of course. Since there isn't a 1:1 translation from Java to JS, sometimes it's complicated to get certain value. For example, even a static `String` is not viewable as-is. You need to add a watch in the debugger and invoke the `$rt_ustr ()` to view the content.

When I've some free time, I'll try to write my experiences with NetBeans+TeaVM in the TeaVM group at Google Groups. If you want to use my Bash script, I'll share it. Although it's very basic and there are some pending improvements that I want to introduce.

**Comment by ScraM-Team** [comment]
Thanks for this!  The script sounds useful, please post it when you are ready.  I had hoped teavm-cli would work with a folder instead of needing a list of files, but if a script can automate then you have solved that problem.

I have started work on a TeaVM plugin for NetBeans.  I'll post more when it becomes useful.  Initial features will be simple (single-click to open a template HTML).  I'd like the plugin to be able to jump to a method by clicking on it in a template, but that will require deep integration with Flavour EL parsing, which will take me some time.

Let me know if you'd be interested in trying the NetBeans plugin sometime.

**Comment by negora** [comment]
Yes, you can pass a path to a directory tree that contains classes. The work of @konsoletyper is perfect in that sense. But you also need to pass all the list of dependencies of your project (the JARs). My script simply automates the obtaining of that information from the Maven project, and then, the subsequent invocation to the server.

I'm usually very busy, but I would love tracking the evolution of that plug-in ;-) . I don't use Flavour though. I don't know if I can be of any help. Create a thread at Google Groups and maybe more people can join to the effort too.
