### ISSUE TITLE
forEach for default collections is much slower than for (...) iteration

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#507]
Recently I performed refactoring of my project and noticed strange thing. I am generating large SVG with multiple polygons. After refactoring I noticed large performance decrease. The model that took 10 seconds to generate before refactoring took 45 seconds to generate (in debug mode). I started investigating and noticed one strange thing: changing only one line of code improves performance 3 times (to 15 seconds, not as good as previously, but it's ok assuming that I improved code clarity).
So, here are this lines:
```
Field.fields().forEach(f -> // Field.fields is just Arrays.stream(Field.CACHE)
                hexagons.get(f).getParts().values().forEach(canvas::appendChild));
```
changed to:
```
for (Field f : Field.CACHE) {
            for (HTMLElement part : hexagons.get(f).getParts().values()) {
                canvas.appendChild(part); // canvas is SVG element
            }
        }
```
The same operation is performed in other place with list (replacing "forEach" by "for")
I reviewed source code https://github.com/konsoletyper/teavm/blob/master/classlib/src/main/java/org/teavm/classlib/java/util/TArrayList.java and noticed that neither THashMap values()  nor TArrayList contains forEach override. In the same time, in JDK sources both are overridden.
I raised the issue because I don't have easy and clean test that can confirm my assumption, but missing implementation of forEach is suspicious.

**Comment by Ihromant** [comment]
Tried new version of 0.7.0-dev-1128 and noticed almost no difference in speed between for( and forEach( . Still not all default collections have custom forEach implementation. As I understood, I need to go througn classLib and look at collections that doesn't have forEach implemented (TreeMap/Set, HashSet, PriorityQueue come to mind for instance). Is it correct approach?

**Comment by konsoletyper** [comment]
Also, you can just avoid `forEach` methods and use `for` statement. Is there any advantage in `forEach` method over `for` statement?
