### ISSUE TITLE
Stream.of is broken for "*Match"

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#517]
Real output of such code:
```
System.out.println(Stream.of(1, 2, 3).anyMatch(i -> i == 3) + "");
System.out.println(Stream.of(1, 2, 3).anyMatch(i -> i == 2) + "");
System.out.println(Stream.of(3).anyMatch(i -> i == 3) + "");
```
is:
false
true
false
Expected is:
true
true
true

Similarly, last value is ignored for noneMatch and allMatch.

**Comment by konsoletyper** [comment]
Could not reproduce. Could you provide more information on how you are using TeaVM? Can you attach a self-contained sample project that reproduces the issue?

**Comment by Ihromant** [comment]
https://gofile.io/d/NDOItA
Here are zip files with simple projects that reproduce issue. Launch teavm:debug in IDEA, then jetty:run in IDEA, then go to localhost:9090

**Comment by Ihromant** [comment]
I can confirm that with newest teavm 0.7.dev version issue is not reproducible.
