### ISSUE TITLE
java.lang.IllegalArgumentException: Node must not be null

### ISSUE THREAD

**Issue by LAX1DUDE** [konsoletyper/teavm#521]
I've actually ported minecraft to run in chrome using your tools ([https://x-games.nx-eags.tk/minecraft_demo/](https://x-games.nx-eags.tk/minecraft_demo/)) but I still can't pass an average of more than 40fps and I feel that using the webassembly backend would help bring that number up. The problem is I can't get it to work, the compiler produces this error:

```
Caused by: java.lang.IllegalArgumentException: Node must not be null
	at org.teavm.dependency.DependencyNode.connectWithoutChildNodes(DependencyNode.java:285)
	at org.teavm.dependency.DependencyNode.connect(DependencyNode.java:271)
	at org.teavm.dependency.DependencyNode.connect(DependencyNode.java:388)
	at org.teavm.dependency.DependencyGraphBuilder$1.exit(DependencyGraphBuilder.java:261)
	at org.teavm.model.InstructionReadVisitor.visit(InstructionReadVisitor.java:122)
	at org.teavm.model.instructions.ExitInstruction.acceptVisitor(ExitInstruction.java:34)
	at org.teavm.model.BasicBlock.readAllInstructions(BasicBlock.java:314)
	at org.teavm.dependency.DependencyGraphBuilder.buildGraph(DependencyGraphBuilder.java:111)
	at org.teavm.dependency.PreciseDependencyAnalyzer.processMethod(PreciseDependencyAnalyzer.java:35)
	at org.teavm.dependency.DependencyAnalyzer.lambda$scheduleMethodAnalysis$8(DependencyAnalyzer.java:512)
	at org.teavm.dependency.DependencyAnalyzer.processQueue(DependencyAnalyzer.java:670)
	at org.teavm.dependency.DependencyAnalyzer.processDependencies(DependencyAnalyzer.java:697)
	at org.teavm.vm.TeaVM.build(TeaVM.java:376)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:414)
	at org.teavm.tooling.builder.InProcessBuildStrategy.build(InProcessBuildStrategy.java:247)
	... 98 more
```

is there any known cause for this failure?

I won't bother trying to upload the source yet, the whole game stripped down is still 120,000 lines of java, but if you think it's worth wading through I can make a repository

**Comment by LAX1DUDE** [comment]
my goal is to make this efficient enough to play on the chromebooks at my high school, so 40fps on a gaming pc will scale to like 10fps on a tiny netbook

**Comment by konsoletyper** [comment]
WebAssembly support is incomplete and may produce some errors. I can't investigate this issue without ability to reproduce it locally. Even if I investigate and fix issue there might be hundreds of other issues that you meet. WebAssembly does not guarantee better performance. You can give a try to JavaScript, just compile to non-obfuscated JavaScript and use profiler from Chrome dev tools to find performance bottlenecks.

BTW, which version of TeaVM you are using? And what are compiler settings?

**Comment by LAX1DUDE** [comment]
I am using teavm 0.6.1 from jcenter, with FULL optimization and minification enabled. I disable minification when I debug

I've been analyzing the non-minified javascript for weeks now and I have a good idea where the bottlenecks are. The largest bottleneck is all the minecraft code for dynamically generating chunk meshes at runtime for the terrain, it makes 100s of function calls per block in chunks of 4096 blocks at a time, and profiling shows it consumes 30% of CPU cycles and it's been optimized to frick already. large amounts of casting and bitwise operations and array lookups are used

**Comment by konsoletyper** [comment]
Can you use latest development version of TeaVM and compare performance? Can you switch to ADVANCED optimization level?

**Comment by LAX1DUDE** [comment]
okay I'll reconfigure my project and use the latest travis build. give me a day or so I'm not very fluent in maven. I did not realize the jar on jcenter has not been updated in a year

**Comment by konsoletyper** [comment]
Please, learn project README, for example [this particular section](https://github.com/konsoletyper/teavm#preview-builds)

**Comment by ScraM-Team** [comment]
@LAX1DUDE , this is very cool!  On a reasonably fast system this starts up quickly.

When we tried the link above it launches, but the servers aren't reachable.  And the single-player option is disabled.  Is there a different version we could try?

We're very excited, having a browser-based Minecraft client would be a game-change, so to speak.

This must have been a lot of work, thanks for sharing this.

**Comment by LAX1DUDE** [comment]
@ScraM-Team I have a compatibility layer built on bungeecord for hosting a websocket endpoint for multiplayer and syncing the skins, singleplayer is disabled because I am not in the mood to port the internal server to web workers to run singleplayer yet. I can publish a repository with all the code but the project is incomplete and averages 40fps on a core i7 with an nvidia gtx 970 so it is not a practical solution for web based minecraft, and additionally it would violate the Minecraft EULA and MCP license agreement and worst of all I don't have a unified build system. The upshot is that the bungeecord compatibility layer does support vanilla 1.5.2 and spigot 1.5.2 servers and therefore all plugins and servers for 1.5.2 will work in this configuration

**Comment by LAX1DUDE** [comment]
@ScraM-Team I see you are using linux, I did some browser compatibility testing yesterday and firefox for linux had a framebuffer-related bug when joining a server, which I plan to fix today. if you would like to see a live demo email me at cgiacun@gmail.com or add me on discord at LAX1DUDE#6306. I don't want to turn this thread into a circus lol

**Comment by LAX1DUDE** [comment]
@konsoletyper @ScraM-Team I will probably fork teavm and optimize it for this project myself, the minified javascript output has syntax errors where it collapses statements like `x - -0.0` to `x--0.0`, for example (obviously bad practice but anyone who's experimented with minecraft knows notch is a bad programmer so the game is littered with stuff like this) and others like it. I've had the whole game with multiplayer and sound running in my browser for a long time I've just been optimizing it and while I appreciate how close to the JVM spec teavm is its not like I'm gonna take this to the moon so I'm okay with sacrificing some mathematical precision for an overall increase in client performance. I've done everything I can to strip the minecraft client down removing the internal server and world generation and MCO and all that jizz so I'm only focusing on optimizing the purely client-side code now related to rendering where I've built a desktop opengl 3.0 compatibility layer that the game runs inside which can be swapped with a class linking to teavm's webgl adapter on a very low level (I write code with teavm's preformance favored usually). Additionally I replaced the Tessellator class (mojang (idiot) talk for "vertex buffer/array") to use bare metal webgl in the browser too so I'm approaching the limit in terms of data transfer because I'm using multiple ArrayBufferViews of the same ArrayBuffer to write the different data types for each vertex to the upload buffer. I achieve an average framerate of 500fps with the render distance set to normal with occlusion culling  using my java binding with FXAA but the browser rarely cracks 50fps and minecraft's built in profiler (thanks, mojang) shows that only a single chunk can be built and uploaded to the gpu every frame (maybe use optimized web workers?) and it uses 30% of the cpu doing just that because mojang doesn't understand how to write cache-friendly code so the chunk block renderer is a huge mess and honestly it's so bad it's almost cute (I'm using minecraft 1.5.2 for this project because it was the last minecraft release to use java.net.Socket as its primary network interface because I didn't want to deal with mojang's netty hack) so I'm just gonna experiment with teavm itself making minecraft related optimizations and if @ScraM-Team wants to work with me that's fine just know I'm 16 and I'm getting a job when covid is over

**Comment by LAX1DUDE** [comment]
@konsoletyper I'm still trying to make webassembly work (I'm using the latest snapshot of teavm from ~2 weeks ago, as in 0.7.0-SNAPSHOT). The stack trace of the error I receive remains unchanged. I never asked, but can you give me a hint on what the mechanism of the exact step is in the build process is that corresponds to this stack trace?

```
Caused by: java.lang.IllegalArgumentException: Node must not be null
	at org.teavm.dependency.DependencyNode.connectWithoutChildNodes(DependencyNode.java:290)
	at org.teavm.dependency.DependencyNode.connect(DependencyNode.java:271)
	at org.teavm.dependency.DependencyNode.connect(DependencyNode.java:394)
	at org.teavm.dependency.DependencyGraphBuilder$1.exit(DependencyGraphBuilder.java:263)
	at org.teavm.model.InstructionReadVisitor.visit(InstructionReadVisitor.java:122)
	at org.teavm.model.instructions.ExitInstruction.acceptVisitor(ExitInstruction.java:34)
	at org.teavm.model.BasicBlock.readAllInstructions(BasicBlock.java:314)
	at org.teavm.dependency.DependencyGraphBuilder.buildGraph(DependencyGraphBuilder.java:111)
	at org.teavm.dependency.PreciseDependencyAnalyzer.processMethod(PreciseDependencyAnalyzer.java:35)
	at org.teavm.dependency.DependencyAnalyzer.lambda$scheduleMethodAnalysis$8(DependencyAnalyzer.java:498)
	at org.teavm.dependency.DependencyAnalyzer.processQueue(DependencyAnalyzer.java:656)
	at org.teavm.dependency.DependencyAnalyzer.processDependencies(DependencyAnalyzer.java:683)
	at org.teavm.vm.TeaVM.build(TeaVM.java:379)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:433)
	at org.teavm.tooling.builder.InProcessBuildStrategy.build(InProcessBuildStrategy.java:268)
	... 121 more
```
I'm assuming it's determining which class files (or which methods in each class file) need to be compiled to WASM for the program to link correctly. This puzzles me because I'd assume the process to assemble a dependency graph for a WASM build is the same process used to assemble a dependency graph for a regular Javascript build. Can you tell me how a null pointer like this in these classes of the compiler could arise from the dependency graph step in the build process? Again, this problem does not happen when compiling to Javascript, it only happens with WASM.

There are some `java.lang.reflect` functions used in the game but it never goes beyond invoking a constructor retrieved directly via a `java.lang.Class` object, and the instance of the class object used is always retrieved via the default built-in static `Object.class` variable defined by the JDK compiler on every type in the program. **If reflection is not implemented on WASM I can try removing the parts of the game that use reflection** and try compiling it without them to see if that fixes it, but I don't want to do this yet because it would take a long time to weed out every usage of a `java.lang.reflect` function in the whole program without a precise message describing where in the program it encountered java reflection.

**Comment by konsoletyper** [comment]
@LAX1DUDE I don't know what is the reason for this particular issue. There's no some magic for debugging TeaVM. Just old plain debugger. I can't help with it, until I get the access to the code base you are trying to process with TeaVM. Try set breakpoints and see what's going on, which method produces this error, etc.

> This puzzles me because I'd assume the process to assemble a dependency graph for a WASM build is the same process used to assemble a dependency graph for a regular Javascript build.

Yes, they are same. Java library implementation is not the same, which may be the cause. Also, what about JSO code? Wasm backend does not support JSO.

> If reflection is not implemented on WASM I can try removing the parts of the game that use reflection

Reflection is not implemented in Wasm BE. Moreover, it's not recommended to use reflection with TeaVM, since it can cause performance regression and huge JS file.

**Comment by LAX1DUDE** [comment]
what I was asking is just if you can give me a hint of what particular step in the build process this stack trace corresponds to, instead of asking what the root cause of it is

but...
>  Also, what about JSO code? Wasm backend does not support JSO.

The whole project uses JSO extensively, primarily for fast WebGL on a canvas with event listeners and then the WebSocket API and XMLHttpRequests and local storage and indexeddb are all also used, I guess it could all be re-implemented using many @JSBody annotations but I'm pretty sure that's also a part of what you refer to as the JSO when you say it's not supported

> Reflection is not implemented in Wasm BE. Moreover, it's not recommended to use reflection with TeaVM, since it can cause performance regression and huge JS file.

I have replaced some of the reflection in the game (minecraft) with hashmaps of just individual lambda expressions all for creating a certain instance of many different classes each identified by an id or string in the map. I think the only reflection classes used in the whole game are only used for calling constructors so that makes hashmaps with lambdas a solution to remove all dependence on the `java.lang.reflect` package but `java.lang.Class` is also often used too and idk if that counts as reflection or not.

This issue is basically resolved because there is JSO code all over the project that's being compiled and it looks like none of it is supported by the Wasm BE so it wouldn't be fair to really continue to call this an "Issue" if the crash is literally from it assembling a dependency tree containing JSO classes that aren't supposed to be compiled in Wasm builds

**Comment by konsoletyper** [comment]
`@JSBody` is not supported in Wasm BE as well. Look at [this example](https://github.com/konsoletyper/teavm/blob/393ab3b09ed7bce52a0e5278d04594662326182b/samples/benchmark/src/main/java/org/teavm/samples/benchmark/teavm/WasmBenchmarkStarter.java).

**Comment by konsoletyper** [comment]
@LAX1DUDE I believe that expected behaviour is: gracefully report error and continue. This particular issue is not resolved. However, until I find a way to reproduce it locally or you find a way to fix it and send me a PR, there's no way to resolve it.
