### ISSUE TITLE
String concat issue

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#522]
Simple code:

short s = 1;
System.out.println(s + "2");

fails during the compilation to JS with:
Method java.lang.StringBuilder.append(S)Ljava/lang/StringBuilder; was not found

Obviously it's due to the fact that TeaVM unwraps Java 9+ concat code to StringBuilder, but we need to include that fact that there is no append(short) and append(byte) methods in StringBuilder.

I think that I can try to fix it myself, but I need a hint where to look at.

**Comment by konsoletyper** [comment]
I will fix it myself. Identifying the actual place that causes a bug is 90% of work, so it was trivial to just make remaining 10%.
