### ISSUE TITLE
Element.getTagName() not working

### ISSUE THREAD

**Issue by hohwille** [konsoletyper/teavm#543]
In my TeaVM app in the browser I got this exception:
```
classes.js:449 null: (JavaScript) TypeError: $this.$widget.getTagName is not a function
classes.js:8024 
```

IMHO there is a bug in JSO that `Element.getTagName()` is simply missing `@JSProperty`:
https://github.com/konsoletyper/teavm/blob/b718e7852f2981c968ce740e5d42a57e1ba64c8c/jso/apis/src/main/java/org/teavm/jso/dom/xml/Element.java#L21

**Comment by hohwille** [comment]
Workaround: use `getNodeName()` instead ;)

**Comment by Ihromant** [comment]
Thanks for noticing it. Fixed it https://github.com/konsoletyper/teavm/commit/14ca8ecdbb2fc612b6c1b978a0c7121ea391e149 here because needed this property almost simultaneously with you.

**Comment by hohwille** [comment]
@Ihromant awesome. Your fix looks good to me 👍 So I am closing this issue. Thanks.
