### ISSUE TITLE
(Event.getTarget() instanceof HTMLElement) returns wrong result

### ISSUE THREAD

**Issue by hohwille** [konsoletyper/teavm#549]
TeaVM does a great job hiding away the browser hell and gives developers the feeling that they can write Java code that behaves like what you expect in JVM. Now, I have an event listener that I added to the document body. When I click on a button, I observed that `event.getTarget()` returns that button in the JavaScript debugger. However, `(event.getTarget() instanceof HTMLElement)` returns `false`. Interesting is that casting anyway to `HTMLElement` works without an exception.
Therefore it seems that in some edge-cases `instaceof` does not behave as expected in TeaVM compiled JS.

**Comment by konsoletyper** [comment]
`instance` of does not work with JavaScript classes

**Comment by hohwille** [comment]
Thanks for the explanation. As you already labelled wontfix I close as not planned.
