### ISSUE TITLE
ToggleClass option 

### ISSUE THREAD

**Issue by lucas-goldner** [konsoletyper/teavm#551]
Hey I have code for a menu that opens in javascript like this:
```
    let hamburger = document.getElementById("hamburgerbtn");

    let mobileMenu = document.getElementById("mobileMenu");

    hamburger.addEventListener("click", function () {
      mobileMenu.classList.toggle("active");
    });
```

and I am trying to make this work in Java like this

```
    public void openHamburger( ) throws ClassNotFoundException {
        Element mobileMenu = (Element) Window.current().getDocument().getElementById("mobileMenu");
        mobileMenu.getClass().getClassLoader().loadClass("active");
    }
```

Either my code is wrong or is there no way of toggling the class ?

**Comment by Ihromant** [comment]
@lucas-goldner https://github.com/konsoletyper/teavm/pull/553 this PR fixes issue you mentioned. After it's merged and new dev teavm version released, you can use it as follows:

mobileMenu.getClassList().toggle("active");
