### ISSUE TITLE
DecimalFormat format problem edge case

### ISSUE THREAD

**Issue by reportmill** [konsoletyper/teavm#557]
DecimalFormat works fine for me 99.9% of the time. But every once in a while I hit something like this:

    String str = new DecimalFormat("#.##").format(0.9977993000000007d);

For me this produces the string ".:".

**Comment by ScraM-Team** [comment]
I wonder if this is one of the classes pulled in from Apache Harmony?  Interesting case.

The source is here: https://github.com/konsoletyper/teavm/blob/master/classlib/src/main/java/org/teavm/classlib/java/text/TDecimalFormat.java

Looks very different from the Apache Harmony code here: http://svn.apache.org/viewvc/harmony/enhanced/java/branches/java6/classlib/modules/text/src/main/java/java/text/DecimalFormat.java?view=markup

So perhaps this is one that was hand-coded.  We should contribute a test case.

**Comment by ScraM-Team** [comment]
I wrote a quick test and ran it on a desktop JVM.  

    DecimalFormat decimalFormat = new DecimalFormat("#.##");
    org.junit.jupiter.api.Assertions.assertEquals("1.00", decimalFormat.format(0.9977993000000007d));  // Expected should be 1, really

Output:

org.opentest4j.AssertionFailedError: expected: <1.00> but was: <1>

Now '1' is the right answer, if I'm reading the javadocs right.  It rounds up if more than halfway, and it isn't supposed to show fractional zeroes by default.

So if this isn't working in the browser it is something deeper with how doubles get translated into JS.
