### ISSUE TITLE
Unintended multithreading

### ISSUE THREAD

**Issue by JojOatXGME** [konsoletyper/teavm#561]
I encountered the issue that one event listener gets interrupted by another event listener. Unfortunately, I'm not sure how to reproduce the issue outside of our project. Semantically, I have code similar to the following example.

```java
element.addEventListener("mousedown", (EventListener<MouseEvent>) event -> {
    System.out.println("START mousedown");
    ...
    System.out.println("END   mousedown");
});
element.addEventListener("focus", (EventListener<Event>) event -> {
    System.out.println("START focus");
    ...
    System.out.println("END   focus");
});
```

The code causes the following output when the element receives focus by clicking on it.

```
START mousedown
START focus
END   focus
END   mousedown
```

As you can see, the listener for *mousedown* events gets interrupted by the *focus* event. It looks like – contrary to #436 and #447 – the [coroutines feature](http://teavm.org/docs/runtime/coroutines.html) (i.e. thread emulation) delays part of the execution of the first event listener. This breaks our implementation because the implementation assumes it is running on a single threaded environment.

As far as I know, the event listeners do not call any blocking method*. At least they shouldn't. Can I verify that somehow? Is it possible that TeaVM delays some part of the first event listener although the event listener does not call a blocking method?

\* With "blocking method", I mean methods that have the `@Async` annotation.

**Comment by konsoletyper** [comment]
You can try to find `$rt_suspend` function in generated JS. If it's present, then your code uses multithreading somewhere. Put breakpoint on that function body and you'll find out what actually causes this behaviour. Also, you can find where new threads start by finding `jl_Thread_start` function usages.

**Comment by JojOatXGME** [comment]
Thanks for your input. I took some more time debugging the issue and found that it actually was some unintended recursion. The listener for *mousedown* events called `element.focus()` which triggered the *focus* event listener.

Interestingly, the issue was not 100% reproducible. While I could mostly reproduce the issue on Chrome, I was barely able to reproduce the issue on Firefox. After settings breakpoints, it became difficult to reproduce on Chrome as well. I guess whether `element.focus()` triggers the event listeners when the element is already about to gain focus depends on the timing of the method call. While this is strange, I don't have a better explanation.
