### ISSUE TITLE
repo for recent teavm artifacts???

### ISSUE THREAD

**Issue by hohwille** [konsoletyper/teavm#572]
Already long time ago I told @konsoletyper that bintray service will be discontinued.
This is now the case and breaks my builds:
```
ailed to collect dependencies at org.teavm:teavm-classlib:jar:0.7.0-dev-1185: Failed to read artifact descriptor for org.teavm:teavm-classlib:jar:0.7.0-dev-1185: Could not transfer artifact org.teavm:teavm-classlib:pom:0.7.0-dev-1185 from/to teavm-dev (https://dl.bintray.com/konsoletyper/teavm): authorization failed for https://dl.bintray.com/konsoletyper/teavm/org/teavm/teavm-classlib/0.7.0-dev-1185/teavm-classlib-0.7.0-dev-1185.pom, status: 403 Forbidden -> [Help 1]
```

For undefined reasons maven central still contains rotten old releases of teavm:
https://repo1.maven.org/maven2/org/teavm/teavm-core/

Can you please provide a new solution or link where in your documentation one could find instructions for it?

**Comment by konsoletyper** [comment]
Hello. I migrated to new repository location and updated README.md long ago.

**Comment by hohwille** [comment]
Not a drop-in replacement as it seems:
```
Could not find artifact org.teavm:teavm-classlib:jar:0.7.0-dev-1185 in teavm-dev (https://teavm.org/maven/repository) -> [Help 1]
```

Will check for updates. Deploying to maven central would make things much easier...

**Comment by konsoletyper** [comment]
Just update version.

> Deploying to maven central would make things much easier...

No chance

**Comment by hohwille** [comment]
https://teavm.org/maven/repository/
is not listing anything. No version documented in readme
And the readme is still linking to bintray and should be fixed.

**Comment by hohwille** [comment]
For any request in your "repo" I am getting this:
```
The page you are looking for cannot be found.
403
````

**Comment by hohwille** [comment]
Try yourself:
https://teavm.org/maven/repository/org/teavm/teavm-classlib/

**Comment by hohwille** [comment]
OK, found a version:
https://teavm.org/maven/repository/org/teavm/teavm-cli/0.7.0-dev-1196/teavm-cli-0.7.0-dev-1196.jar

But to avoid giving your users a hard time you should still update your readme and add some hints.
