### ISSUE TITLE
The TeamVM CLI is missing the "runtime" option

### ISSUE THREAD

**Issue by norzak** [konsoletyper/teavm#574]
The TeamVM CLI is missing the "runtime" option. We want to merge the final output to a single one from our build tool, but the runtime option is missing.

**Comment by konsoletyper** [comment]
`runtime` option is deprecated long time ago. TeaVM always includes runtime into resulting JS file

**Comment by norzak** [comment]
Yeah I was using and old version of TeaVM. thanks for heads up.
