### ISSUE TITLE
[Question] What Java bytecode version does TeaVM currently support

### ISSUE THREAD

**Issue by LAX1DUDE** [konsoletyper/teavm#578]
Hi, sorry to slip this in your main issues field, but I'm just wondering what class file version TeaVM supports before I start a project. I just want to know the current version number, otherwise you can close this issue.

**Comment by ScraM-Team** [comment]
Java 11 has been supported since 2018, after this commit:

https://github.com/konsoletyper/teavm/commit/064888c9a179d07a2973cd258386a50ff893378f

Java 8 bytecode works well too.

**Comment by LAX1DUDE** [comment]
thanks
