### ISSUE TITLE
Double.getNaN() claims to be synchronous but contains asynchronous calls

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#58]
I just ran into a compilation error with Double.getNaN().  It appears that because it is called in the static initializer, it implicitly has a monitor, so it is marked Async by the Async Method finder.  But since it is defined using an Injector, it throws this error.  I have worked around this issue with the following patch:

https://gist.github.com/shannah/fa801cb5ee5a0e7f189d

**Comment by shannah** [comment]
It seems this may be a more general problem with static initializers as I am running into some runtime problems with other classes.   For example, consider the String class static initializer that is generated as follows:

~~~~
[Log] function jl_String6_$clinit() {
    jl_String6_$clinit = function(){};
    jl_String6_$init4108 = function($this, $return) {
        var $part_0 = $rt_guardAsync(function() {
            return jl_Object10_$init21($this, $rt_continue($part_1));
        }, $return);
        var $part_1 = $rt_guardAsync(function($restore) {
            $restore();
            $this.characters4104 = $rt_createCharArray(0);
            return $return($rt_asyncResult());
        }, $return);
        return $part_0();
    };
    jl_String6_$init1997 = function($this, a, b, c, $return) {
        var d;
        var $part_0 = $rt_guardAsync(function() {
            return jl_Object10_$init21($this, $rt_continue($part_1));
        }, $return);
        var $part_1 = $rt_guardAsync(function($restore) {
            $restore();
            $this.characters4104 = $rt_createCharArray(c);
            d = 0;
            while ((d < c)) {
                $this.characters4104.data[d] = a.data[((d + b) | 0)];
                d = ((d + 1) | 0);
            }
            return $return($rt_asyncResult());
        }, $return);
        return $part_0();
    };
    jl_String6_wrap96 = function(a, $return) {
        var $part_0 = $rt_guardAsync(function() {
            return $return($rt_asyncResult(a));
        }, $return);
        return $part_0();
    };
    jl_String6_$init4109 = function($this, a, b, c, $return) {
        var d, e, f, g, h, i;
        var $part_0 = $rt_guardAsync(function() {
            return jl_Object10_$init21($this, $rt_continue($part_1));
        }, $return);
        var $part_1 = $rt_guardAsync(function($restore) {
            $restore();
            $this.characters4104 = $rt_createCharArray(((c * 2) | 0));
            d = 0;
            e = 0;
            while ((e < c)) {
                f = a.data;
                g = ((b + 1) | 0);
                h = f[b];
                if ((h < 65536)) {
                    i = $this.characters4104.data;
                    f = ((d + 1) | 0);
                    i[d] = (h & 65535);
                } else {
                    f = $this.characters4104.data;
                    i = ((d + 1) | 0);
                    f[d] = otcic_UTF16Helper476_highSurrogate477(h);
                    d = $this.characters4104.data;
                    f = ((i + 1) | 0);
                    d[i] = otcic_UTF16Helper476_lowSurrogate481(h);
                }
                e = ((e + 1) | 0);
                b = g;
                d = f;
            }
            if ((d < $this.characters4104.data.length)) {
                $this.characters4104 = ju_Arrays2017_copyOf2016($this.characters4104, d);
            }
            return $return($rt_asyncResult());
        }, $return);
        return $part_0();
    };
    jl_String6_valueOf372 = function(a, $return) {
        var $part_0 = $rt_guardAsync(function() {
            if ((a === null)) {
                return jl_String6_wrap96($rt_s(481), $rt_continue($part_1));
            }
            return a.toString40($rt_continue($part_2));
        }, $return);
        var $part_1 = $rt_guardAsync(function($restore) {
            a = $restore();
            return $return($rt_asyncResult(a));
        }, $return);
        var $part_2 = $rt_guardAsync(function($restore) {
            a = $restore();
            return jl_String6_wrap96(a, $rt_continue($part_3));
        }, $return);
        var $part_3 = $rt_guardAsync(function($restore) {
            a = $restore();
            return $return($rt_asyncResult(a));
        }, $return);
        return $part_0();
    };
    jl_String6_$init4110 = function($this, a, $return) {
        var b, c, d;
        var $part_0 = $rt_guardAsync(function() {
            return jl_Object10_$init21($this, $rt_continue($part_1));
        }, $return);
        var $part_1 = $rt_guardAsync(function($restore) {
            $restore();
            b = a.data;
            c = b.length;
            $this.characters4104 = $rt_createCharArray(c);
            d = 0;
            while ((d < c)) {
                $this.characters4104.data[d] = b[d];
                d = ((d + 1) | 0);
            }
            return $return($rt_asyncResult());
        }, $return);
        return $part_0();
    };
    jl_String6_$clinit4111 = function($return) {
        var a;
        var $part_0 = $rt_guardAsync(function() {
            a = new jl_String$13311();
            return jl_String$13311_$init3781(a, $rt_continue($part_1));
        }, $return);
        var $part_1 = $rt_guardAsync(function($restore) {
            $restore();
            jl_String6.CASE_INSENSITIVE_ORDER4106 = a;
            a = new ju_HashMap977();
            return ju_HashMap977_$init1014(a, $rt_continue($part_2));
        }, $return);
        var $part_2 = $rt_guardAsync(function($restore) {
            $restore();
            jl_String6.pool4107 = a;
            return $return($rt_asyncResult());
        }, $return);
        return $part_0();
    };
    jl_String6_$clinit4111();
}
~~~~

Notice that jl_String6_$clinit4111(); is called right at the end with no arguments, even though this function takes a `$return` argument.

**Comment by konsoletyper** [comment]
May be TeaVM should prohibit user from creating async <clinit>, with giving error when <clinit> tries to call async method? Obviously, you have a problem here with java.lang.Object.<init> method. Why TeaVM made it async? I'll try to figure out these things and provide a general solution.

**Comment by shannah** [comment]
Some more observations.  Platform.nextObjectId() is being generated as async, even though its content is just:

~~~~
public static int nextObjectId() {
        return ((PlatformHelper)JS.getGlobal()).nextId();
    }
~~~~

The AsyncMethodFinder it adding it because it claims it makes a call to String.<init>(char[]), which it also considers to be async.   Perhaps I don't understand exactly how the async generation is supposed to work. It seems as though nearly everything is generated async even if the method clearly is sync (e.g. only returns a value).  Is this how it is supposed to work?

**Comment by konsoletyper** [comment]
The problem of async code is that sometimes least async function makes half of the code async. Consider, you have an asynchronous library function and you want to use it in your own function. Your function becomes asynchronus too. Then, someone else it going to use your function and he has to write an async code too. So does TeaVM. Once it finds `@Async` method, it looks through call graph what methods call this method, and makes them async too. Then, it repeats the same procedure for each of these methods recursively. The possible reason is that TeaVM builds incorrect callgraph. As I mentioned, TeaVM async support is in its very early stage, so every disaster may happen. BWT, notice `@Sync` annotation, which causes error message if you are trying to call async code.

**Comment by shannah** [comment]
Yes.  This is how I thought it works.  I'm debugging the process right now to see if I can figure out why some methods that clearly don't call async code are still being marked as async by the async method finder.

**Comment by shannah** [comment]
OK.  I think I found it.  The AsyncMethodFinder marks all methods who have been overridden by an async method as Async.  This includes constructors.  I think we can safely exclude constructors and class initializers from this list since those can't be called as virtual methods in the same way as normal methods.

**Comment by konsoletyper** [comment]
Wrong, AsyncMethodFinder does not make such assumptions. It only marks methods as in "async family", which causes generation of async-to-sync adapter. TeaVM generates each method as a global function. To emulate virtual calls, it additionaly produces stub method in the prototype of the class. Now consider you call a virtual method, and there are both sync and async overrides. You have to make async call, but you don't need to transform sync override to async. Instead, TeaVM produces special kind of stub.

The real problem is: why does method that must be sync tried to call something async?

**Comment by shannah** [comment]
Here's the code I'm referring to:

~~~~
for (MethodReference overridenMethod : overriden) {
            add(overridenMethod);
        }
~~~~

This directly adds all methods that have been overridden by an async method to the list of async methods.  This is added to the asyncMethods collection, not the asyncFamilyMethods map.

Because of this, Object.<init> is marked as async.  And the cascade effect is that *every* method is marked async.

**Comment by konsoletyper** [comment]
Well, this code might be wrong at all. I'll try to remove it and see what happens. DependencyChecker automatically resolves virtual calls and therefore if there is any chance that callsite might be async, we will know about it from call graph.

**Comment by konsoletyper** [comment]
@shannah if you have an example, please, check if the latest commit in `async` branch fixed this issue
