### ISSUE TITLE
teavm.org unavailable

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#583]
Hi. From the russian-ukrainian war started, teavm site (and artifacts repository) became unavailable.
I suppose that teavm.org is hosted in Russia (checked whois for domain).
Are there any plans to move hosting to other country?

**Comment by konsoletyper** [comment]
Can you contact your local authorities to get explanation why this particular IP/domain/certificate was banned?

**Comment by Ihromant** [comment]
Ukraine

**Comment by Ihromant** [comment]
Maybe will try to build and install it locally.

**Comment by Ihromant** [comment]
Basically Russia closed all access from Ukraine because people in Ukraine DDOSed their state services. So this is the reason. I can access russian hosted sites only via Tor.
Maven central would be great, thanks.

**Comment by PokingUrsa** [comment]
This was mentioned on teavm-site and the mailing list some time ago when corporate firewalls were causing problems: https://github.com/konsoletyper/teavm-site/issues/29

Perhaps github pages is a option?  It's free.  https://pages.github.com/

**Comment by Ihromant** [comment]
@konsoletyper any news or obstacles about releasing 0.7.0 version to maven central?
https://mvnrepository.com/artifact/org.teavm here is only 0.6.1 version which has no fixes I need.
Last release of teavm was 3 years ago.

**Comment by konsoletyper** [comment]
@Ihromant I just forgot how to do that. Tried to use instruction, but seems that I lost my old GPG keys, and I don't know how to update them to the new one (if it's even possible).

**Comment by konsoletyper** [comment]
Ah, I think gnupg just changed for some reason my default key, there were several ones. I changed default key back to that I used for TeaVM and now deployments works.

**Comment by Ihromant** [comment]
@konsoletyper Thank you, with teavm released to maven central, everything works!
