### ISSUE TITLE
Apparently incorrect package name in ZoneRulesBuilder

### ISSUE THREAD

**Issue by dsyer** [konsoletyper/teavm#585]
`ZoneRulesBuilder` has `package org.threeten.bp.zone;` (https://github.com/konsoletyper/teavm/blob/master/tests/src/test/java/org/teavm/classlib/java/time/zone/TestZoneRulesBuilder.java#L47) but that's not consistent with its location in the source tree. Apparently the project still builds (how? maybe `tests` is not part of the build?) but it upsets the IDE, so I can't work comfortably on this project, if I wanted to fix a bug maybe.

**Comment by konsoletyper** [comment]
That's correct location according to [these rules](https://github.com/konsoletyper/teavm/blob/5e37e2a45bb8340cd9f4f2712aa4129145f5222b/classlib/src/main/resources/META-INF/teavm.properties). That was done intentionally to be able to simplify merging changes from threeten repository.

**Comment by dsyer** [comment]
Yikes. That's complicated. I can't think of a way to persuade the IDE to just ignore that though. Oh well. Is it temporary?

**Comment by konsoletyper** [comment]
Ah, I see. Misunderstood your initial question. Now fixed that. Looks like ZoneRulesBuilder was not used anywhere and I simply removed it and tests for it

**Comment by dsyer** [comment]
That's helpful, thanks. Now I'm stuck on a load of non-existent dependencies in `tools/idea` and subdirs. Is that expected ?

**Comment by konsoletyper** [comment]
Yes, it's expected. You should build project with IDEA support using Maven at least once in order to download and generate all necessary dependencies. Another way it to disable `with-idea` profile while importing Maven project.

**Comment by dsyer** [comment]
I built from the command line a few times. Doesn't seem to be a problem, but the errors are still there in the IDE. ALso now seeing

```
The constructor URLDecoder() is not visibleJava(134217859)
```

from `URLDecoderTest`. Am I using the wrong JDK?

**Comment by konsoletyper** [comment]
> The constructor URLDecoder() is not visibleJava

Looks like they removed some old deprecated constructor in newer Java versions. I usually open project using Java 11. I think this particular test can be removed.

> Doesn't seem to be a problem, but the errors are still there in the IDE

What kind of IDE?

**Comment by dsyer** [comment]
> What kind of IDE?

I'm using VSCode (so Eclipse JLS).

**Comment by konsoletyper** [comment]
Have no idea why it shows these problems. Can you show them?

**Comment by dsyer** [comment]
![image](https://user-images.githubusercontent.com/124075/160127666-b3674d8a-dce1-4fab-a2d0-dbce1c40e4e7.png)

Those dependencies are not installed in the local Maven repository. So it's no surprise they are not found. I don't understand how they are supposed to get there. Part of the build in `tools/idea/idea-artifacts`? Doesn't seem to be working.

**Comment by konsoletyper** [comment]
Yes, `teavm-idea-artifacts` prepares these dependencies. IDEA has no problems with that, though in IDEA I can enable/disable profiles manually (and AFAIR `with-idea` profile is not enabled by default in `pom.xml`). So it's a question to authors of VSCode.

**Comment by dsyer** [comment]
Sigh. I give up.
