### ISSUE TITLE
VirtualMethods not linked

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#59]
I have run into a situation where virtual methods are not linked by the Dependency checker if they aren't explicitly called.

e.g.

~~~~
class A {
    public Impl impl;
    String foo(){
        return impl.foo();
    }
}

class Impl {
    String foo(){
        return "some string";
    }
}

class SubImpl extends Impl {
    String foo(){
        return "some other string";
    }
}

A a = new A();
a.impl = new SubImpl();

a.foo();
~~~~

In the following case, the SubImpl::foo() method will not be linked by the dependency checker because it wasn't called explicitly... only its parent is called.

(I haven't tried this specific example... but I've observed this in a more complex app).

**Comment by konsoletyper** [comment]
Please, try to compile **exactly** this code and tell what happened. Do you use direct JavaScript or JSO invocations in your code?

**Comment by shannah** [comment]
OK.   This simple example actually works fine.  Will need to look closer at the real-world app, and see why it's not working.
