### ISSUE TITLE
Presence of .iml files in source

### ISSUE THREAD

**Issue by ulugbekna** [konsoletyper/teavm#597]
Hi, 

I was wondering why we need `.iml` files when we have `.pom` files that should be enough for IJ IDEA to work on the project. 

I'm concerned about their presence because there's mismatch between pom and iml files. For example, pom files indicate that JDK 1.8 needs to be used but `.iml` files specify JDK 1.5-1.7. I haven't looked much into this, please take with a grain of salt 

Thanks!

**Comment by konsoletyper** [comment]
There are only in few modules, right? Somewhere in `tools/idea`. That's because I don't know a way to make IDEA import `pom.xml` as IDEA plugin project.
