### ISSUE TITLE
Type Error undefined function with async branch

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#60]
I just checked out the latest async branch. I ran into a problem with the main() method if using async methods.  The problem is that the main() method has an undefined $return method.

I was able to fix the problem in the index.html file, by simply adding a "null" parameter.

e.g.
change:

~~~~
<body onload="main()">
~~~~

to

~~~~
<body onload="main(null)">
~~~~

**Comment by konsoletyper** [comment]
Just forgot to tell about this in time: I solved this problem. You can just call `main()`, or, if you want to pass parameters, `main(paramsArray)`, where paramsArray is JavaScript array containing JavaScript strings.
