### ISSUE TITLE
Server Error using TeaVM Plugin?

### ISSUE THREAD

**Issue by 1fxe** [konsoletyper/teavm#600]
I am following the getting started documentation and running through IDEA
https://teavm.org/docs/tooling/idea.html

Setup the TeaVM development server go to http://localhost:9090/

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO: Starting build
INFO: Recompiled stale methods: 66
INFO: Build complete successfully
INFO: Compilation took 811 ms
```

![image](https://user-images.githubusercontent.com/37674069/178532598-3af6153d-73b5-4a19-ac5d-69be0a83466d.png)

**Comment by konsoletyper** [comment]
And what's expected to serve `index.html` page? Did you set up proxy to another server?

**Comment by 1fxe** [comment]
> And what's expected to serve `index.html` page? Did you set up proxy to another server?

Ah thanks make sense I changed my cofiguration to run the server after build 
![image](https://user-images.githubusercontent.com/37674069/178560935-c4e6234f-c06d-4486-82ca-f99628d7200a.png)
