### ISSUE TITLE
Custom classlib

### ISSUE THREAD

**Issue by philiptzou** [konsoletyper/teavm#604]
Greetings!

I am using TeaVM to make a [Java-written project](https://github.com/hivdb/asi_interpreter) available to be used by JavaScript. After did my research on many documents and even some part of the source code of TeaVM, I still couldn't find any resource of about how to customize classlib for Java core and/or third party libraries with native functions and methods. Can you provide me some guidance? Or can you point out the document if I overlooked?

Thanks!

**Comment by konsoletyper** [comment]
Hello. You can't customize classlib in TeaVM.
