### ISSUE TITLE
Any thoughts on supporting Clojure language?

### ISSUE THREAD

**Issue by ertugrulcetin** [konsoletyper/teavm#613]
Hi there 👋🏻, 

First of all, thank you for this project. I've looked a bit into the source code and found that you support Kotlin and Scala languages. I was wondering if it is easy to support Clojure as well? 

Because `ScalaHacks` and `KotlinHacks` classes are not that big (could not understand what they do under the hood - checked for supporting Clojure myself).

If you are not considering supporting Clojure, maybe I can check myself. Perhaps you can give me some tips/guidance?

**Comment by konsoletyper** [comment]
I don't think it's possible with TeaVM.

**Comment by ertugrulcetin** [comment]
@konsoletyper Both Scala and Kotlin are supported, is Clojure doing something different with class loading or runtime?

**Comment by ertugrulcetin** [comment]
Also Clojure supports Ahead-of-time Compilation: https://clojure.org/reference/compilation

**Comment by konsoletyper** [comment]
> Both Scala and Kotlin are supported, is Clojure doing something different with class loading or runtime?

Both Scala and Kotlin are statically typed. Clojure is not. And it relies heavily on generation of classes during runtime. *Even* AOT mode AFAIK.

**Comment by ertugrulcetin** [comment]
I see, thank you for the info.
