### ISSUE TITLE
AbstractStringBuilder indexOf() problem

### ISSUE THREAD

**Issue by reportmill** [konsoletyper/teavm#615]
This code seems to fail:

    int index = new StringBuffer("Hello").indexOf("Hello", 0);
    assert (index == 0);

I think the "i < sz" needs to be "i <= sz".

**Comment by ScraM-Team** [comment]
Jeff, do you have the line in the TeaVM source where this change is needed?  It sounds like you've found the exact file/line already.  Is it possible to make a PR for Alexey to merge?

**Comment by reportmill** [comment]
Ah, right, sorry I need to be a better TeaVM citizen. I think the issue is in:

TAbstractStringBuilder.java:indexOf (lines 675 - 686):

```
    public int indexOf(TString str, int fromIndex) {
        int sz = length - str.length();
        outer: for (int i = fromIndex; i < sz; ++i) {
            for (int j = 0; j < str.length(); ++j) {
                if (buffer[i + j] != str.charAt(j)) {
                    continue outer;
                }
            }
            return i;
        }
        return -1;
    }
```

I think if changed to i <= sz, it will fix, otherwise if search str is same length as buffer string, it will erroneously bail.

**Comment by reportmill** [comment]
Thanks Alexey!
