### ISSUE TITLE
Substitutor for bootstrap method [...] was not found

### ISSUE THREAD

**Issue by DevTaube** [konsoletyper/teavm#624]
When compiling, I am receiving this error message:
```
ERROR: <!> Substitutor for bootstrap method java.lang.invoke.LambdaMetafactory.metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; was not found
    at java.lang.String.<clinit>(TString.java:36)
    at java.lang.String.<init>
    at java.lang.Class.getClass(TClass.java:76)
    at java.lang.Object.getClass(TObject.java:221)
    at java.lang.Object.toString(TObject.java:241)
    at java.lang.Object.toString(TObject.java:241)
    at java.lang.Object.toString(TObject.java:241)
    at java.lang.Object.toString(TObject.java:241)
    at java.lang.Object.toString(TObject.java:241)
    at java.lang.Object.toString(TObject.java:241)
    ...
```
From looking at other issues, I noticed that this error message occurred when not having `teavm-classlib-<version>.jar` in the dependencies (for maven). Sadly I am not using maven, so I have been trying to look for a solution on my own, without luck.
I wrote my own compiler class (looking at the source code of `teavm-cli` when I was stuck) that is compiled to a jar file together with the following jar files:
```
gson-2.8.6.jar
joda-convert-1.2.jar
joda-time-2.7.jar
jzlib-1.1.3.jar
teavm-classlib-0.7.0.jar
teavm-core-0.7.0.jar
teavm-interop-0.7.0.jar
teavm-jso-0.7.0.jar
teavm-jso-apis-0.7.0.jar
teavm-jso-impl-0.7.0.jar
teavm-metaprogramming-api-0.7.0.jar
teavm-metaprogramming-impl-0.7.0.jar
teavm-platform-0.7.0.jar
teavm-tooling-0.7.0.jar
```
As you can see, `classlib` is included in the libraries and also in the final jar file that gets executed.
What do I have to change to make this work?
Do I have to load the classlib jar as project source?
Or do I maybe have to add the classlib-jar to `TeaVMTool`?
Looking at the maven plugin source code or the cli source code didn't really help answering these questions...
I will try adding it as a `JarSourceFileProvider` and keep you updated.

Edit: adding `teavm-classlib-0.7.0.jar` doesn't seem to solve anything...

**Comment by konsoletyper** [comment]
This is *definitely* an issue with `teavm-classlib` not available in the classpath, it has nothing to do with Maven specifics. Without knowing your exact setup I can't tell anything, you should either share it or debug yourself. You can start by putting breakpoint in `TeaVM.installPlugins` method. Is it called at all? If it is, how does it look for JCLPlugin and why it fails to do it?

**Comment by DevTaube** [comment]
I got it working! finally! It finally worked by not using a .jar file, but instead just using IntellIJ to run it. I've set the classloader correctly and set a main class, and now everything works as intended. Thank you for creating TeaVM and taking you time to help me.
