### ISSUE TITLE
Is it possible to decompile classes.js back to java?

### ISSUE THREAD

**Issue by Hellscap3d** [konsoletyper/teavm#642]
I'm attempting to get the source of a teavm compiled program, but I can't find a method of decompiling. Is this possible?

**Comment by shannah** [comment]
I'm not aware of any tools that do this.  This may not be possible as teavm compiled code includes many transformations to handle async code and other optimizations.  It is a much harder problem than, for example, bytecode decompilation.

Making the compiled js easily decompilable is also undesirable to most developers.  In fact, the harder it is to decompile, the better.

**Comment by konsoletyper** [comment]
No, it's not possible. As well, as it's not possible in general case to decompile machine code back to Go or Rust.
