### ISSUE TITLE
Error when using Async methods in static initializer

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#65]
If I call an async method in the static initializer, I get errors.  

The following works fine:

~~~~
public final class StaticInitTest {
    private static StaticInitTest instance;
    
    private StaticInitTest() {
        try {
            Thread.sleep(1);
        } catch (Throwable t){
            throw new RuntimeException(t);
        }
    }
    
    public static StaticInitTest getInstance(){
        if (instance == null){
            instance = new StaticInitTest();
        }
        return instance;
    }
    
    public void printStatus(){
        System.out.println("StaticInitTest is alive");
    }
}

...

StaticInitTest test = StaticInitTest.getInstance();
test.printStatus();

~~~

But this does not:

~~~~
public final class StaticInitTest {
    private static StaticInitTest instance = new StaticInitTest();
    
    private StaticInitTest() {
        try {
            Thread.sleep(1);
        } catch (Throwable t){
            throw new RuntimeException(t);
        }
    }
    
    public static StaticInitTest getInstance(){
        return instance;
    }
    
    public void printStatus(){
        System.out.println("StaticInitTest is alive");
    }
}

...

StaticInitTest test = StaticInitTest.getInstance();
test.printStatus();
~~~~

I get the error:

~~~~
[Error] TypeError: undefined is not a function (evaluating 'continuation($rt_asyncError(e))')
	(anonymous function) (runtime.js, line 542)
	(anonymous function) (runtime.js, line 542)
	complete164 (classes.js, line 1170)
	jl_Thread$244_onTimer270 (classes.js, line 912)
	(anonymous function) (classes.js, line 2844)
	(anonymous function) (classes.js, line 1123)
~~~~

The generated clinit in this case is:

~~~~
function otsa_StaticInitTest127_$clinit() {
    otsa_StaticInitTest127_$clinit = function() {};
    otsa_StaticInitTest127_$clinit359 = function($return) {
        var a;
        var $part_0 = $rt_guardAsync(function() {
            a = new otsa_StaticInitTest127;
            return otsa_StaticInitTest127_$init361(a, $rt_continue($part_1));
        }, $return);
        var $part_1 = $rt_guardAsync(function($restore) {
            $restore();
            otsa_StaticInitTest127.instance128 = a;
            return $return($rt_asyncResult());
        }, $return);
        return $part_0();
    };
    otsa_StaticInitTest127_$init361 = function($this, $return) {
        var a, $je;
        var $part_0 = $rt_guardAsync(function() {
            jl_Object6_$init160($this);
            try {
                return jl_Thread10_sleep297(Long_fromInt(1), $rt_continue($part_1));
            } catch ($e) {
                $je = $e.$javaException;
                if ($je && $je instanceof jl_Throwable17) {
                    a = $je;
                } else {
                    throw $e;
                }
            }
            $rt_throw(jl_RuntimeException23_$init226(a));
        }, $return);
        var $part_1 = $rt_guardAsync(function($restore) {
            $ba: {
                try {
                    $restore();
                } catch ($e) {
                    $je = $e.$javaException;
                    if ($je && $je instanceof jl_Throwable17) {
                        a = $je;
                        break $ba;
                    } else {
                        throw $e;
                    }
                }
                return $return($rt_asyncResult());
            }
            $rt_throw(jl_RuntimeException23_$init226(a));
        }, $return);
        return $part_0();
    };
    otsa_StaticInitTest127_getInstance363 = function($return) {
        var $part_0 = $rt_guardAsync(function() {
            return $return($rt_asyncResult(otsa_StaticInitTest127.instance128));
        }, $return);
        return $part_0();
    };
    otsa_StaticInitTest127_$clinit359();
}
~~~~

**Comment by konsoletyper** [comment]
Are you sure it is really necessary? I'm afraid, support of async code in static initializer is quite hard to implement, and is very rarely needed. So it might be better just to explicitly prohibit async <clinit> methods.

**Comment by shannah** [comment]
A compile-time error would be sufficient, if implementation would be difficult to achieve.
