### ISSUE TITLE
Teavm 0.7.0-dev-1210 plugin is not working

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#652]
Obtaining error during build with newest dev:
```
[ERROR] Failed to parse plugin descriptor for org.teavm:teavm-maven-plugin:0.7.0-dev-1210 (/home/ihromant/.m2/repository/org/teavm/teavm-maven-plugin/0.7.0-dev-1210/teavm-maven-plugin-0.7.0-dev-1210.jar): No plugin descriptor found at META-INF/maven/plugin.xml -> [Help 1]
```

**Comment by konsoletyper** [comment]
Fixed in `0.7.0-dev-1211`. Also, you can try new Gradle plugin.

**Comment by Ihromant** [comment]
@konsoletyper replaced 1209 to 1211, not build just goes to infinite loop when I'm building. Rolled back to 1209, build successfully finished. Can't reveal sources of the project again unfortunately.

**Comment by Ihromant** [comment]
I can show it on video call if needed. On simple project build works, on bigger it goes to infinite loop. The only change I'm doing is increasing teavm.version variable in maven.

**Comment by konsoletyper** [comment]
Videos usually don't help. You should find a way to reveal the source code (at least to me personally), to create a simple self-contained project that reproduces the issue or to debug this issue yourself.

**Comment by Ihromant** [comment]
Added you to one of the repositories as collaborator. Try to build head of master with 1209, then replace it to 1211

**Comment by Ihromant** [comment]
Fixed issue mentioned above. Thanks for your support. Cause was really ```Class.forName``` used in deserializer.
