### ISSUE TITLE
Reference Error: Can't find variable: otpp_ResourceAccessor1288_$init3779

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#66]
I'm working through quite a complex library that I'm trying to compile so I don't have a simple test case for this one yet.  The stack traces aren't too helpful here either... I can provide more information if you direct me as to what you need to know to fix this.

~~~~
[Error] ReferenceError: Can't find variable: otpp_ResourceAccessor1288_$init3779
	(anonymous function) (runtime.js, line 459)
	(anonymous function) (runtime.js, line 493)
	(anonymous function) (runtime.js, line 542)
	(anonymous function) (runtime.js, line 542)
	(anonymous function) (runtime.js, line 542)
	(anonymous function) (runtime.js, line 542)
	(anonymous function) (runtime.js, line 542)
	(anonymous function) (runtime.js, line 542)
	(anonymous function) (runtime.js, line 542)
	(anonymous function) (runtime.js, line 530)
~~~~

**Comment by konsoletyper** [comment]
I don't know how could you help me to find a problem as well. Can you provide me the code? Here is a little hint: use JavaScript debugger and select "pause on caught exceptions"

**Comment by shannah** [comment]
By JavaScript debugger, are you referring to the Eclipse debugger stuff you did, or just Chrome's debugger?  I haven't tried with Eclipse yet.  Just using Chrome and Safari.

**Comment by shannah** [comment]
Nevermind.  Found it in Chrome.  Will post more shortly.

**Comment by shannah** [comment]
Here is the generated Javascript code.
https://gist.githubusercontent.com/shannah/5c63f68bfd157212acd1/raw/classes.js

It was generated more or less from the Codename One sources.
https://code.google.com/p/codenameone/source/checkout  (if you're looking to see java class equivalents).

Still working through the exceptions and stack trace to look for clues.

**Comment by shannah** [comment]
Here is the cluprit line.  It is referencing a constructor that wasn't generated.

![screen shot 2015-02-19 at 11 45 58 am](https://cloud.githubusercontent.com/assets/2677562/6274516/f986d386-b82c-11e4-996b-81f01a43e8d8.png)

**Comment by konsoletyper** [comment]
I had some issues with Class.newInstance. It is impossible with current architecture to implement it properly, since I don't track actual values of Class. I think I'll include it as soon as I finish with async branch. For now I'll try to find workaround.

Here is a little hint for you: if you launch TeaVM compiler with `-Dorg.teavm.logDependencies=true` option, you'll get huge amount of debugging information about dependency checking phase. I sometimes use these logs when I encounter bug there.

**Comment by shannah** [comment]
Likely this is due to the fact that the ResourceAccessor class has a private constructor.  And it is never called (because all methods on the class are static ... and native).

I'm narrowing it down to this section of PlatformGenerator:

~~~
for (String clsName : context.getClassSource().getClassNames()) {
            ClassReader cls = context.getClassSource().get(clsName);
            MethodReader method = cls.getMethod(new MethodDescriptor("<init>", void.class));
            if (method != null) {
                writer.appendClass(clsName).append("[c]").ws().append("=").ws()
                        .append(writer.getNaming().getNameForInit(method.getReference()))
                        .append(";").softNewLine();
            }
        }
~~~

(lines 94-101).

I'm not sure yet what the purpose of these constructor references is, so I'm not sure if I can just skip private constructors in this altogether, or it I need to be explicitly adding dependencies to the constructors, or if I need to skip them based on other factors.

**Comment by shannah** [comment]
A simple workaround for now would be to change the assigments to something like:

~~~
otpp_ResourceAccessor1288[c] = window.otpp_ResourceAccessor1288_$init3779;
~~~

Instead of just

~~~
otpp_ResourceAccessor1288[c] = otpp_ResourceAccessor1288_$init3779;
~~~

As this wouldn't throw an exception... it would just set the value to undefined.

**Comment by konsoletyper** [comment]
The problem was: I made all methods of ResourceAccessor class to be injectable. It means that their body are not generated, by rather special object, named Injector, is called to render method invocation. Of course, constructor, even if it is empty, must be generated. I just made exception for <init> method in class processor, and everyting began to work.
