### ISSUE TITLE
Can't build lastest

### ISSUE THREAD

**Issue by jmccay-work** [konsoletyper/teavm#661]
I haven't been able to build this project.

`Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: publishToLocalMaven

FAILURE: Build failed with an exception.

* Where:
Settings file '/mnt/c/github/wasm/teavm/teavm/settings.gradle.kts' line: 25

* What went wrong:
Plugin [id: 'dependency-relocation'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/6.8.2/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (plugin dependency must include a version number for this source)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s`

**Comment by konsoletyper** [comment]
Build works for me. What you are doing exactly to get this message?

**Comment by Ihromant** [comment]
Have different issue when building:
```
gradle publishToMavenLocal
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by konsoletyper** [comment]
@Ihromant you should use `gradlew` instead of `gradle`

**Comment by Ihromant** [comment]
Now it works, thanks.
