### ISSUE TITLE
Stack traces for Async

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#67]
Debugging issues in Async is currently a little painful.  You end up with long stack traces of $rt_guardAsync(), etc.. calls with some possibly helpful listings from classes.js intermixed.  I would like to add a debug mode that would maintain its own java stack traces.  Conceptually it should suffice to just add a map of threadId->stack.  And upon entering a method, it just adds a line to the stack recording the file name and line number - and existing the method it pops the item from the stack for the current thread.

Is there already a similar mechanism built in?  Or can you suggest some tips to make debugging easier?

**Comment by konsoletyper** [comment]
I made more verbose logging of exceptions. May it help you?

**Comment by shannah** [comment]
Yes.  This makes it much easier.  Thanks!
