### ISSUE TITLE
Issues and pull requests cleanup

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#670]
It would be great to clean up outdated issues and pull requests.
In pull requests recent requests are created by bots, some pull requests are abandoned and some are done in scope of other pull requests.
In issues important issues are shadowed by already fixed or resolved, but not closed.
If you @konsoletyper don't want to deal with them, I can do that, but I need permission to do that. Here we can agree on what and how should be closed.

**Comment by konsoletyper** [comment]
> In pull requests recent requests are created by bots, some pull requests are abandoned and some are done in scope of other pull requests.
> In issues important issues are shadowed by already fixed or resolved, but not closed.

And I don't see any problems in this.

**Comment by Ihromant** [comment]
Ok then.
