### ISSUE TITLE
Questions about using Jackson

### ISSUE THREAD

**Issue by virajsanghvi** [konsoletyper/teavm#673]
Just to check my understanding, libraries like Jackson databind are usable if a ReflectionSupplier implementation is provided, correct?

If so, I am running into two problems:
1. ConcurrentHashMap is undefined (saw open issue/pr) - is there a way of defining an alternate implementation of a class that doesn't exist?
2. When including a call to ObjectMapper#readValue, I get the following. Any pointers on how to trace where this is being called from would be great. Trying to see if there's anything I can do to prevent it from going down this path as I don't think it should be necessary.

```
Error optimizing program for method com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(Ljava/net/URI;)Ljava/nio/file/FileSystem;:
var @this as this // 0
var @uri as uri // 1
var @zipfs as zipfs // 3
$0
    goto $1
$1
  at 'com/sun/nio/zipfs/ZipFileSystemProvider.java' 163
    nop
    @2 := field com.sun.nio.zipfs.ZipFileSystemProvider.filesystems @this as `Ljava/util/Map;`
    monitorEnter @2
  at unknown location
    @21 := nullCheck @2
    goto $8
$2
    @12 := phi @14 from $7
  at 'com/sun/nio/zipfs/ZipFileSystemProvider.java' 170
    if @12 !== null then goto $3 else goto $4
    catch  goto $5
$3
  at 'com/sun/nio/zipfs/ZipFileSystemProvider.java' 172
    monitorExit @2
  at unknown location
    goto $9
    catch  goto $5
$4
  at 'com/sun/nio/zipfs/ZipFileSystemProvider.java' 171
    @15 := new java.lang.NoClassDefFoundError
    @16 := 'Class not found: java.nio.file.FileSystemNotFoundException'
    invoke `java.lang.NoClassDefFoundError.<init>(Ljava/lang/String;)V` @15, @16
    throw @15
    catch  goto $5
$5
    @4 := exception
  at 'com/sun/nio/zipfs/ZipFileSystemProvider.java' 173
    monitorExit @21
    throw @4
$6
  at 'com/sun/nio/zipfs/ZipFileSystemProvider.java' 166
    nop
    @5 := field com.sun.nio.zipfs.ZipFileSystemProvider.filesystems @this as `Ljava/util/Map;`
    @6 := invokeVirtual `com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(Ljava/net/URI;)Ljava/nio/file/Path;` @this, @uri
    @7 := 0
    @17 := new java.lang.NoClassDefFoundError
    @18 := 'Class not found: java.nio.file.LinkOption'
    invoke `java.lang.NoClassDefFoundError.<init>(Ljava/lang/String;)V` @17, @18
    throw @17
    catch java.io.IOException goto $7
    catch  goto $5
$7
    @14 := phi @zipfs from $6, @11 from $6
  at 'com/sun/nio/zipfs/ZipFileSystemProvider.java' 166
    goto $2
    catch  goto $5
$8
  at 'com/sun/nio/zipfs/ZipFileSystemProvider.java' 164
    @zipfs := null
  at unknown location
    goto $6
    catch  goto $5
$9
  at 'com/sun/nio/zipfs/ZipFileSystemProvider.java' 172
    return @12
```

**Comment by konsoletyper** [comment]
TeaVM does not support Jackson and is not meant to do it. You should prefer any other library for JSON deserlialization that does not rely on reflection. As for this error: what TeaVM version are you using? How did you run TeaVM? Was there any stack trace? Anyway, here I see that TeaVM was going to report some problem gracefully (e.g. the lack of `java.nio.file.FileSystemNotFoundException`), but crashed for some reason. TeaVM only support subset of Java class library, as described [here](https://teavm.org/docs/runtime/java-classes.html) and [here](https://teavm.org/jcl-report/recent/jcl.html)

**Comment by virajsanghvi** [comment]
I was using 0.7.0 and running with maven (`maven clean package`). There was no stack trace. 

Closing as I don't need a resolution to this and might just be due to using Jackson.
