### ISSUE TITLE
location.hash

### ISSUE THREAD

**Issue by ambahk** [konsoletyper/teavm#68]
Is there any way to expose location.hash to java so that we can do client side routing?  passing in thru the main method doesn't seem to work.  i.e. <body onLoad="main(location.hash)">

Thanks!

**Comment by konsoletyper** [comment]
What do you mean for location?

**Comment by ambahk** [comment]
I was looking for ways for the single-page-app to render according to window.location.hash.  It would be nice to get the back button working too, such as that supported by http://backbonejs.org/#History.  Do you have any suggestions?  Thanks.

**Comment by konsoletyper** [comment]
You can use any existing JavaScript APIs throgh [JSO](https://github.com/konsoletyper/teavm/wiki/Interacting-with-JavaScript). Just write your own wrappes for functions you need. If you need examples, learn the [teavm-dom](https://github.com/konsoletyper/teavm/tree/master/teavm-dom) project.

**Comment by ambahk** [comment]
Ah OK.  I have read the docs before but wasn't sure that it was the way to go since it look a bit too easy... the following code snippet works.

BTW is there a better way to get the global variable or is this **(MyWindow) JS.getGlobal()** way the recommended approach?

```
public class Client {
	public static void main(final String... args) {
		final MyWindow window = (MyWindow) JS.getGlobal();
		System.out.println(window.getLocation().getHash());
    }
}

public interface MyWindow extends JSObject {

	@JSProperty
	public Location getLocation();
}

public interface Location extends JSObject {

	@JSProperty
	public String getHash();
}
```

**Comment by konsoletyper** [comment]
I can't answer your question until I understand what do you mean for "better way".

**Comment by ambahk** [comment]
I mean what's the recommended way for getting a global javascript object, such as this location object.  Maybe **JS.get(JS.getGlobal(), JS.wrap("location"))** ?  Or maybe there's a function somewhere that's as convenient as **getGlobalObject("location")** or **expr("window.location")**?  Just want to make sure that I don't miss the good stuffs.

**Comment by konsoletyper** [comment]
No, there is no alternative ways. But, of course, you can create and use your own helper methods, if you think they are more convenient.
