### ISSUE TITLE
Java 17 CharSequence.isEmpty() is not supported in TeaVM

### ISSUE THREAD

**Issue by neckbosov** [konsoletyper/teavm#682]
When I try to use `CharSequence.isEmpty()` in TeaVM I get following error `ERROR: Method java.lang.CharSequence.isEmpty()Z was not found`
TeaVM version 0.7.0-dev-1204. 
Is there support for this method and, in general, complete support of Java 17 in newer versions?

**Comment by Ihromant** [comment]
Welcome here.
List of supported methods you can find here
https://www.teavm.org/jcl-report/recent/jcl.html
As TeaVM is open source, you can add implementation for missing Java methods or browser API like in this pull request like I did just now:
https://github.com/konsoletyper/teavm/pull/683
In 0.9.0-dev-3 it will be present after PR merge.

**Comment by konsoletyper** [comment]
> TeaVM version 0.7.0-dev-1204.

Why don't you migrate to the recent one?

> Is there support for this method and, in general, complete support of Java 17 in newer versions?

There's no even complete support of Java 8 standard library. Only Java 17 bytecode is supported.
