### ISSUE TITLE
JVM 8 lambda support would be really nice!

### ISSUE THREAD

**Issue by ambahk** [konsoletyper/teavm#69]
best wishes!

**Comment by konsoletyper** [comment]
I suggest using [Retrolambda](https://github.com/orfjackal/retrolambda) for this purpose.

**Comment by ambahk** [comment]
The Retrolambda maven plugin works, except that the eclipse TeaVM Builder keeps having build errors.  Probably due to the execution sequence.

Here's the modifications to pom.xml that worked:

```
	  	<!-- Backport lambda expression to JVM 7-->
			<plugin>
				<groupId>net.orfjackal.retrolambda</groupId>
				<artifactId>retrolambda-maven-plugin</artifactId>
				<version>1.8.1</version>
				<executions>
					<execution>
						<id>retrolambda</id>
						<goals>
							<goal>process-main</goal>
							<goal>process-test</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

Need to add the following to remove Eclipse's complaint about **maven plugin execution not covered by lifecycle configuration**
```
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId> net.orfjackal.retrolambda </groupId>
										<artifactId> retrolambda-maven-plugin </artifactId>
										<versionRange> [1.8.1,) </versionRange>
										<goals>
											<goal>process-main</goal>
											<goal>process-test</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<execute>
											<runOnIncremental>true</runOnIncremental>
										</execute>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
```

**Comment by konsoletyper** [comment]
This configuration works for me: http://pastebin.com/EcWAUwxx

**Comment by ambahk** [comment]
In my case I finally removed the eclipse TeaVM builder plugin and retrolambda is now working silently.  Thanks man.

**Comment by konsoletyper** [comment]
You can set up both TeaVM Eclipse plugin and Retrolambda. For explanations, read [this article](https://wiki.eclipse.org/M2E_compatible_maven_plugins). Unfortunately, I can't help you with the exact configuration, because I am in active development of async branch an I have mess inside my workspace. So you can try yourself.

**Comment by ambahk** [comment]
You have given me a lot of help already.  Thank you very much :)
