### ISSUE TITLE
How to compile Pixelitor to JavaScript?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [konsoletyper/teavm#693]
https://github.com/lbalazscs/Pixelitor

**Comment by 2dpdlja496or43iq** [comment]
> Sorry, I can't answer your question

Why?

**Comment by konsoletyper** [comment]
Because I don't know the answer

**Comment by 2dpdlja496or43iq** [comment]
> Because I don't know the answer

So TeaVM doesn't support compiling of Java graphical application to JavaScript?

**Comment by konsoletyper** [comment]
This depends on what you call "Java graphical application". If you mean Swing or JavaFX, yes, TeaVM does not support them.

**Comment by 2dpdlja496or43iq** [comment]
> This depends on what you call "Java graphical application". If you mean Swing or JavaFX, yes, TeaVM does not support them.

Both JEdit and Pixelitor are Java Swing application.
