### ISSUE TITLE
How to compile JEdit to JavaScript?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [konsoletyper/teavm#694]

**Comment by konsoletyper** [comment]
TeaVM site [clearly states](https://teavm.org/docs/runtime/java-classes.html) limitations of the tool. This includes the absence of Java library classes. The list of supported APIs is available [here](https://teavm.org/jcl-report/recent/jcl.html), and it does not mention JEdit class for now. So the answer to you question is: you can't compile JEdit with TeaVM.

**Comment by konsoletyper** [comment]
Ok, I just thought that it's one of Swing classes. Anyway, I can't answer this question, since I don't know the answer.
