### ISSUE TITLE
style.setPropertyValue is not a function

### ISSUE THREAD

**Issue by pizzadox9999** [konsoletyper/teavm#695]
Hi, 
I don't know what I did wrong, but non the less I would like to seek some help.

Down below is the code which procudeced the error in Firefox 112.0.1 (64-Bit Windows 10 22H2).
I'm using Eclipse Version: 2023-03 (4.27.0) Build id: 20230309-1520 and the maven compiler plugin 3.1. I use "clean package" in the eclipse maven run configuration to run it.
Also I am using the teavm "example" project. I tried the following version of teavm: 0.8.1, 0.7.0 and 0.6.1. All produced the described error.
```
package org.mss;

import org.teavm.jso.dom.html.HTMLDocument;
import org.teavm.jso.dom.html.HTMLElement;

public class MemberStatisticService {
	public static void main(String[] args) {
		HTMLElement test = HTMLDocument.current().createElement("button");
		HTMLDocument.current().getBody().appendChild(test);
		test.setInnerHTML("test");
		test.getStyle().setPropertyValue("background-color", "black");
		
	}
}
```
Best regards pizzadox9999

PS: I looked in Edge, Firefox and Internet Explorer and no one had the setPropertyValue function avaiable on their style attribute document.body.style.

**Comment by konsoletyper** [comment]
Use `setProperty` instead
