### ISSUE TITLE
Missing source file

### ISSUE THREAD

**Issue by pizzadox9999** [konsoletyper/teavm#700]
Hi, 

teavm writes in the info log that it is missing source files (quite a lot). But compiles and writes sourcefiles successfully. The thing is I am linking to 2 other local maven repositories. Is it possible to configure maven to include those source files from other locations on my harddrive or change the linked maven projects to provide source maps?

Best regards pizzadox9999

**Comment by konsoletyper** [comment]
Hello. It's not possible. If you have a multi-module project, you need to attach source artifacts for each module, see [documentation](https://maven.apache.org/plugins/maven-source-plugin/usage.html). You can copy source files manually, or you can use [TeaVM plugin](https://teavm.org/docs/tooling/idea.html) for IDEA to run dev server, which serves source files properly. Or you can try to find a way to tell your browser's dev tools to pick sources from specific FS location.
