### ISSUE TITLE
Not able to invoke a method from a third part library.

### ISSUE THREAD

**Issue by thegeek-dev** [konsoletyper/teavm#701]
Hi,
I tried to include a java library org.worldcubeassociation.tnoodle.scrambles.Puzzle and tried to invoke a method of abstract class Puzzle, I got an error while building the wasm. The error I am getting is: Failed to execute goal org.teavm:teavm-maven-plugin:0.5.1:compile (hello) on project UpcubeScrambler: Unexpected error occured: Cannot invoke "org.teavm.model.MethodReader.getAnnotations()" because "method" is null -> [Help 1]
I tried to search for a solution but couldn't get any.

I don't work with Java much. I need to implement this functionality in frontend itself, but Tnoodle(library) is only available in java.
Please help me here.

**Comment by konsoletyper** [comment]
I can't help you, unless you provide more information about your setup. Also, where did you get build instructions? 0.5.1 is pretty old.

**Comment by konsoletyper** [comment]
I found your question on SO and created a simple test here: https://github.com/konsoletyper/tnoodle-example

**Comment by thegeek-dev** [comment]
Thanks a lot for it. I really appreciate your help.

I am now using the .js build and able to call JavaScript functions from Java using @JSBody, however I still couldn't get how to call Java functions from JavaScript. I checked the official documentation, did not find it very useful. Again Thanks a lot.
