### ISSUE TITLE
Implementation of java.util.concurrent with Doug Lea's public domain sources

### ISSUE THREAD

**Issue by siepkes** [konsoletyper/teavm#710]
This might be common knowledge to people in the project but I thought to bring it up just to be sure.

The classes, interfaces, etc. under `java.util.concurrent` are maintained by Doug Lea and licensed as public domain (or better said: "put in the public domain") on his [site](https://gee.cs.oswego.edu/dl/concurrency-interest/). You can view the sources [here](https://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/jsr166/src/main/java/util/concurrent/). There is also a repository which contains a backport to Java 8 [here](https://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/jsr166/src/jdk8/java/util/concurrent/).

Now since these are all put in the public domain they could be re-used by TeaVM in the class library without any licensing issues.

On the surface it seems like it might be possible to get the TeaVM `java.util.concurrent` class library complete with these sources. Or am I over simplifying this? Would there be substantial rework required to make them compatible with TeaVM?

**Comment by konsoletyper** [comment]
Yes, it's a bit oversimplification. TeaVM does not support fair threads, instead it emulates threads with cooperative coroutines on single physical thread. So slightly different approaches should be used here. Another thing is: TeaVM focuses on producing small 'binaries', so it has to deal with 'async pollution' effect and all concurrent code must be written with this in mind. I think that some of Doug Lea code can be re-used with slight modification, however, it should be carefully reviewed and modified to apply to TeaVM.
