### ISSUE TITLE
Cannot call toString on JsArray

### ISSUE THREAD

**Issue by ccadete** [konsoletyper/teavm#72]
Then calling the toString method on JSArray:
```
public static void main(String[] args) {
    JSGlobal global = ((JSGlobal) JS.getGlobal());

    JSArray<JSObject> array = global.newArray();
    System.out.println(array.toString());
}
```
Result in `Uncaught TypeError: undefined is not a function`.

The same error appear in other instances of classes that implement JSObject.

**Comment by konsoletyper** [comment]
It is not an issue, but restriction. You can't call Object methods on JSObject instances.

**Comment by ccadete** [comment]
Since it is a restriction, could it be verified at compile time with an error message? For example, then a class is marked as JSObject, TeaVM could issue an error if any Object method is called.

**Comment by konsoletyper** [comment]
It can be verified at compile time only in certain cases. Consider the following example:

```java
void foo(Object obj) {
    System.out.printlln(obj);
}

...

foo(JS.getGlobal());
```

How can TeaVM predict this?

**Comment by ccadete** [comment]
Could it be possible, that the call to `JS.getGlobal()` return a proxy of the returned instance, with an overrided Object methods throwing an exception?

**Comment by konsoletyper** [comment]
No
