### ISSUE TITLE
Error converting Object to Byte Array

### ISSUE THREAD

**Issue by JessePinkman27** [konsoletyper/teavm#723]
Here is my code:

```java
public static byte[] getBytesFromObject(Object obj) {
    String string = JSON.stringify((JSObject)obj);
    byte[] data = string.getBytes();
}

public static Object getObjectFromBytes(byte[] data) {
    String string = new String(data);
    Object obj = JSON.parse(string);
    return obj;
}
```

and this is the output in the console:
```
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '$array' -> object with constructor 'Object'
    |     property '$meta' -> object with constructor 'Object'
    --- property 'item' closes the circle
    at JSON.stringify (<anonymous>)
```

Am I doing this right? If not then how would I go about converting an Object to a byte array and the byte array back into an Object?

**Comment by konsoletyper** [comment]
You should avoid direct casting of non-JS objects to `JSObject`.

If you want to stringify JS, please, pass JS objects to `JSON.stringify`, e.g. something like this:

```java
JSMapLike<JSObject> json = JSObjects.create();
json.set("foo", JSNumber.valueOf(23));
json.set("bar", JSString.valueOf("hello"));
System.out.println(JSON.stringify(json));
```

**Comment by JessePinkman27** [comment]
> You should avoid direct casting of non-JS objects to `JSObject`.
> 
> If you want to stringify JS, please, pass JS objects to `JSON.stringify`, e.g. something like this:
> 
> ```java
> JSMapLike<JSObject> json = JSObjects.create();
> json.set("foo", JSNumber.valueOf(23));
> json.set("bar", JSString.valueOf("hello"));
> System.out.println(JSON.stringify(json));
> ```

Okay, thank you! How would I go about converting a Java class into a Byte Array?
For example:
```java
TestClass test = new TestClass();
Object obj = (Object)test;

public class TestClass {
    //...
}
```

**Comment by konsoletyper** [comment]
> How would I go about converting a Java class into a Byte Array?

What do you mean?

**Comment by JessePinkman27** [comment]
> > How would I go about converting a Java class into a Byte Array?
> 
> What do you mean?

Like this https://www.baeldung.com/object-to-byte-array
On this tutorial they have a class called "User" and they convert it to a byte array using ObjectOutputStream

**Comment by JessePinkman27** [comment]
> You should avoid direct casting of non-JS objects to `JSObject`.
> 
> If you want to stringify JS, please, pass JS objects to `JSON.stringify`, e.g. something like this:
> 
> ```java
> JSMapLike<JSObject> json = JSObjects.create();
> json.set("foo", JSNumber.valueOf(23));
> json.set("bar", JSString.valueOf("hello"));
> System.out.println(JSON.stringify(json));
> ```

How would I parse and retrieve objects from JSON?

**Comment by konsoletyper** [comment]
@JessePinkman27 there's no way to serialize and deserialize Java objects to/from JSON. Jackson won't work with TeaVM. You should either construct JS objects via [JS interaction layer](https://teavm.org/docs/runtime/jso.html) or write a library that acts like Jackson, but relies on code generation (perhaps, annotation processors) rather than reflection.
