### ISSUE TITLE
Record field accessor functions not transpiled

### ISSUE THREAD

**Issue by ianmjackson** [konsoletyper/teavm#724]
Many thanks for all your great work on TeaVM.

I am trying to make use of Java 17 Records with TeaVM 0.8.1, as per commit [f0d805f](https://github.com/konsoletyper/teavm/commit/f0d805fda81ca5bbeacddda6d5cae10ec1dc942f).

I don't seem to be able to access the fields of the record, either via the implict record accessor or by providing an explicitly defined accessor method.

`java.lang.RuntimeException: (JavaScript) ReferenceError: cepus_ColumnDefinition_field is not defined`

From ColumnDefiniton.java (additional fields omitted for brevity):
```java
public record ColumnDefinition(
    String field,
    ...
) {}
```

From classes.js:
```javascript
var jl_Record = $rt_classWithoutFields();
function jl_Record__init_($this) {
    jl_Object__init_0($this);
}
function cepus_ColumnDefinition() {
    var a = this; jl_Record.call(a);
    a.$field0 = null;
    ...
}
function cepus_ColumnDefinition__init_(var_0, ...) {
    var var_14 = new cepus_ColumnDefinition();
    cepus_ColumnDefinition__init_0(var_14, var_0, ...);
    return var_14;
}
function cepus_ColumnDefinition__init_0($this, $field, ...) {
    jl_Record__init_($this);
    $this.$field0 = $field;
    ...
}

// The function cepus_ColumnDefinition_field does not exist in classes.js but it is called several times, as below:
cepus_ColumnDefinition_field($obj)
```

We are building with Apache Ant + Ivy using the following dependencies:
```xml
<!DOCTYPE ivy-module [
    <!ENTITY teavm.version "0.8.1">
]>
<dependency conf="tea-deps->default" org="org.teavm" name="teavm-classlib" rev="&teavm.version;"/>
<dependency conf="tea-deps->default" org="org.teavm" name="teavm-jso" rev="&teavm.version;"/>
<dependency conf="tea-deps->default" org="org.teavm" name="teavm-core" rev="&teavm.version;"/>
<dependency conf="tea-deps->default" org="org.teavm" name="teavm-jso-apis" rev="&teavm.version;"/>
<dependency conf="tea-deps->default" org="org.teavm" name="teavm-cli" rev="0.7.0"/>
```

**Comment by ianmjackson** [comment]
I have just read [this](https://groups.google.com/g/teavm/c/2G2A2T5TKCo/m/oTp56I9yAQAJ).

We use `TeaVMRunner` in our Ant build. If this is an unsupported build workflow, maybe that is the problem?

**Comment by konsoletyper** [comment]
For me that works. The presence of field accessors, as well as other methods, depend not on how you *declare* them, but how you *access* them. Can you please provide self-contained example to reproduce the problem?

**Comment by konsoletyper** [comment]
@ianmjackson you should use TeaVM API rather than CLI to integrate with build systems. See `TeaVMTool` class and please look through sources of Maven and Gradle plugins respectively. I guess you are trying to use CLI artifact as a standalone JAR, which is not the case any more.
