### ISSUE TITLE
DataOutputStream.write freezes program.

### ISSUE THREAD

**Issue by PeytonPlayz595** [konsoletyper/teavm#725]
Whenever I use DataOutputStream.writeByte the entire page feezes.

```java
ByteArrayOutputStream bos = new ByteArrayOutputStream();
new DataOutputStream(new GZIPOutputStream(bos)).write(byteHere);
```
There are no errors in the console and the page just becomes unresponsive.

**Comment by konsoletyper** [comment]
Could not reproduce. Can you provide more details and/or self-contained project?
