### ISSUE TITLE
AsyncCallback JSObjects nulls out

### ISSUE THREAD

**Issue by Den-Hovenbagen** [konsoletyper/teavm#734]
It is indeed possible to convert the parsed Uint8Array to byte[]. And return a byte[] from the AsyncCallback.
`@JSBody(params = {"data"}, script = "return data;")
	public static native byte[] conversion(Uint8Array data);`
 Once returned; convert the byte[] back to Uint8Array. However, for huge arrays these operation, especially the inital conversion, can be extremely slow.

JSObject callback would be required for tasks where conversions are not optimal or suitable. Here is a simplified test to show-case the issue:
Note, that this issue also applies to: JSNumber, JSString, JSBoolean, etc.

    public static void main(String args[]) throws InterruptedException {
    Uint8Array arr = Uint8Array.create(256);
          for (int i = 0; i < arr.getLength(); i++) 
           arr.set(i, (byte) i);
          System.out.println(retrieve(arr).getLength());
    }

	@Async
	public static native Uint8Array retrieve(Uint8Array arr);

	public static void retrieve(Uint8Array arr, AsyncCallback<Uint8Array> callback) {
		System.out.println(arr.getLength());
		callback.complete(arr);
	}
	
Output : 256
Output: �

My question therefore is - are there any alternatives for what I am trying to accomplish? {retrieve and return Uint8Array asynchronously fast and efficiently}

**Comment by konsoletyper** [comment]
In this particular case it looks like bug. You can try to workaround by passing `Uint8Array` in some wrapper class. Also, to avoid copying arrays, you can use `@JSByRef`. Note that you should use this annotation on your own risk - it violates Java semantics. Additionally I'm thinking about improving `ByteBuffer` implementation performance and introducing ability to support `ByteBuffer` directly in JSO.

**Comment by Den-Hovenbagen** [comment]
I tried @JSByRef and was hit by some stacktraces. Wrapping it seems like the solid solution for now. Good call. Appreciate the quick in depth answer 👍
