### ISSUE TITLE
Add support for AtomicReferenceFieldUpdater

### ISSUE THREAD

**Issue by Maddin-M** [konsoletyper/teavm#750]
Hello!

I use [libGDX](https://github.com/libgdx/libgdx) and its Kotlin extensions [KTX](https://github.com/libktx/ktx) to create a multiplattform application and ran into the following problem:

When adding a serializable enum class and using it (therefore compiling it into JavaScript) the application crashes when opened.
`java.lang.RuntimeException: (JavaScript) ReferenceError: jl_NoClassDefFoundError__init_ is not defined`

How to reproduce:
1. Checkout KTX's template project [Sample Web Project](https://github.com/libktx/ktx-sample-web-project)
2. Make sure it compiles and works in the browser: `./gradlew teavm:run`
3. Add the Kotlinx Serialization dependency (in `core/build.gradle`)
```
plugins {
  id "org.jetbrains.kotlin.plugin.serialization" version "1.9.10"
}

dependencies {
  api "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.6.0"
}
```
4. Add a serializable enum class and instantiate it (in `core/src/main/kotlin/ktx/demo/Main.kt`)
```
@Serializable
enum class Foo {
    FOO, BAR,
}

(...)

private val myEnum = Foo.BAR
```
5. Run the app, it will compile but crash upon opening localhost:8080 in the browser

I hope this issue fits here as I am aware that the problem could potentially lie in the frameworks that I use but maybe someone here will have some insight, am not a TeaVM nor a JS expert.

Thank you!

**Comment by konsoletyper** [comment]
I reproduced the steps and libGDX builder reported following error:

```
#################################################################
| ERROR[0]
| Class: kotlin/LazyJVM.kt:124
| Method: kotlin.SafePublicationLazyImpl.<clinit>()V
| Text: Class java.util.concurrent.atomic.AtomicReferenceFieldUpdater was not found
```

Unfortunately, this message is not descriptive enough. For some reason libGDX does not use TeaVM Gradle plugin, they wrote their own "builder", which does not report full errors. Anyway, from this I can conclude that Kotlin serialization library is using `AtomicReferenceFieldUpdater` class, which currently is not supported by TeaVM.

**Comment by konsoletyper** [comment]
I suggest that AtomicReferenceFieldUpdated can be implemented soon, but in a bit limited way: only when it was constructed with constant values. This should be enough for this particular case in Kotlin stdlib and in similar cases.
