### ISSUE TITLE
Gradle migration broke JPMS support

### ISSUE THREAD

**Issue by hohwille** [konsoletyper/teavm#778]
MAINFEST.MF from Maven build (`teavm-jso-apis-0.7.0-dev-1209.jar`):
```
Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.3.0
Build-Jdk-Spec: 17
Automatic-Module-Name: org.teavm.jso.apis
```
New MAINFEST.MF from Gralde build (`teavm-jso-apis-0.9.0-dev-13.jar`):
```
Manifest-Version: 1.0
```

This bug prevents usage of TeaVM with JPMS (Java-Modules):
```
t mmm-marshall-tvm-xml: Compilation failure: Compilation failure:
[ERROR] D:\projects\mmm\workspaces\main\marshall\impl\tvm-xml\src\main\java\module-info.java:[14,31] error: module not found: org.teavm.jso
[ERROR] D:\projects\mmm\workspaces\main\marshall\impl\tvm-xml\src\main\java\module-info.java:[16,35] error: module not found: org.teavm.jso.apis
```

Breaking change from commit [8014c03](https://github.com/konsoletyper/teavm/commit/8014c038c0090540bda5e9f294904f72c4a11edb)

**Comment by hohwille** [comment]
I prefer maven but I found some hint how this could be done with gradle:
https://github.com/eseifert/vectorgraphics2d/issues/76

**Comment by hohwille** [comment]
Same problem with `0.9.0-dev-14` that has just been released.

**Comment by konsoletyper** [comment]
Sorry, I don't understand what you mean. How are you using TeaVM with JPMS?

**Comment by hohwille** [comment]
> Sorry, I don't understand what you mean. How are you using TeaVM with JPMS?

https://github.com/m-m-m/ui-tvm/blob/8c00f31d9e56b42a82d68989444a4b6301a67a94/core/src/main/java/module-info.java#L21-L23

Or

https://github.com/m-m-m/marshall/blob/2f5719746077254372de00a78a3d1d94b954aa59/impl/tvm-xml/src/main/java/module-info.java#L14-L16

Projects that are using JPMS and have a `module-info.java` are forced by the design of JPMS to only use other modules and require them in their `module-info.java`. Libraries that are not modules or do not have at least an `Automatic-Module-Name` can more or less not be used and accessed (technically it is theoretically possible to reference them by a generated name but that one is derived from the JAR file and this approach is entirely discouraged and all tools are flooding you with warnings that you should not do that and never publish a release with such module dependencies).
So in order to keep TeaVM usable for "modern Java projects" you should really fix this even if you do not care about JPMS at all in your TeaVM project what is fully fine and IMHO would not really bring much added value.

**Comment by konsoletyper** [comment]
Ok, but for what reason anyone would describe all these JPMS modules in their projects? What problem do they solve? What problem do you solve in you m-m-m adding these module-info.java in your projects?

**Comment by hohwille** [comment]
I guess this discussion is drifting apart but if you want some arguments:
* https://dzone.com/articles/java-modules-benefits
* https://stackoverflow.com/questions/55686575/java-platform-modules-system-whats-the-point-of-protection
* It is also security and Oracle decided to drop the `SecurityManager` from Java/JDK and argued that JPMS is the new alternative security concept. Indeed if JPMS is actually used by an app then inner code (packages not exportet) are inaccessible to other modules and most probably to attackers for direct access.

**Comment by hohwille** [comment]
Why do people use JEE and annotate their code with `@Inject`, etc.? Why do you use Java at all?

**Comment by hohwille** [comment]
Thanks for merging and creating `0.9.0-dev-15`. I can confirm the issue is resolved and my build is working again with that version.
Awesome 👍
