### ISSUE TITLE
TypeError: Cannot read property 'owner1652' of undefined

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#81]
I'm running into an issue that I'm having trouble tracking down:

~~~
Root cause is Cannot read property 'owner1652' of undefined at "TypeError: Cannot read property 'owner1652' of undefined
    at jl_Object6_isEmptyMonitor3354 (file:///Users/shannah/cn1_files/incubator/teavmtests/teavmtest1/target/teavmtest1-0.0.1-SNAPSHOT/teavm/classes.js:4952:30)
    at jl_Object6_monitorExit3360 (file:///Users/shannah/cn1_files/incubator/teavmtests/teavmtest1/target/teavmtest1-0.0.1-SNAPSHOT/teavm/classes.js:5098:11)
    at jl_Object6_monitorExit3359 (file:///Users/shannah/cn1_files/incubator/teavmtests/teavmtest1/target/teavmtest1-0.0.1-SNAPSHOT/teavm/classes.js:5029:5)
    at file:///Users/shannah/cn1_files/incubator/teavmtests/teavmtest1/target/teavmtest1-0.0.1-SNAPSHOT/teavm/classes.js:87366:25
    at file:///Users/shannah/cn1_files/incubator/teavmtests/teavmtest1/target/teavmtest1-0.0.1-SNAPSHOT/teavm/runtime.js:506:22
    at file:///Users/shannah/cn1_files/incubator/teavmtests/teavmtest1/target/teavmtest1-0.0.1-SNAPSHOT/teavm/runtime.js:496:18"
~~~

The section that crashes:

~~~
function jl_Object6_isEmptyMonitor3354($this) {
    if ($this.monitor13 !== null) {
        if (!($this.monitor13.owner1652 === null && (otp_PlatformQueue374_isEmpty$static3347($this.monitor13.enteringThreads1655) != 0 && otp_PlatformQueue374_isEmpty$static3347($this.monitor13.notifyListeners1653) != 0))) {
            return 0;
        }
        $this.monitor13 = null;
        return 1;
    }
    return 1;
}
~~~

If I change `if ($this.monitor13 !== null) {` to `if ($this.monitor13 !== null && $this.monitor13 !== undefined ) {`  I just get an illegalmonitorstate exception.

The project is at 
https://github.com/shannah/cn1-teavm-port

That stack trace doesn't allow me to see back any further than the Platform.launchThread call, so it is difficult to know exactly what user-level code initiated it.

(btw... I have already been able to achieve "hello world" ... I'm now working on the "Kitchen Sink" app ...  so progress has been made).

**Comment by konsoletyper** [comment]
The problem is not in `isEmptyMonitor`. The problem is `undefined` passed to this method. `undefined` should not emerge anywhere in TeaVM. If you want to understand the reason of this bug, you should first figure out where this `undefined` came from.

**Comment by konsoletyper** [comment]
This issue occurs sometimes. The reason is that for some reason `$this` takes number instead of object. I suppose, we again ecountered problem with async parts executing in wrong order.

**Comment by shannah** [comment]
Yes.  I saw this in another instance relating to catching exceptions where calling ex.printStackTrace() caused a similar error because the exception was undefined.  I worked around this at the time by making changes to code, but planned to form a test case for it.   I'm not sure if providing that test case will assist in solving this issue or not.

**Comment by konsoletyper** [comment]
Probably, this issue encounters due to irreducible loop that appears after splitting program. In the latest [async-irreducible](https://github.com/konsoletyper/teavm/tree/async-irreducible) branch KitchenSink works in Google Chrome. However, there is one little bug, when TeaVM tries to do `break` outside of block. I'll fix this later. With this issue Google Chrome refuses to run application with developer's console open, but you can correct this error manually.

**Comment by shannah** [comment]
I discovered the problem (or at least a problem).  The notifyAll() implementation wasn't setting the thread back after notifying listeners.  Here is my change:

~~~
@Sync
    @Rename("notifyAll")
    public final void notifyAll0() {
        if (!holdsLock(this)) {
            throw new TIllegalMonitorStateException();
        }
        TThread thread = TThread.currentThread();
        PlatformQueue<NotifyListener> listeners = monitor.notifyListeners;
        while (!listeners.isEmpty()) {
            NotifyListener listener = listeners.remove();
            if (!listener.expired()) {
                Platform.startThread(listener);
            }
        }
        TThread.setCurrentThread(thread);
    }
~~~

**Comment by shannah** [comment]
Actually, Now I'm not sure that this was an issue at all.  I had some immediate success after this change, but that was likely just to do the non-deterministic nature of this problem.

**Comment by shannah** [comment]
This looks like it could be part of the problem.  In $rt_continue() sets thread.postponed when the stack size hits 40.  But it doesn't check if a previous "postponed" function had already been registered on the thread.  I have made the following modification and it seems to have increased stability substantially:

~~~
function $rt_continue(f) {
   if ($rt_continueCounter++ == 40) {
       $rt_continueCounter = 0;
       return function() {
           var self = this;
           var args = arguments;
           var thread = $rt_getThread();
           var postponed = function(){};
           if (thread.postponed){
                postponed = thread.postponed;
           }
           thread.postponed = function() {
               f.apply(self, args);
               postponed();
           };
       };
   } else {
       return f;
   }
}
~~~

Unfortunately I'm still getting the same error that is the title of this issue, but less frequently now.

**Comment by konsoletyper** [comment]
You don't need to set current thread after notifying threads, since notifying won't affect current thread. Also, this `postponed` was introduces in the latest commit and it can't be the reason. There mustn't be more than one `postponed` per thread. Do you really experience the problem in the `async-irreducible` branch? I don't, I can see Kitchen Sink title and letters moving from left and right until they reach center.

**Comment by shannah** [comment]
Yes I experience it with a sync irreducible.  I may be "fixing" the break
issue incorrectly though.  The postponed fix I implemented allows me to get
much further in the app though I'm still getting some of the same error.

I used break points to confirm that postpones were indeed being overwritten
before being executed.  That's why I put in the fix.

I have committed my latest to the cn1 teavm port project so you should be
able to see what I'm talking about.

**Comment by shannah** [comment]
One observation that may (or may not) be useful.    I have noticed that the Object.wait() sometimes never gets called back, even though notifyAll() is called on the object.  E.g. With code like this:

~~~
final Object lock = new Object();
                loaded = false;
                error = false;
                img.addEventListener("load", new EventListener(){

                    @Override
                    public void handleEvent(Event evt) {
                        new Thread(){

                            @Override
                            public void run() {
                                System.out.println("In handleEvent(load) for image "+img.getSrc());
                                loaded = true;
                                error = false;
                                synchronized(lock){
                                    lock.notifyAll();
                                }
                            }
                            
                        }.start();
                    }
                    
                }, false);
                img.addEventListener("error", new EventListener(){

                    @Override
                    public void handleEvent(final Event evt) {
                        new Thread(){

                            @Override
                            public void run() {
                                System.out.println("In handleEvent(error) for image "+img.getSrc());
                                System.out.println(evt.getType());
                                error = true;
                                loaded = false;
                                synchronized(lock){
                                    lock.notifyAll();
                                }
                            }
                            
                        }.start();
                    }
                    
                }, false);
                while (!loaded && !error){
                    System.out.println("Waiting for image to load "+img.getSrc());
                    synchronized(lock){
                        try {
                            lock.wait();
                        } catch (InterruptedException ex) {
                            Logger.getLogger(HTML5Implementation.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                if (error){
                    System.out.println("Image could not load due to error "+img.getSrc());
                } else {
                    System.out.println("Image loaded "+img.getSrc());
                }
            }
~~~

I confirm (via the print statement) that the notifyAll() method is called on the lock, but the the code never ends up executing past the wait().  I work around problems like this right now by adding a timeout to the wait, so that if the wait() callback never gets called by notify(), it will still be called by the timeout.

This is not 100% of the time - but it happens several times per app run - and that effectively causes it to lock.

**Comment by konsoletyper** [comment]
I've fixed both bugs and merged all my changes into master. Now I can see Kitchen Sink title with labels floating from both sides until they reach center.

**Comment by shannah** [comment]
Everything working flawlessly now.  Thanks for the fast fix.  This is really cool.
