### ISSUE TITLE
What is the difference between gwt jsweet teavm?

### ISSUE THREAD

**Issue by qq1053831109** [konsoletyper/teavm#833]
What is the difference between gwt jsweet teavm?

**Comment by konsoletyper** [comment]
1. I suggest that you ask questions not in issues, but in discussions.
2. The main difference of TeaVM with GWT and JSweet is that it takes bytecode, not source code. This makes it possible to compile also Kotlin and Scala projects, and even mixed ones.
3. Anyway, there's no easy answers. There are plenty of small differences.
