### ISSUE TITLE
Processing Javascript Promises in Java

### ISSUE THREAD

**Issue by aghasemi** [konsoletyper/teavm#845]
Hi,

Is there an example of how to process the return value of a native function when it is a Promise?

To begin with, I had to add `teavm-core` to my dependencies so that I could have the Promise class (it wasn't added by the archetype). 

Promise is not a subclass of JSObject. When I ran the following code:

```java
Promise p =  callModule().cast();
p.then( obj -> {
            System.out.println(obj);
            System.out.println(obj.getClass());
            return null;
});
```

I got `Uncaught TypeError: ia_Client_callModule$js_body$_1(...).$then is not a function`. If I print the output object of `callModule`, it is `[object Promise]`. Is there an extra step required?

Thanks
Best

**Comment by konsoletyper** [comment]
Promises declared in core module have nothing to do with JavaScript Promise class. There's no standard wrapper declared for Promise, so you need to write your own definition.

**Comment by tryone144** [comment]
https://github.com/konsoletyper/teavm/pull/884 introduced `JSPromise` as an interface for native promises. This should cover the above use-case.
