### ISSUE TITLE
Teavm-IO broken after update to 0.10.0-dev

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#847]
Hi @konsoletyper,
Something is wrong after recent changes to teavm-0.10.0-dev-1.
The issue is in the same project: https://github.com/ihromant/teavm-io
After update to 0.10.0-dev-1 ConvertersTest started failing. Other issue is in project that uses it, but I suppose that they are strongly related (failure is when I'm trying to deserialize received JSON).
I tried to update to 0.9.0 (stable), replaced dev version of plugin to stable and issue was solved.
So unfortunately can't check 0.10.0-dev stability because completely broken for now.
Here is failing test: https://github.com/Ihromant/teavm-io/blob/master/converters-impl/src/test/java/ua/ihromant/teavm/io/ConvertersTest.java
Could you please investigate and solve the issue?

**Comment by konsoletyper** [comment]
But the next time I suggest you to try to investigate the issue yourself
