### ISSUE TITLE
when i try to compile it gives me a error

### ISSUE THREAD

**Issue by radmanplays** [konsoletyper/teavm#849]
when i try to compile in gradle it gives me this error : 
severe problem: [ERROR] - class org.teavm.diagnostics.Problem : org.teavm.model.CallLocation@4594161b - Class {{c0}} was not found params: [java.util.Scanner]

**Comment by konsoletyper** [comment]
See explanation here: https://teavm.org/docs/runtime/jso.html

Also, full list of supported classes is available here: https://teavm.org/jcl-report/recent/jcl.html

Unfortunately, you are using some custom builder, so you get this clumsy error instead of proper formatting

**Comment by radmanplays** [comment]
> See explanation here: https://teavm.org/docs/runtime/jso.html
> 
> Also, full list of supported classes is available here: https://teavm.org/jcl-report/recent/jcl.html
> 
> Unfortunately, you are using some custom builder, so you get this clumsy error instead of proper formatting

when will java.util.Scanner be implemented?

**Comment by konsoletyper** [comment]
When I get motivation to do it

**Comment by radmanplays** [comment]
can you set like a release date or somthing?

**Comment by konsoletyper** [comment]
No
