### ISSUE TITLE
unused import function

### ISSUE THREAD

**Issue by wangshuli0315** [konsoletyper/teavm#857]
```
  (import "teavm" "currentTimeMillis" (func $teavm.currentTimeMillis (type $t9)))
  (import "teavm" "logString" (func $teavm.logString (type $t1)))
  (import "teavm" "logInt" (func $teavm.logInt (type $t1)))
  (import "teavm" "logOutOfMemory" (func $teavm.logOutOfMemory (type $t4)))
```

As shown above, these import methods are not used in java applications and should be generated by Teavm by default. How can I configure not to generate these import methods?

**Comment by konsoletyper** [comment]
Are you sure these functions aren't used by application?

**Comment by wangshuli0315** [comment]
Yes, the application I tested was written with an empty main method.

**Comment by konsoletyper** [comment]
This does not mean anything. TeaVM runtime uses it internally. Anyway, I don't see a reason why it's a problem

**Comment by wangshuli0315** [comment]
The generated wasm module I compile needs to run on resource-constrained devices, so I need to make sure the generated wasm file is as small as possible. Is there any way to do this?

**Comment by konsoletyper** [comment]
The generates Wasm file *is* as small as possible in this context. You can't remove anything else.
