### ISSUE TITLE
Error when compiling project with teavm 0.10.0-dev-2

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#860]
Tried to compile private large project with teavm 0.10.0-dev-2. Got the following error:
![Screenshot_2023-11-14_22-35-28](https://github.com/konsoletyper/teavm/assets/2134002/4544e946-8ed2-4bd1-945d-300b47bfbf02)
Will try to reproduce it on smaller publishable project.

**Comment by Ihromant** [comment]
In smaller project it adds zero correctly to second identifier:
![Screenshot_2023-11-14_22-58-13](https://github.com/konsoletyper/teavm/assets/2134002/00da3ac9-175e-46c7-b000-f84865bbcf1b)

**Comment by konsoletyper** [comment]
You can try to debug it on the project that you have

**Comment by konsoletyper** [comment]
`DefaultAliasProvider`, in particular you can place conditional breakpoint on `getStaticMethodAlias`. Also, `DefaultNamingStrategy`: `getFullNameFor(MethodReference method)` and `getNameForInit(MethodReference method)`

**Comment by Ihromant** [comment]
I have another question. I have multi-module maven project. How to launch TeaVM compiler against it in debug mode preferrably in IDEA?

**Comment by konsoletyper** [comment]
By "In debug mode" you mean to attach debugger to TeaVM compiler? In Gradle there's a `daemonPort` property or something like this, which allows to attach with remote debugger (you should also turn on out-of-process build). In case of Maven you can just open TeaVM project and create a Maven run configuration, which builds your project and debug this run configuration - but make sure you turned off out-of-process build.

**Comment by Ihromant** [comment]
Ideally it would be
```java
public static void main(String[] args) {
// configure classpath, TeaVM options, paths etc.
doBuild(); // what should it be?
}
```
Usually it's faster than configure remote debug, connect, fight against source-class mismatch etc.

**Comment by konsoletyper** [comment]
It would be `TeaVMBuilder`, see Maven plugin implementation.

**Comment by Ihromant** [comment]
Many thanks. Hope that I'll be able to run my project in 0.10.0-dev-4 at last.

**Comment by aloraps** [comment]
Same issue on the same version for me:
<img width="545" alt="image" src="https://github.com/konsoletyper/teavm/assets/24554228/b3790bf5-7865-43a0-9b10-1918f1e3c944">

@lhromant
Were you able to resolve this issue?
