### ISSUE TITLE
Support varargs in JSO objects

### ISSUE THREAD

**Issue by Ihromant** [konsoletyper/teavm#866]
Example:
```java
public interface DOMTokenList extends JSObject {
        void add(String... tokens);
        void remove(String... tokens);
}
```
After it https://github.com/konsoletyper/teavm/pull/867 can be merged.

**Comment by konsoletyper** [comment]
What if I implement it in 10 years? Should mentioned PR wait 10 years then?

**Comment by Ihromant** [comment]
Definitely no. I will try to investigate and implement it myself. Will ask questions if something.
