### ISSUE TITLE
Issue with indexed db on latest dev version.

### ISSUE THREAD

**Issue by HoosierTransfer** [konsoletyper/teavm#914]
`Method org.teavm.jso.indexeddb.IDBIndex.unwrapStringArray(Lorg/teavm/jso/JSObject;)[Ljava/lang/String; is marked with @JSByRef, but does not return valid array type
    at org.teavm.jso.indexeddb.IDBIndex.getKeyPath(IDBIndex.java:36)
Method org.teavm.jso.indexeddb.IDBIndex.unwrapStringArray(Lorg/teavm/jso/JSObject;)[Ljava/lang/String; is marked with @JSByRef, but does not return valid array type
    at org.teavm.jso.indexeddb.IDBIndex.getKeyPath$static(IDBIndex.java:36)`

I'm not sure what part of my code causes this error.

**Comment by konsoletyper** [comment]
It's an issue in IndexedDB declarations within TeaVM. The best way to work-around it is to copy these declaration sources into your project and fix them.

**Comment by konsoletyper** [comment]
See https://github.com/konsoletyper/teavm/tree/master/jso/apis/src/main/java/org/teavm/jso/indexeddb
