### ISSUE TITLE
Class replacements outside of java.*

### ISSUE THREAD

**Issue by xupwup** [konsoletyper/teavm#919]
Hi,

I noticed that TeaVM does not do class replacements for classes like org.lwjgl.opengl.GL11C if I put a class named org.teavm.classlib.org.lwjgl.opengl.TGL11C in my project. I also found a comment (https://github.com/konsoletyper/teavm/pull/911#discussion_r1580017972) where this seems to be confirmed. Is there a reason why only java.* is considered? I would be able to improve my code if I could override LWJGL's classes this way.

**Comment by konsoletyper** [comment]
There are several ways to replace lwjgl:

1. You can just create another jar and replace with it original dependency
2. You can apply some configuratoin for TeaVM by providing your own `META-INF/teavm.properties`. See [example](https://github.com/konsoletyper/teavm/blob/master/classlib/src/main/resources/META-INF/teavm.properties). Note that this format is ugly and subject of change in some future (see #791).
3. You can replace classes from within custom plugin.
