### ISSUE TITLE
Stream.ofNullable missing

### ISSUE THREAD

**Issue by Quillraven** [konsoletyper/teavm#930]
Hi,

I tried to introduce [ktx-script](https://github.com/libktx/ktx/tree/master/script) in my project which uses javax.script.ScriptEngineManager in the background and seems like this is not working in TeaVM because of:

```
| ERROR[0]
| Class: javax/script/ScriptEngineManager.java:222
| Method: javax.script.ScriptEngineManager.getEngineBy(Ljava/lang/String;Ljava/util/Map;Ljava/util/function/Function;)Ljavax/script/ScriptEngine;
| Text: Method java.util.stream.Stream.ofNullable(Ljava/lang/Object;)Ljava/util/stream/Stream; was not found
```

From what I saw Stream.ofNullable is not implemented in TeaVM? Can this be added? Or is there an alternative for Kotlin scripting that I could try?

**Comment by konsoletyper** [comment]
`Stream.ofNullable` is not implemented and it can be easily added. However, the whole task of bringing Kotlin compiler to the browser is a tough challenge for TeaVM and I want to discourage you from any attempt to do so.

**Comment by Quillraven** [comment]
okay, thanks for the heads up :)
