### ISSUE TITLE
TimeZone support

### ISSUE THREAD

**Issue by shannah** [konsoletyper/teavm#94]
I am working on adding timezone support.  I have added a few classes (e.g. TimeZone, SimpleTimeZone, etc..) and a few methods to Calendar, GregorianCalendar, etc.. to add timezone support.  

I have also added a couple of native Javascript methods to the runtime which are used by TimeZone.  Currently I only support two timezones:
1. The current timezone of the browser (I have given this timezoneID "LOCAL" for lack of a better idea).
2. GMT

The portions that I have added to the runtime.js file are:

~~~~
function $rt_getTimezoneId(){
    return "LOCAL";
}
function $rt_getTimezoneOffset(name, year, month, day, timeOfDayMillis){
    if ($rt_getTimezoneId()===name){
        var hours = Math.floor(timeOfDayMillis/1000/60/60);
        var minutes = Math.floor(timeOfDayMillis/1000/60)%60;
        var seconds = Math.floor(timeOfDayMillis/1000)%60;
        var millis = timeOfDayMillis % 1000;
        return -(new Date(year, month, day, hours, minutes, seconds, millis).getTimezoneOffset()*1000*60);
    } else if ("UTC"===name || "GMT"===name){
        return 0;
    } else {
        throw new Error("Unsupported Timezone: "+name);
    }
}
function $rt_getTimezoneRawOffset(name){
    if ($rt_getTimezoneId()===name){
        var millis = new Date().getTime();
        var i=0;
        var addDays = 1000 * 60 *60 * 24 * 200; // Check 200 days later
        while ($rt_isTimezoneDST(name, millis) && i++<4){
            millis += addDays;
        }
        return -(new Date(millis).getTimezoneOffset()*1000*60);
    } else if (name==='GMT' || name==='UTC'){
        return 0;
    } else {
        throw new Error("Unsupported Timezone: "+name);
    }
}
function $rt_isTimezoneDST(name, millis){
    if ($rt_getTimezoneId()===name){
        var jan = new Date(this.getFullYear(), 0, 1);
        var jul = new Date(this.getFullYear(), 6, 1);
        var maxOff = Math.max(jan.getTimezoneOffset(), jul.getTimezoneOffset());
        return new Date(millis).getTimezoneOffset()<maxOff;
    } else if (name==='GMT' || name=='UTC'){
        return false;
    } else {
        throw new Error("Unsupported Timezone: "+name);
    }
}
~~~~

And these are used within the Timezone class as follows:

~~~~
@JSBody(params={}, 
            script="return $rt_getTimezoneId(name,year,month,day,timeOfDayMillis)"
            )
    private static native String getTimezoneId();
    
    @JSBody(params={"name","year","month","day","timeOfDayMillis"},
            script="return $rt_getTimezoneOffset(name,year,month,day,timeOfDayMillis)")
    private static native int getTimezoneOffset(String name, int year, int month, int day, int timeOfDayMillis);
    
    @JSBody(params="name",
            script="return $rt_getTimezoneRawOffset(name)")
    private static native int getTimezoneRawOffset(String name);
    
    @JSBody(params={"name","millis"}, script="return $rt_isTimezoneDST(name,millis)")
    private static native boolean isTimezoneDST(String name, long millis);
~~~~

Support for other timezones could easily be added at the javascript level by simply overriding the 4 $rt timezone functions and employing a 3rd party JS library.  I have found a few:

1. https://github.com/mde/timezone-js
2. https://github.com/dbaron/tz.js
3. https://github.com/sproutsocial/walltime-js

I'm not sure whether it makes sense to incorporate full timezone support into TeaVM since the browser doesn't do it natively.  Do you have any suggestions or preferences on how you would prefer it included.

I have updated the existing DateTime tests to pass (they didn't previously take into account DST).  I was about to write some TimeZone tests but without support for any objective timezones except for GMT, much of it would be moot.  I suppose I could embed support for just a couple of timezones - just enough to write tests.

I'll be posting a branch with the changes shortly.

**Comment by konsoletyper** [comment]
I made attempt to add timezone support some time ago, but soon felt pain, thanks to JavaScript with its 'powerful' API. To support timezones, one needs to include entire tzdata into `classes.js`. One of the goals of TeaVM is the size of the generated file, so I don't really like the idea. Do you really need timezone support?

Also, I don't understant why are you including timezone functions into `runtime.js` file. Can't you rewrite these functions in pure Java, using JSO and DOM where needed?

**Comment by shannah** [comment]
Yes.  That's what I figured (not including in classes.js).

I wanted to implement those core methods in runtime.js to make it easy to add support for other timezones.  For example, I can easily override these methods to add support for other timezones using another Javascript library if I want to.

**Comment by shannah** [comment]
Here is the proposed modification.
https://github.com/konsoletyper/teavm/pull/95

**Comment by shannah** [comment]
"I wanted to implement those core methods in runtime.js to make it easy to add support for other timezones."

Although I suppose I could also implement a similar mechanism in Java.  Let me look at this some more and seem if I can remove the javascript stuff.

**Comment by shannah** [comment]
I have removed the changes to runtime.js and moved everything into Java.  The pull request (#95) includes the changes.  I also added tests for TimeZone and Calendar from Apache harmony.  Will be adding the GregorianCalendar test shortly as well.

**Comment by shannah** [comment]
Turns out the tests weren't passing in the browser.  I have made some changes to try to get styles complying with TeaVM conventions.  The latest changes also fix a bug with Date related to the "year" parameters in the constructors and the getYear() and setYear() methods.  (Java Date handles "years" differently than Javascript Date objects do). 

The TimeZone tests are now passing in the browser.  I still need to get the Calendar test passing in the browser before the pull is ready to be merged.

**Comment by shannah** [comment]
I'm at the point where there are only a couple of tests still failing in the Calendar test and they are for features that are more obscure / potentially not needed.   I need to push forward with other aspects now and don't have time to sort out these tests right now.  Would you prefer I comment out the tests that fail, or leave them in, failing, so that someone else (or me later) can identify and fix them?

**Comment by konsoletyper** [comment]
There is TZ database parser in JodaTime, which is under Apache 2.0 license. So we could borrow this parser to convert TZ database into some binary format, filter it by date (say, exclude everything earlier 1980, or as configured by user), and write this binary TZ database into `classes.js`. Then we could take another portion of JodaTime to calculate timezone offsets. There is already some code dealing with CLDR, so it will be easy to include support for timezone names. Please, don't forget that including `TimeZone` class **is not** timezone support. There are timezones in at least `Calendar` and `DateFormat`.

I don't like the idea of including timezones into `teavm-plaform` nor `runtime.js`. There are another ways of making extensible logic, see [ServiceLoader](http://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html).

**Comment by shannah** [comment]
I needed timezone support for Codename One, so our build server is using the add_timezone branch into which I continually merge the latest master when I update.
https://github.com/shannah/teavm/tree/add_timezone

It includes necessary modifications to Calendar and DateFormat.  My strategy is to not include any particular timezones, but to make it pluggable to be able to add timezones easily.  It includes a "special" timezone that I have called "Local" which is just the current browser timezone.  GMT timezones also work (e.g. if you specify a timezone relative to GMT).

If we embedded timezone offsets into classes.js we could use the infrastructure I have set up here for registering for using the timezones quite easily.  If you check the tests I have added you can see how it works.

This branch also includes some important fixes to the Date class as the "year" parameter in the constructor and getYear() method of the Java Date class are handled differently than their counterparts on the Javascript Date class.  If you don't want to include all of these changes, then I can submit a separate pull request to fix just the bug.

**Comment by konsoletyper** [comment]
Please, check out my `timezones` branch. It's almost complete. This implementation embeds very small (about 50kb) packaged IANA timezone database into `classes.js` together with parts of modified Joda Time. Also, I implemented timezone detection algorithm, which tracks timezone history. Unfortunately, this algoritm is rather slow (about 350ms on my machine, and 60ms in warmed up VM).

**Comment by shannah** [comment]
Hi Alexey,

I finally got around to testing this out.  It satisfies the initial needs I had for building some apps in CN1 that require timezones  (i.e. they didn't build before because of missing classes or methods, but now they do). 

I haven't done any explicit testing of Timezone stuff other than observing that projects that used the Timezone APIs appear to work correctly.
