### ISSUE TITLE
obfuscation breaks js by wrongly placed line break

### ISSUE THREAD

**Issue by hontvari** [konsoletyper/teavm#944]
Firefox displays this error on the console:
> Uncaught SyntaxError: expected '=>' on the same line after an argument list, got line terminator example.js:19:514

The referenced line:
`=null;result=JavaArray;cls.$array=JavaArray;}return result;},Cr,Fw=strings=>{FR();Cr=new Array(strings.length);for(let i=0;i<strings.length;++i){Cr[i]=DA(Be(strings[i]));}},E=index=>Cr[index],C1=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},E8=array=>C1(array,0,array.length),Be=str=>str===null?null:Cm(str),BM=str=>str===null?null:str.b4,FR=()=>(()`

If I switch off obfuscation in gradle, then the same code works.

**Comment by konsoletyper** [comment]
Fixed by d0707e53. Please, try to build TeaVM locally and test it with your app
