### ISSUE TITLE
https://teavm.org/docs/tooling/maven.html broken

### ISSUE THREAD

**Issue by jsfan3** [konsoletyper/teavm#945]
Please check this page, it seems broken:
https://teavm.org/docs/tooling/maven.html

It ends with:
_targetType – what code to generate. Following options are supported:
    JAVASCRIPT
    WEBASSEMBLY
    WEBASSEMBLY_WASI
    C_

**Comment by konsoletyper** [comment]
I checked it, what's wrong with the `buildType` option?

**Comment by jsfan3** [comment]
Sorry, it was my reading error. It's okay.
