### ISSUE TITLE
<maven.compiler.source> and </maven.compiler.source>question

### ISSUE THREAD

**Issue by jsfan3** [konsoletyper/teavm#946]
I am starting my first project from scratch with TeaVM. I am not sure about the level of bytecode compatibility. This is my pom.xml: are the maven.compiler.source and maven.compiler.target options correct and necessary?

```
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
</properties>
```

**Comment by konsoletyper** [comment]
Hi. Sorry, I don't fully understand your question. Do you mean something like "does TeaVM support bytecode version more than 8"? TeaVM supports source bytecode for Java up to 21 and it requires at Java 11 to run compiler.

**Comment by jsfan3** [comment]
You answered my question, thank you.
