### ISSUE TITLE
UnsatisfiedLinkError in both the main example from site and from baaldung example

### ISSUE THREAD

**Issue by cohenran** [konsoletyper/teavm#961]
I tried an [example](https://www.baeldung.com/java-teavm) from baaldung, and got:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: org.teavm.jso.browser.Window.current()Lorg/teavm/jso/browser/Window;`
(The example was a copy from [git](https://github.com/eugenp/tutorials/tree/master/libraries-bytecode))

Then I tried the base example fron the TeaVM [site](https://teavm.org/docs/intro/getting-started.html) and got the same exception.

What am I doing wrong?

**Comment by cohenran** [comment]
> Please, read [this](https://teavm.org/docs/intro/getting-started.html) carefully and perform step-by step what's written in it.

I did it, and got the exception I mentiond...
I ran the MAVEN command, did `mvn clean package` then tried to run MainClass.

**Comment by konsoletyper** [comment]
> I ran the MAVEN command, did mvn clean package then tried to run MainClass.

Please, quote that part of [documentation](https://teavm.org/docs/intro/getting-started.html) that says you should run `MainClass`.
