### ISSUE TITLE
java 8 static methods in interfaces are not compiling

### ISSUE THREAD

**Issue by bennylut** [konsoletyper/teavm#97]
when writing and using a static method in an interface the compilation fails.

e.g., the compilation of the program:

```
public interface IfcWithStaticMethod {
  static void doNothing(){}
}

public class Main {
  public static void main(String[] args){
    IfcWithStaticMethod.doNothing();
  }
}
```

is resulted with the error:
 INVOKESPECIAL/STATIC on interfaces require ASM 5 

I checked and saw that TeaVM depends on Asm 5.0.3 but since the method visitor defined in the ProgramParser class on line 370 uses ASM4 opcodes, it cannot handle the new instruction.

**Comment by konsoletyper** [comment]
Please, check with the latest TeaVM. The bug should not appear now.

**Comment by bennylut** [comment]
Thank you, I will check it on this weekend.

Benny.
