### ISSUE TITLE
At least one line in the documentation for overlay constructors

### ISSUE THREAD

**Issue by hontvari** [konsoletyper/teavm#970]
As far as I see, constructors should be implemented by providing a usual Java constructor but with empty body. Could you please confirm this and mention in the documentation? 

ChatGPT hallucinates an annotation for this, which does not exists, or recommends static create methods, which seems to be false, or at least unrelated.

**Comment by konsoletyper** [comment]
Sure, just forgot to mention this in documentation. You are right, if you want to bind JS constructor, then supply (empty) constructor in Java class (actually, you can add whatever code you want, TeaVM will just ignore it). You can examine existing API declarations like [RegExp](https://github.com/konsoletyper/teavm/blob/47c136ccc1f20285fcdfeea94be886d5118f532c/jso/apis/src/main/java/org/teavm/jso/core/JSRegExp.java). Also note that if you want to map non-abstract Java class to JS class, you must annotate it with `@JSClass` annotation.

It's also possible to represent constructors via static method. In this case you can use `@JSBody` declaration. Historically, this was the only way to map constructors, but then direct constructor mapping was added.

**Comment by konsoletyper** [comment]
Added documentation here: https://teavm.org/docs/runtime/jso.html (see 'Mapping constructors' section, you may need to clean cache).

**Comment by hontvari** [comment]
Thank you, the documentation addition is understandable, as well as your comment above.

A new question is appeared in the meantime, but that may be a different issue and not related to htis: what about those "constructor" functions which return an object. Something like in case of stats.js: https://github.com/mrdoob/stats.js/blob/master/src/Stats.js

I tried to declare a constructor but TeaVM issued an error message (during the build?). I solved the case by writing a static create function with @JSBody "return new Stats()". Is that the correct way or is there a way with Java constructor declaration?

**Comment by konsoletyper** [comment]
What build-time error did you get?

As for "function which returns an object". From TeaVM's prospective it's an implementation detail. The only different between "constructors" and "functions" is that when calling former, TeaVM adds 'new' keyword before them. From your example I see that it's ok to just call `Stats()`, so it's not necessary to map it as a constructor.
