### ISSUE TITLE
@JSBody Javadoc

### ISSUE THREAD

**Issue by hontvari** [konsoletyper/teavm#973]
This text is included on  the @JSBody Javadoc:

> Marks abstract member method as a JavaScript method. This is equivalent to the following:
>    @JSBody(params = ..., script = "return new this. methodName(...);")

It seems to me that this is not correct, but I only have basic Javascript knowledge. Looking at for example WebGLRenderingContext this annotation does not make the function create a new object.

**Comment by konsoletyper** [comment]
It's a mistake in javadoc. `new` should not be here. Please, read my answer to another issue you created: https://github.com/konsoletyper/teavm/issues/970

**Comment by hontvari** [comment]
Thank you, I understand now.
