### ISSUE TITLE
debugger statement is swallowed

### ISSUE THREAD

**Issue by hontvari** [konsoletyper/teavm#974]
It seems that javascript debugger statements are missing from the generated code.

Here is the overlay class:
```
public interface JsLang {
    @JSBody(script = "debugger; console.log('XXX'); debugger")
    static void debugger() {}
}
```

Here is the generated code:
```
fjj_JsLang_debugger$js_body$_0 = () => {

    console.log('XXX');

},

```

Even the lines are there for the debugger statements but they are empty.

**Comment by konsoletyper** [comment]
Perpahs. But why do you need this?

**Comment by hontvari** [comment]
> Perpahs. But why do you need this?

It is just more convenient inserting the 'debugger' statement into the IDE into the code I am already woring on, then searching for the line in the browser plain text source map viewer.

**Comment by Ihromant** [comment]
Agree with issue starter. Debugger shouldn't be swallowed. Approach he presented could help to find rare issues when there is a mistake in translation from Java code.
