### ISSUE TITLE
WASM: Should TeaVM use `trunc_sat` instead of `trunc` when floats/doubles are casted to int?

### ISSUE THREAD

**Issue by lax1dude** [konsoletyper/teavm#976]
Hi, another issue I've encountered in my app is it occasionally crashes due to "float unrepresentable in integer range", the source of this is the [`trunc`](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Numeric/Truncate_float_to_int) instruction being used to convert floats/doubles to ints or longs. I think TeaVM should use the nontrapping [`trunc_sat`](https://github.com/WebAssembly/nontrapping-float-to-int-conversions/blob/main/proposals/nontrapping-float-to-int-conversion/Overview.md) instruction for this operation instead to match the behavior of the JVM more closely.

I tested this by modifying TeaVM's `WasmBinaryRenderingVisitor` class to emit `trunc_sat` instead of `trunc` for float-to-int conversions and the float unrepresentable crash no longer happens.

**Comment by konsoletyper** [comment]
Fixed. But please note that this still an issue in C and JS backends, since both don't have any native ways to represent non-trapping conversions. And doing this by inserting manual check would be a performance issue.

**Comment by lax1dude** [comment]
Awesome, thanks
