### ISSUE TITLE
Missing Component Model Methods

### ISSUE THREAD

**Issue by StaticallyTypedAnxiety** [konsoletyper/teavm#982]
I have been attempting to use Teavm for WASM components but I think we might be missing a few things to make them surely work.

Firstly is the CustomSection annotation which can be used to encode the world into the WASM binary. I found an example in the Fermyon repo: https://github.com/fermyon/teavm-wasi/commit/ed22bdcf4f1e69f047dee7fc0790725c25ecd3d5. Secondly are the Cabi Realloc methods which can also be found in the same repo: https://github.com/fermyon/teavm-wasi/blob/master/interop/core/src/main/java/org/teavm/interop/Memory.java

I'm currently using a fork with these pieces of code incorporated and it seems to work fine

**Comment by konsoletyper** [comment]
Sorry, I'm not interested in this

**Comment by StaticallyTypedAnxiety** [comment]
Not interested in Wasi Preview 2 in general? 

No problem I will close this ticket and continue using the fork
