### ISSUE TITLE
HTML Select component - onchange event

### ISSUE THREAD

**Issue by stevepugh99** [konsoletyper/teavm#99]
Apologies if this is a known issue or if I'm doing it wrong, but it looks like a bug as far as I can tell:
The problem is with detecting the change event when a HTML select component is changed.

I have a simple HTML Select component:

            <select id="config-select">
            <option id="configOptionDummy1" value="d1">Dummy1</option>
            <option id="configOptionDummy2" value="d2">Dummy2</option>
            </select>

My java code for detecting the change:

        private static HTMLSelectElement configSelect = (HTMLSelectElement) document.getElementById("config-select");
        .....
        configSelect.addEventListener("change", new EventListener() {
            @Override
            public void handleEvent(Event event) {
                System.out.println("select " + event);
            }
        });

What happens is, at runtime, when the the selection is changed, there is a javascript error of the form:
        TypeError: $this.QG is undefined

**Comment by konsoletyper** [comment]
What version of TeaVM do you use? Did you try to disable minification? Can you send full stack trace of non-minified program?

**Comment by stevepugh99** [comment]
Wow, quick response! :)

OK, so I have now switched off minify. 

I had been using firefox, but couldn't work out how to get the stack trace, so I tried with chrome instead. The error is slightly different but it still goes wrong in the same place. Here is the full error:

Uncaught TypeError: Cannot read property 'data' of undefinedjl_String4_isEmpty172 @ TString.java:151jl_AbstractStringBuilder362_insert376 @ TAbstractStringBuilder.java:81jl_StringBuilder71_insert502 @ TStringBuilder.java:209jl_StringBuilder71_insert376 @ TStringBuilder.java:22jl_AbstractStringBuilder362_insert389 @ TAbstractStringBuilder.java:564jl_StringBuilder71_insert505 @ TStringBuilder.java:167jl_StringBuilder71_insert389 @ TStringBuilder.java:22jl_AbstractStringBuilder362_append388 @ TAbstractStringBuilder.java:560jl_StringBuilder71_append111 @ TStringBuilder.java:113csk_Client$164_handleEvent110 @ Client.java:68(anonymous function) @ classes.js:512(anonymous function) @ Client.java:65

TeaVM version is 0.2.1.

**Comment by konsoletyper** [comment]
Please, use TeaVM version 0.3.0-SNAPSHOT. You should first build it from source code. Simply clone project repository and run `mvn clean install -DskipTests`.

**Comment by stevepugh99** [comment]
Have cloned and compiled latest, and set my teavm version to 0.3.0-SNAPSHOT in the pom. 
But unfortunately the error remains as before.

**Comment by ambahk** [comment]
Steve, you may try to log the event using @JavaScriptBody (TeaVM 0.2.1), see if that makes a difference.

```
	@JavaScriptBody(args = { "o" }, body = "console.log(o)")
	public static native void log(JSObject obj);
```
In 0.3.0-SNAPSHOT the annotation is changed to something else.

**Comment by konsoletyper** [comment]
Logging won't help. I think I realized the reason. `JSObject`s are not completely normal Java objects and they have some restrictions. One is that you can't call `hashCode`, `equals` and `toString` on them. Here, `"select " + event` calls `event.toString()` implicitly. Try to replace it with just

```
System.out.println("select");
```

and see whether it helps.

**Comment by ambahk** [comment]
Quite sure that it's the toString() issue.  Just jumping a step ahead to show how else to display the event object. ;)

**Comment by konsoletyper** [comment]
It's quite easy:

```java
interface Printable extends JSObject {
   @JSMethod("toString")
    String jsToString();
}
((Printable)event).jsToString();
```

But there's no great need to represent event as a string.

**Comment by stevepugh99** [comment]
Nice work guys, it was indeed the event reference. I had only put it in for debug purposes to verify the handleEvent() method was being called.

I notice that it is also not possible to call the methods on the event object, e.g. event.getTarget() 

I see what you mean about it being javascript rather than standard java object. But, not being able to access methods like this might well feel a bit strange to Java developers - I can imagine it tripping them up. Would be good to see a nicer solution for this problem if possible, but anyway, at least I know to avoid that now. Thanks for your speedy assistance with this issue!

**Comment by konsoletyper** [comment]
It's strange that it's not possible to call `event.getTarget()`. Can you create a minimum project that reproduces this issue? Is it reproducible with 0.3.0-SNAPSHOT?

Sorry, but it's not possible to properly implement `toString`, `hashCode` and `equals` on `JSObject`s. Won't ever be possible. So I just claim for Java developers that these objects have very special meaning. They are very low-level, and I hope eventually I'll implement wrappers around them, so regular developers will rarely deal with them directly.

**Comment by stevepugh99** [comment]
The example is the same as above, except I try to print out
System.out.println("select " + event.getTarget());
event.getCurrentTarget() has the same result: TypeError: $this.characters49 is undefined
Happens on 0.3.0-SNAPSHOT as well as 0.2.1.
However event.getType() actually works ok and is equal to "change" as you would expect.

**Comment by ambahk** [comment]
That's because event.getTarget() returns a EventTarget, which is a JSObject.  So your println statement is still trying to execute toString() on a JSObject.  event.getType() returns a java String and therefore it works.
